### ISSUE TITLE
Tasks to complete before making this repo public

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas-stubs#1]
- [x] Set up CI as in the MS project to automatically test the stubs https://github.com/pandas-dev/pandas-stubs/issues/3
- [ ] Figure out how to package the stubs as a `pandas-stubs` project for distribution https://github.com/pandas-dev/pandas-stubs/issues/4

**Comment by Dr-Irv** [comment]
And I have made the repo public.

**Comment by simonjayhawkins** [comment]
> And I have made the repo public.

gr8. let's close this then.

and open separate issues for the tasks mentioned in https://github.com/pandas-dev/pandas-stubs/issues/1#issuecomment-1114960403
