### ISSUE TITLE
BUG: Cannot assign ndarray to `DataFrame`

### ISSUE THREAD

**Issue by bashtage** [pandas-dev/pandas-stubs#100]
**Describe the bug**
Assigning values from a ndarray to a DataFrame errors

**To Reproduce**
```python
import numpy as np
import pandas as pd

df = pd.DataFrame({"a":[1,2,3]}
df.iloc[:, :] = np.array([[-1],[-2],[-3]])
```

error is

```
Incompatible types in assignment (expression has type "ndarray[Any, dtype[Any]]", target has type "Union[float, Series[Any], DataFrame]")
```
**Please complete the following information:**
 - OS: Windows 11
 - OS 22H2
 - Python 3.9
 - mypy 0.961 (compiled: yes)
 - pandas                        1.4.2
- pandas-stubs                  1.4.3.220704

**Comment by Dr-Irv** [comment]
I think just changing https://github.com/pandas-dev/pandas-stubs/blob/99f3b42d23f84b0da92025eeb52db15bac446f25/pandas-stubs/core/frame.pyi#L112
to accept `np.ndarray` would fix this.

PR welcome.
