### ISSUE TITLE
Support Python 3.12 with Pandas 1.5.3

### ISSUE THREAD

**Issue by kerrick-js** [pandas-dev/pandas-stubs#1016]
My company uses Pandas 1.5.3, which from my understanding means that we should use pandas-stubs 1.5.3.230321 (and newer versions like 2.2.3.241009 will not work; please correct me if I'm wrong). We currently use Python 3.10 and are in the process of upgrading to Python 3.12.

[pandas-stubs 1.5.3.230321 specifies "Requires: Python >=3.8, <3.12" on PyPI](https://pypi.org/project/pandas-stubs/1.5.3.230321/). From my understanding, <3.12 wasn't a true requirement, and it was dropped in https://github.com/pandas-dev/pandas-stubs/pull/628, right after 1.5.3.230321 was cut. Unfortunately there was never a 1.5.3.x version of pandas-stubs released without the <3.12 specifier. As a result, we can't upgrade to Python 3.12.

Could you please cut a 1.5.3.x release of pandas-stubs that removes the Python<3.12 requirement?

**Comment by Dr-Irv** [comment]
My suggestion is that you use the latest release of `pandas-stubs`, even though you are using pandas 1.5.3.  (My team actually does this on a large project using pandas 1.5.3 at runtime).  If using the 2.2.3.yymmdd version of the stubs identifies issues in type checking, it means that you are using features in 1.5.3 that won't work with newer versions of pandas, so it is probably a good idea to fix your code to avoid those problems.

The meaning of the version number within `pandas-stubs` is that the testing code we use worked with that version.   It doesn't mean that there is correspondence between the APIs of the version of the stubs and the version of pandas. 

We don't have the bandwidth to backport changes to the stubs and support older versions of pandas.
