### ISSUE TITLE
groupby methods can return Series or DataFrame based on `as_index` variable

### ISSUE THREAD

**Issue by loicdiridollou** [pandas-dev/pandas-stubs#1025]
**Describe the bug**
Depending on the boolean `as_index`, methods on groupby objects will return different type.
This is a follow up for #203,

**To Reproduce**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.
2. Indicate which type checker you are using (`mypy` or  `pyright`).
3. Show the error message received from that type checker while checking your example.

**Please complete the following information:**
 - OS: [e.g. Windows, Linux, MacOS]
 - OS Version [e.g. 22]
 - python version
 - version of type checker
 - version of installed `pandas-stubs`

**Additional context**

**Comment by Dr-Irv** [comment]
Do you think you can create an inventory of methods here in this issue as a checklist, and then as you incrementally fix them, we can know which ones are fixed?

**Comment by loicdiridollou** [comment]
Yes let me add that here so we can see where we are at!

**Comment by loicdiridollou** [comment]
Outstanding methods to typehint:
✅  size
🔴  value_counts
Maybe there are other methods, feel free to append.

**Comment by Dr-Irv** [comment]
I tried a bunch of methods, and I think the only one left to worry about is `value_counts()`.

**Comment by loicdiridollou** [comment]
Agreed, will take care of `value_counts` in a bit, I tried the other methods and they all return `DataFrame` whether we pass `as_index` as True or False.
