### ISSUE TITLE
Incorrect type for the `iterator` argument of the `read_csv` function.

### ISSUE THREAD

**Issue by rudolfbyker** [pandas-dev/pandas-stubs#1060]
https://github.com/pandas-dev/pandas-stubs/blob/b6ae6e8babd2432b681956f109b5c06af779a7c5/pandas-stubs/io/parsers/readers.pyi#L79C1-L79C29

```py
iterator: Literal[True],
```

I think this should be

```py
iterator: bool = ...,
```

**Comment by loicdiridollou** [comment]
The `read_csv` function is overloaded meaning that for different set of arguments it will return different types and this is what we are trying to do. In the case of passing `iterator=True` you will get in return `TextReader`.
If you look below you have a different version of the `read_csv` with `iterator: bool`:
https://github.com/pandas-dev/pandas-stubs/blob/b6ae6e8babd2432b681956f109b5c06af779a7c5/pandas-stubs/io/parsers/readers.pyi#L144
So you have another version with the arguments you expect. Is that what you intended?

**Comment by rudolfbyker** [comment]
Sorry, I did not notice the overload! I guess there is no problem, then. I was using this with the `tightwrap` module, and I think that module only looks at the first overload. So it should be fixed over there...
