### ISSUE TITLE
Literal "calamine" missing from ExcelFile engine attribute

### ISSUE THREAD

**Issue by sanzoghenzo** [pandas-dev/pandas-stubs#1061]
**Describe the bug**

#898 missed the [`engine` attribute of the `ExcelFile` class](https://github.com/pandas-dev/pandas-stubs/blob/b6ae6e8babd2432b681956f109b5c06af779a7c5/pandas-stubs/io/excel/_base.pyi#L249C1-L249C75).

**To Reproduce**

```python
import pandas as pd

with pd.ExcelFile("path.xlsx", engine="calamine") as xlsx:
   pass
```

using mypy I got

```
error: Argument "engine" to "ExcelFile" has incompatible type "Literal['calamine']"; expected "Literal['xlrd', 'openpyxl', 'odf', 'pyxlsb'] | None"  [arg-type]
```

**Please complete the following information:**
I don't think it matters, but:
 - OS: Windows 10 22H2
 - python v3.10
 - mypy v1.13.0
 - `pandas-stubs`  v2.2.3.241126

**Comment by loicdiridollou** [comment]
That is correct, it was missed there! Seems like a small addition to be made in the `pandas-stubs/io/excel/_base.pyi`. Open to PR with tests in `tests/test_io.py`.
