### ISSUE TITLE
__iter__ method of a Series should be type annotated

### ISSUE THREAD

**Issue by diepala** [pandas-dev/pandas-stubs#119]
**Describe the bug**

A type checker can not correctly resolve the return type of the `__iter__` method of a pandas series.

**To Reproduce**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.
```python
from typing_extensions import reveal_type
import pandas as pd

series = pd.Series([1, 2, 3], dtype=int)
reveal_type(series) # type = Series[int]
iterable = iter(series)
reveal_type(iterable) # type = Unkown, type should be Iterable[int]
```
2. Indicate which type checker you are using (`mypy` or  `pyright`).

I am using pyright 1.1.257

3. Pyright message
```
  /home/pandas_types.py:5:13 - information: Type of "series" is "Series[int]"
  /home/pandas_types.py:7:13 - information: Type of "iterable" is "Unknown"
```

**Please complete the following information:**
 - OS: Linux
 - OS Version: Ubuntu 22.04
 - python version: 3.10.4
 - version of type checker 1.1.257
 - version of installed `pandas-stubs` 1.4.3.220704

**Comment by Dr-Irv** [comment]
Need to remove 
```python
    def __iter__(self) -> Iterator: ...
```
from `core/generic.pyi` and add to `core/series.pyi` :
```python
    def __iter__(self) -> Iterator[S1]: ...
```

PR welcome

**Comment by diepala** [comment]
I will try to make a PR. Why is it needed to remove `__iter__` from generic.pyi?

**Comment by Dr-Irv** [comment]
> I will try to make a PR. Why is it needed to remove `__iter__` from generic.pyi? 

In the implementation, `__iter__()` is only defined (but not typed) in `generic.py`.  But we want different results for `DataFrame.__iter__()` and `Series.__iter__()`, so our convention is to be explicit about methods like that in `frame.pyi` and `series.pyi`, and remove the definition in the base class.

> Also, is the `S1` variable covariant or invariant? I haven't been able to find its definition.

It's in `pandas-stubs/_typing.pyi` .  We use it to make `Series` generic in the stubs (even though it is not generic in the implementation).

**Comment by diepala** [comment]
Thanks for the info! Also, is there any reason for a Series not being a Sequence?

**Comment by Dr-Irv** [comment]
> Also, is there any reason for a Series not being a Sequence?

`Series` does not implement `__reversed__`

**Comment by bashtage** [comment]
Wonder if it would be useful to add `__reversed__` so that `Series` could be used anywhere that a `Sequence` is needed. This would be for main pandas though.

**Comment by bashtage** [comment]
@Dr-Irv looks like `Series` cannot be a `Sequence` since a `Sequence` needs to implement:

* `__getitem__`
* `__len__ `
* ` __contains__`
* `__iter__`
* `__reversed__`
* `index`  << Not possible since `index` returns the `index` and cannot be `index(loc: int)`.
* `count`

This is somewhat unfortunate but forever unchangeable I'm sure.
