### ISSUE TITLE
ADMIN: manage differences between how this would evolve versus the Microsoft stubs. 

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas-stubs#12]
At some point, they will cut over and take what we have here.

**Comment by Dr-Irv** [comment]
I've contacted them and suggested that they pull from our repo to make the VS Code distributions and delete the stubs from their repo.  They are moving forward with a plan to do that.

**Comment by gramster** [comment]
That is our plan. We will modify the process we use to generate our stubs bundle to pull from here, and retire the stubs in our repo.

We are very pleased with this outcome (and very grateful to Irv for being a big driver and advocate for this); it means we can switch focus to some other packages and hopefully get to the same place.

**Comment by Dr-Irv** [comment]
Based on https://github.com/microsoft/python-type-stubs/pull/208 , Microsoft has retired their stubs, and is pulling the stubs that go with pylance from here.  Closing.
