### ISSUE TITLE
CI failing on Windows - maybe due to poetry.lock

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas-stubs#121]
See https://github.com/pandas-dev/pandas-stubs/runs/7256706305?check_suite_focus=true which happened after I merged a PR to `main`.  Might be due to the `poetry.lock` stuff??

**Comment by Dr-Irv** [comment]
> It could be a instabability in pypi serve, did you try to re-run the failed job again?

Yes, I did.  It failed the second time as well.  Looking at the log, it is failing when doing an install.

**Comment by BrenoJesusFernandes** [comment]
maybe replacing in CI file `poetry install -vvv --no-root` with `poetry update -vvv` could fix it.

**Comment by twoertwein** [comment]
if it is caused by poetry.lock, a simple workaround is to make any change to pyproject.toml.

I think poetry update, would also ignore the poetry.lock

**Comment by Dr-Irv** [comment]
I updated `pyproject.toml` and now `main` is passing. 

@BrenoJesusFernandes or @twoertwein - can one of you create a PR that does what was suggested here? https://github.com/pandas-dev/pandas-stubs/issues/121#issuecomment-1179278018

I'm concerned that if I merge in the future, then I'll have the same problem where a PR looks good, but I merge, and then the action on `main` fails.

**Comment by twoertwein** [comment]
In theory, peotry.lock should exactly be the same across different python and OS version. I will create a PR to cache poetry-lock separately for each OS/python version.  If it still fails then, then it could be a poetry/network issue.

**Comment by BrenoJesusFernandes** [comment]
> maybe replacing in CI file `poetry install -vvv --no-root` with `poetry update -vvv` could fix it.

@twoertwein I tested here this idea and it looks like it works

**Comment by twoertwein** [comment]
Doesn't update completely ignore poetry.lock? Meaning we get no speedup by caching poetry.lock? Could go back to caching the entire venv. Personally, I find caching poetry.lock very elegant, one small file (almost no overhead on a miss) and quite some speedup.

**Comment by BrenoJesusFernandes** [comment]
hmm I see the point, I totally forgot about the cache system.

**Comment by twoertwein** [comment]
unrelated: do we need to update pip on the CI? It seems that it is already the newest version and in [some cases](https://github.com/pandas-dev/pandas-stubs/runs/7259308979?check_suite_focus=true) checking for updates takes 50 seconds.

**Comment by BrenoJesusFernandes** [comment]
Personally, I don't think is necessary.

**Comment by Dr-Irv** [comment]
> Personally, I think we should remove the pip upgrade.

@twoertwein @BrenoJesusFernandes do either of you want to submit a PR to remove the pip upgrade?  (or was it done and we can close this issue)

**Comment by twoertwein** [comment]
do you have opinions about `pip` vs `pipx` (I don't)? When I was looking at https://github.com/actions/setup-python#caching-packages-dependencies they use pipx in the poetry example

**Comment by Dr-Irv** [comment]
Until now, I hadn't heard of `pipx`.  Based on the docs at https://pypa.github.io/pipx/comparisons/#:~:text=to%20Other%20Tools-,pipx%20vs%20pip,install%20packages%20with%20cli%20entrypoints., I would stick with `pip`
