### ISSUE TITLE
black, isort, flake8 should run locally

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas-stubs#125]
The pre-commit hook should run locally so that it passes `black`, `isort` and `flake8` before doing a local commit.

It used to be that there was a `poe` command to run `black` and `isort`, but that seems to have disappeared.

**Comment by twoertwein** [comment]
I probably removed that when switching to pre-commit. I assumed that people just install the pre-commit hook.

**Comment by Dr-Irv** [comment]
> I assumed that people just install the pre-commit hook.

Maybe we need instructions on how to do that.
