### ISSUE TITLE
[Bug] `DataFrame.set_index` does not accept `pd.Index` anymore.

### ISSUE THREAD

**Issue by alkatar21** [pandas-dev/pandas-stubs#140]
**Describe the bug**
`DataFrame.set_index` does not accept `pd.Index` anymore.

**To Reproduce**
```py
# pyright: strict, reportUnknownMemberType=false
"""Example."""
import pandas as pd

df = pd.DataFrame()
expected = df.set_index(pd.Index([])) # Argument of type "Index" cannot be assigned to parameter "keys" of type "Label | Sequence[Unknown]" in function "set_index"
```
![grafik](https://user-images.githubusercontent.com/61387986/179023921-f2eef8d4-7511-4df8-a869-8db90922641e.png)

**Please complete the following information:**
 - OS: Linux
 - OS Version: 20.04
 - python version: 3.8.10
 - version of type checker: pylance v2022.7.31 (not in v2022.7.30)
 - version of installed `pandas-stubs`: i belive `_stub_version = Literal["1.4.3.220710"]` (pylane bundled)

**Additional context**

**Comment by Dr-Irv** [comment]
Thanks for the report.  Docs say:
> This parameter can be either a single column key, a single array of the same length as the calling DataFrame, or a list containing an arbitrary combination of column keys and arrays. Here, “array” encompasses [Series](https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series), [Index](https://pandas.pydata.org/docs/reference/api/pandas.Index.html#pandas.Index), np.ndarray, and instances of [Iterator](https://docs.python.org/3/library/collections.abc.html#collections.abc.Iterator).

So we need to update the parameters in `frame.pyi` and add tests in `test_frame.py`

PR welcome!

**Comment by twoertwein** [comment]
This is probably a result of `Index` no longer being declared as `Hashable`.

**Comment by Dr-Irv** [comment]
> This is probably a result of `Index` no longer being declared as `Hashable`.

Good find.  We should probably be explicit in saying that `Series`, `Index`, `np.ndarray` and `Iterator[Hashable]` are valid (and remove `Sequence`)
