### ISSUE TITLE
Use PEP 604 style annotations

### ISSUE THREAD

**Issue by twoertwein** [pandas-dev/pandas-stubs#150]
We might consider using the new(er) type annotation system (replace `Union` with `|`, use `list` and so on):

- Pandas uses them universally since https://github.com/pandas-dev/pandas/pull/47769
- and based on [flake8-pyi](https://github.com/PyCQA/flake8-pyi) those annotations are supported in almost all cases (as far as I understand we shouldn't be using them in `pandas/_typing.pyi` where we define most/all the type aliases):

> Y037 (enforcing PEP 604 syntax everywhere) is not yet fully compatible with the mypy type checker, which has [a few bugs](https://github.com/python/mypy/issues?q=is%3Aopen+is%3Aissue+label%3Atopic-pep-604+label%3Atopic-type-alias) regarding PEP 604 type aliases.

**Comment by Dr-Irv** [comment]
My only concern here is compatibility with python 3.8.  Maybe we just have to do `from future import __annotations__` throughout.

**Comment by twoertwein** [comment]
As a first step we could only change pyi files (not the tests). pyi files do not need `from future import __annotations__`. flake8-pyi:

> Y044:  `from __future__ import annotations` has no effect in stub files, as forward references in stubs are enabled by default.

Adding the future imports to the tests would be fairly easy as there are only a few (but large) test files.

**Comment by Dr-Irv** [comment]
You're certainly welcome to try to  make the changes in a PR!
