### ISSUE TITLE
Index.difference should allow for None values in the "other" list

### ISSUE THREAD

**Issue by svetlin-mladenov** [pandas-dev/pandas-stubs#17]
Currently the type annotation for [Index.difference](https://github.com/pandas-dev/pandas-stubs/blob/main/typings/pandas/core/indexes/base.pyi#L152) is

```python
def difference(self, other: Union[List[T1], Index]) -> Index: ...
```

`None` values are disallowed for the `other` argument if it is a list. As a result of that the following code, which runs perfectly fine, will give an error when `mypy` is used to check it:

```python
from pandas.core.indexes.api import Index

index = Index(["a", "b", "c"])
index.difference(["a", None])
```

I think the function type should be changed to:
```python
def difference(self, other: Union[List[Optional[T1]], Index]) -> Index: ...
```

**Comment by Dr-Irv** [comment]
Thanks @svetlin-mladenov for the report.  This is fixed in #18 and now in `main`
