### ISSUE TITLE
BUG: groupby by argument raises with mypy when argument is annotated as ``list[str]``

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas-stubs#187]
**Describe the bug**

Using ``df.groupby(by=cols)`` where cols is annotated as ``list[str]`` raises a mypy error

```
error: Argument "by" to "groupby" of "DataFrame" has incompatible type "List[str]"; expected "Optional[Union[Tuple[Any, ...], List[Optional[Hashable]], Union[ufunc, Callable[..., Any]], Series[Any], ndarray[Any, Any], Mapping[Optional[Hashable], Any], Index]]"  [arg-type]
``` 

**To Reproduce**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.
2. Indicate which type checker you are using (`mypy` or  `pyright`).
3. Show the error message received from that type checker while checking your example.

```
def _call_groupby(df: pd.DataFrame, cols: list[str]):
    df.groupby(by=cols).count()
```

This also raises when adding:

```
    cols: list[str] = ["col1", "col2"]
    df.groupby(by=cols).sum()
```

to ``test_types_groupby`` in ``test_frame.py``

``list[str]`` should be valid? If passing simply ``["col1", "col2"]`` without an annotation this works

**Please complete the following information:**
 - OS:  ubuntu
 - OS Version 22.04
 - python version 3.10
 - version of type checker mypy 0.971
 - version of installed `pandas-stubs` newest 20220807

**Additional context**

**Comment by twoertwein** [comment]
Should probably replace `list[Hashable | None]` with `list[HashableT]` (`None` is hashable).
