### ISSUE TITLE
No types for DatetimeIndex attributes

### ISSUE THREAD

**Issue by ruler501** [pandas-dev/pandas-stubs#193]
**Describe the bug**
```python
import pandas

x = pandas.DatetimeIndex()
x.month
```
Fails to typecheck in mypy even though this attribute is documented here https://pandas.pydata.org/docs/reference/api/pandas.DatetimeIndex.month.html

**To Reproduce**
1. Run type checker of your choice on the above snippet with latest version of pandas and pandas-stubs

**Please complete the following information:**
 - OS: Linux
 - OS Version NixOS unstable
 - python version 3.9.13
 - version of type checker mypy 0.971
 - version of installed `pandas-stubs` 1.4.3.220807

**Additional context**
Also tested with pyright language server and got same error, not sure what version of pyright.

**Comment by Dr-Irv** [comment]
Thanks for reporting this.  We'll have to change `pandas.core.indexes.accessors.pyi` to use `Generic` so that it works right for `Series.dt` and `DatetimeIndex`.   I've started to work on this

**Comment by ruler501** [comment]
Thanks. I also noticed some issues with indexing dataframes I'll try to document the failures and report them too.
