### ISSUE TITLE
"key" parameter typing is incorrect in the DataFrame.xs method

### ISSUE THREAD

**Issue by jbiz25** [pandas-dev/pandas-stubs#214]
**Describe the bug**
mypy reports an error when using the DataFrame.xs() method.  DataFrame MultiIndexes can easily accept non-string labels, such as ints.  In fact, this is very common.  

**To Reproduce**
Create a script like below and run mypy.  You will see mypy reporting an error about the "key" positional argument, which I assert is not a true error.

import pandas as pd
mi = pd.MultiIndex.from_product([[0, 1], [0, 1]], names=["foo", "bar"])
df = pd.DataFrame({"x": [10, 20, 30, 40], "y": [50, 60, 70, 80]}, index=mi)
df.xs(0, level="foo")

**Please complete the following information:**
 - OS:  Windows
 - OS Version 10
 - python version 3.8
 - version of type checker mypy 0.971
 - version of installed `pandas-stubs` 1.4.3.220724

**Comment by Dr-Irv** [comment]
Have to change the `key` argument in `generic.pyi` from `key: _str | tuple[_str],` to `key: Hashahble  | tuple[Hashable],

PR welcome

**Comment by twoertwein** [comment]
`Hashable` alone might also work, `tuple[Hashable]` should be `Hashable`
