### ISSUE TITLE
Review expected failures

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas-stubs#217]
In #213 @twoertwein marked typing tests that we expect to fail using `TYPE_CHECKING_INVALID_USAGE` .  The idea here is that we are testing code that we want the type checkers to pick up as being incorrect.  In many cases, `pyright` does figure that out.  `mypy` figures it out sometimes, and there are occasions where both type checkers see what we expect to fail as "correct" code.

At some point in time in the past, when the stubs were in the Microsoft repository, those tests were doing the "right" thing, i.e., both type checkers were marking those tests as "failures", and the `# type: ignore` comments were correct, in the sense that the type checkers saw that they were correct ignores.

Now, possibly due to changes in the settings used for `mypy` and `pyright`, as well as evolutions in the type checkers themselves, those tests are no longer failing as we expect them to.   Some investigation is required to determine whether this is due to something changing in the stubs, or to particular settings in the type checkers.

**Comment by twoertwein** [comment]
I think why 
https://github.com/pandas-dev/pandas-stubs/blob/417c3d0f8301e2eee0fc75d492f9f1eb74d2bca5/tests/test_timefuncs.py#L208
works might be because of this overload https://github.com/pandas-dev/pandas-stubs/blob/417c3d0f8301e2eee0fc75d492f9f1eb74d2bca5/pandas-stubs/core/series.pyi#L1163
