### ISSUE TITLE
TST: Add an unfailable CI run against pandas main

### ISSUE THREAD

**Issue by bashtage** [pandas-dev/pandas-stubs#218]
It would probably be a good idea to add a CI run against pandas main.  Ideally, this would use nightly wheels to save on time.  Not sure how easy this is with poetry and the current CI setup.

**Comment by bashtage** [comment]
The CI run would be info only, but would make it easier to see any upcoming changes.  It would be green for pass, and yellow for fail, but never red.

**Comment by Dr-Irv** [comment]
Agree this is a good idea.  PR welcome!

**Comment by twoertwein** [comment]
> Not sure how easy this is with poetry and the current CI setup.

Could simply give `poe pytest` a `--nightly` option, similar to stubtest https://github.com/pandas-dev/pandas-stubs/pull/184
