### ISSUE TITLE
CustomBusinessDay annotation is not complete

### ISSUE THREAD

**Issue by gandhis1** [pandas-dev/pandas-stubs#222]
The initializer does not appear to match as it is missing `holidays` and `calendar` https://pandas.pydata.org/docs/reference/api/pandas.tseries.offsets.CustomBusinessDay.html

**Comment by Dr-Irv** [comment]
Please provide an example that illustrates a type checker showing an error.

**Comment by gandhis1** [comment]
```
import pandas as pd
from pandas.tseries.offsets import CustomBusinessDay
from pandas.tseries.holiday import USFederalHolidayCalendar

x = CustomBusinessDay(holidays=USFederalHolidayCalendar())
```

> test_case.py:3: error: Skipping analyzing "pandas.tseries.holiday": found module but no type hints or library stubs
test_case.py:3: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
test_case.py:5: error: Unexpected keyword argument "holidays" for "CustomBusinessDay"
.../lib/python3.8/site-packages/pandas-stubs/_libs/tslibs/offsets.pyi:203: note: "CustomBusinessDay" defined here

**Comment by Dr-Irv** [comment]
That's not valid code, but this is and will be fixed in a PR:
```python
from pandas.tseries.offsets import CustomBusinessDay
from pandas.tseries.holiday import USFederalHolidayCalendar

x = CustomBusinessDay(calendar=USFederalHolidayCalendar())
```
