### ISSUE TITLE
All occurences of freq should be a Union[str, BaseOffset]

### ISSUE THREAD

**Issue by gandhis1** [pandas-dev/pandas-stubs#223]
The one bug I could find was the method `bdate_range` which is annotated as a `str`, but my suspicion is there are other occurrences as `freq` is a common parameter

**Comment by Dr-Irv** [comment]
Please provide an example that illustrates a type checker showing an error.

**Comment by gandhis1** [comment]
```
import pandas as pd
from pandas.tseries.offsets import Day, BusinessDay

x = pd.date_range("1/1/2022", "2/1/2022", freq="1D")
y = pd.date_range("1/1/2022", "2/1/2022", freq=Day())
z = pd.bdate_range("1/1/2022", "2/1/2022", freq=BusinessDay())
```

> test_case.py:6: error: Argument "freq" to "bdate_range" has incompatible type "BusinessDay"; expected "str"
Found 1 error in 1 file (checked 1 source file)

**Comment by ojdo** [comment]
Sorry to piggy-back here, but this seems like the best place to ask: in a tiny script, mypy complains about

> Argument "freq" to "date_range" has incompatible type "timedelta"; expected "Union[str, BaseOffset]"

As far as I understand, and [offsets.pyi](https://github.com/pandas-dev/pandas-stubs/blob/07f9398a95d325dbf6302a321493d10aeb130aed/pandas-stubs/_libs/tslibs/offsets.pyi#L100) seems to agree, argument "freq" should also support `timedelta`. Is this a bug in mypy, or should one of the lines in this PR include another `timedelta |` somewhere?

If so, I would be happy to provide a PR. I am just very new to mypy with such heavy stubbing.

**Comment by gandhis1** [comment]
The Pandas documentation for some functions that accept an offset does not seem to include `timedelta`. This interface may vary.

https://pandas.pydata.org/docs/reference/api/pandas.date_range.html

**Comment by gandhis1** [comment]
I will note that this may be in error as the underlying code ultimately calls `to_offset`. So whatever that supports should be supported by the overlying function.

**Comment by Dr-Irv** [comment]
> As far as I understand, and [offsets.pyi](https://github.com/pandas-dev/pandas-stubs/blob/07f9398a95d325dbf6302a321493d10aeb130aed/pandas-stubs/_libs/tslibs/offsets.pyi#L100) seems to agree, argument "freq" should also support `timedelta`. Is this a bug in mypy, or should one of the lines in this PR include another `timedelta |` somewhere?

The main issue here is that the docs for `pd.date_range()` don't say that a `timedelta` (or `pd.Timedelta()`) is a valid argument for `freq`, but the implementation accepts it.  With the stubs, we have been following what's documented.

So can you open an issue in the `pandas` repo saying that `pd.date_range` accepts `timedelta` for the `freq` argument, but it's not documented, and then a determination can be made by the pandas team whether the docs are wrong or the implementation is wrong.

If the docs are wrong, then create a new issue here to update the stubs.  If the implementation is wrong, we leave things here as they are.

**Comment by gandhis1** [comment]
My PR to update the Pandas documentation to include `timedelta` was just accepted. I can open a PR here to match later, unless anyone else wants to go ahead and take care of it.

**Comment by Dr-Irv** [comment]
> My PR to update the Pandas documentation to include `timedelta` was just accepted. I can open a PR here to match later, unless anyone else wants to go ahead and take care of it.

Please submit a PR here.  Thanks!
