### ISSUE TITLE
BaseOffset arithmetic methods (add, sub, etc.) accept a  _DatetimeT but a date is a valid parameter value

### ISSUE THREAD

**Issue by gandhis1** [pandas-dev/pandas-stubs#224]
An error will be given if attempting to subtract an offset from a `datetime.date`

Should be the `Union` of the two

**Comment by Dr-Irv** [comment]
Please provide an example that illustrates a type checker showing an error.

**Comment by gandhis1** [comment]
```
from datetime import date
from pandas.tseries.offsets import Day

x = date.today() - Day()
```

> test_case.py:4: error: No overload variant of "__sub__" of "date" matches argument type "Day"
test_case.py:4: note: Possible overload variants:
test_case.py:4: note:     `def __sub__(self, timedelta) -> date`
test_case.py:4: note:     `def __sub__(self, date) -> timedelta`
Found 1 error in 1 file (checked 1 source file)
