### ISSUE TITLE
Version 1.5 changes

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas-stubs#227]
Need to update stubs for version 1.5 based on docs in RC:
https://pandas.pydata.org/pandas-docs/version/1.5.0rc0/whatsnew/v1.5.0.html

**Comment by phofl** [comment]
How do you want to handle deprecations of arguments? Remove them from the stubs immediately?

**Comment by bashtage** [comment]
I think once we shift to 1.5 as the target we should fully target 1.5 including all deprecations.

**Comment by phofl** [comment]
So if argument x is deprecated we would just remove it from the stubs, correct?

**Comment by bashtage** [comment]
That is what we have been doing.

**Comment by Dr-Irv** [comment]
List of 1.5 things to handle.  As these are addressed, put a check mark and edit this comment to indicate which PR addressed the issue:
- [ ] `pd.ArrayDType`
- [ ] `[DataFrame.__dataframe__()]`
- [ ] `pandas.api.interchange.from_dataframe() `
- [ ] ` Styler.concat() `
- [ ] `Styler.to_string()`
- [ ] `Styler.relabel_index() `
- [ ] ` Styler.highlight_null()` now accepts `color `and deprecates `null_color`
- [ ] The argument `group_keys` has been added to the method `DataFrame.resample()`
- [ ] `pd.from_dummies`
- [ ] ` DataFrame.to_orc()`
- [ ] `read_xml` now supports `dtype`, `converters`, and `parse_dates`
- [ ] `read_xml` now supports large XML using `iterparse`
- [ ] `MultiIndex.to_frame()` now supports the argument `allow_duplicates`
- [ ] `DataFrame.plot()` will now allow the `subplots` parameter to be a list of iterables specifying column groups
- [ ] `Series.reset_index()` and `DataFrame.reset_index(`) now support the argument `allow_duplicates`
- [ ] `read_csv()` now supports `defaultdict` as a `dtype` parameter
- [ ] `DataFrame.rolling()` and `Series.rolling()` now support a `step `
- [ ] Add milliseconds field support for DateOffset 
- [ ] DataFrame.reset_index() now accepts a names argument 
- [ ] Added numeric_only argument to DataFrame.corr(), DataFrame.corrwith(), DataFrame.cov(), DataFrame.idxmin(), DataFrame.idxmax(), DataFrameGroupBy.idxmin(), DataFrameGroupBy.idxmax(), GroupBy.var(), GroupBy.std(), GroupBy.sem(), and DataFrameGroupBy.quantile()
- [ ] Added validate argument to `DataFrame.join()`
- [ ] Added numeric_only argument to Resampler.sum(), Resampler.prod(), Resampler.min(), Resampler.max(), Resampler.first(), and Resampler.last()
- [ ] times argument in ExponentialMovingWindow now accepts np.timedelta64
- [ ] DataError, SpecificationError, SettingWithCopyError, SettingWithCopyWarning, NumExprClobberingError, UndefinedVariableError, IndexingError, PyperclipException, PyperclipWindowsException, CSSWarning, PossibleDataLossError, ClosedFileError, IncompatibilityWarning, AttributeConflictWarning, DatabaseError, PossiblePrecisionLoss, ValueLabelTypeMismatch, InvalidColumnName, and CategoricalConversionWarning are now exposed in pandas.errors
- [ ] Added check_like argument to testing.assert_series_equal()
- [ ] RangeIndex.union() now can return a RangeIndex instead of a Int64Index if the resulting values are equally spaced 
- [ ] DataFrame.compare() now accepts an argument result_names
- [ ] DataFrame.quantile() gained a method argument that can accept table
- [ ] Added copy keyword to Series.set_axis() and DataFrame.set_axis()
- [ ] The method ExtensionArray.factorize() accepts use_na_sentinel=False
- [ ] BigQuery I/O methods read_gbq() and DataFrame.to_gbq() default to auth_local_webserver = True. Google has deprecated the auth_local_webserver = False “out of band” (copy-paste) flow.
- [ ] When read_sas() previously returned None, it now returns an empty DataFrame
- [ ] `ExcelWriter` public attributes:
  - [ ] book
  - [ ] check_extension
  - [ ] close
  - [ ] date_format
  - [ ] datetime_format
  - [ ] engine
  - [ ] if_sheet_exists
  - [ ] sheets
  - [ ] supported_extensions
- [ ] `ExcelWriter` deprecated attributes:
  - [ ] cur_sheet
  - [ ] handles
  - [ ] path
  - [ ] save
  - [ ] write_cells
- [ ] add ` DataFrame.isetitem()`
- [ ] add `numeric_only` to following methods:
  - [ ] DataFrame.corr()
  - [ ] DataFrame.corrwith()
  - [ ] DataFrame.cov()
  - [ ] DataFrame.idxmin()
  - [ ] DataFrame.idxmax()
  - [ ] DataFrameGroupBy.cummin()
  - [ ] DataFrameGroupBy.cummax()
  - [ ] DataFrameGroupBy.idxmin()
  - [ ] DataFrameGroupBy.idxmax()
  - [ ] GroupBy.var()
  - [ ] GroupBy.std()
  - [ ] GroupBy.sem()
  - [ ] DataFrameGroupBy.quantile()
  - [ ] Resampler.mean()
  - [ ] Resampler.median()
  - [ ] Resampler.sem()
  - [ ] Resampler.std()
  - [ ] Resampler.var()
  - [ ] DataFrame.rolling() operations
  - [ ] DataFrame.expanding() operations
  - [ ] DataFrame.ewm() operations
- [ ] Deprecated the keyword line_terminator in DataFrame.to_csv() and Series.to_csv()
- [ ] Deprecated DataFrame.iteritems(), Series.iteritems(), HDFStore.iteritems()
- [ ] Deprecated Series.is_monotonic() and Index.is_monotonic()
- [ ] Deprecated the __array_wrap__ method of DataFrame and Series
- [ ] Deprecated the warn parameter in infer_freq()
- [ ] Deprecated allowing non-keyword arguments in ExtensionArray.argsort()
- [ ] Deprecated Timedelta.freq and Timedelta.is_populated
- [ ] Deprecated Timedelta.delta
- [ ] Deprecated passing arguments as positional in DataFrame.any() and Series.any()
- [ ] Deprecated passing positional arguments to DataFrame.pivot() and pivot() except data
- [ ] Deprecated the methods DataFrame.mad(), Series.mad(), and the corresponding groupby methods 
- [ ] Deprecated positional arguments to Index.join() except for other
- [ ] Deprecated positional arguments to StringMethods.rsplit() and StringMethods.split() except for pat
- [ ] Deprecated the display.column_space global configuration option
- [ ] Deprecated the argument na_sentinel in factorize(), Index.factorize(), and ExtensionArray.factorize()
- [ ] Deprecated argument errors for Series.mask(), Series.where(), DataFrame.mask(), and DataFrame.where()
- [ ] Deprecated arguments *args and **kwargs in Rolling, Expanding, and ExponentialMovingWindow ops. 
- [ ] Deprecated the inplace keyword in Categorical.set_ordered(), Categorical.as_ordered(), and Categorical.as_unordered()
- [ ] Deprecated setting a categorical’s categories with cat.categories = ['a', 'b', 'c']
- [ ] Deprecated unused arguments encoding and verbose in Series.to_excel() and DataFrame.to_excel() 
- [ ] Deprecated the inplace keyword in DataFrame.set_axis() and Series.set_axis()
- [ ] Deprecated the sort_columns argument in DataFrame.plot() and Series.plot()
- [ ] Deprecated positional arguments for all but the first argument of DataFrame.to_stata() and read_stata()
- [ ] Deprecated the mangle_dupe_cols argument in read_csv(), read_fwf(), read_table() and read_excel(). 
- [ ] Deprecated allowing dtype='datetime64' or dtype=np.datetime64 in Series.astype()

**Comment by bashtage** [comment]
> Deprecated allowing dtype='datetime64' or dtype=np.datetime64 in Series.astype()

Is it possible to actually do this?  I don't see how it could be done give the type is `S1 | _str | type[Scalar]` so "datetime64" would match "str", which is needed for many NumPy types (e.g., "i4", "f8").

**Comment by Dr-Irv** [comment]
> > Deprecated allowing dtype='datetime64' or dtype=np.datetime64 in Series.astype()
> 
> Is it possible to actually do this? I don't see how it could be done give the type is `S1 | _str | type[Scalar]` so "datetime64" would match "str", which is needed for many NumPy types (e.g., "i4", "f8").

I think the type for `astype()` is too wide.  Right now, you could do `pd.Series([1,2,3]).astype("foobar")`, and that would be accepted from a typing standpoint.  We should work on narrowing it to the set of valid strings (might be quite large), and then we could get this deprecation done.

I'm fine to hold off on this one.  The list I created was just copied from the whatsnew note.

**Comment by Dr-Irv** [comment]
We've checked off all the issues except `astype()`, so created #372 for that, so closing this.

Thanks to @bashtage for all his work on this!
