### ISSUE TITLE
CI failing on Windows.

### ISSUE THREAD

**Issue by bashtage** [pandas-dev/pandas-stubs#240]
**Describe the bug**
loguru is breaking windows

**To Reproduce**
Run CI on windows

Should use standard logging for now since it is a minimal dependency.

**Comment by Dr-Irv** [comment]
I have a hunch that poetry upgrading is the cause of this issue, so I am trying to pin poetry to a working version.  Based on issues reported in github, it seems there are issues with poetry 1.2.0 all over the place.

**Comment by Dr-Irv** [comment]
I pinned the poetry version and it passed, so trying merging your current versions with latest main and see if it makes CI work @bashtage

**Comment by Dr-Irv** [comment]
Thought that the change to poetry version would work, but still failing.

**Comment by Dr-Irv** [comment]
It's not `loguru`.  Wrote a test to just run a simple `pandas` python script, and that is not importing pandas

**Comment by bashtage** [comment]
Could try windows-2019 as host.

**Comment by Dr-Irv** [comment]
I've simplified it to having something to do with where poetry installs packages .  I have a simple workflow now where if I use `pip` to install `pandas` (and `pandas` is the only dependency), and run a testing program that just does a little pandas script, it works.  If I have poetry install pandas, it fails.

**Comment by twoertwein** [comment]
On mac/linux we have a cached poetry.lock but on windows we do not have a cache hit! Maybe mac/linux would also fail if they have a cache miss?

**Comment by Dr-Irv** [comment]
It's still fails if I comment out all the stuff that looks for the cached `poetry.lock`

**Comment by twoertwein** [comment]
> It's still fails if I comment out all the stuff that looks for the cached `poetry.lock`

Yeah, just tested it here https://github.com/pandas-dev/pandas-stubs/runs/8125630234?check_suite_focus=true :(

The weird thing is that poetry's verbose output claims it installs loguru!

**Comment by Dr-Irv** [comment]
Take a look at this one https://github.com/Dr-Irv/pandas-stubs/runs/8125585160?check_suite_focus=true

I made the script print out the path to python, called a simple thing to import pandas, and it is not using the python in the poetry virtual environment.

**Comment by Dr-Irv** [comment]
So it seems if you refer to `sys.executable` from python, it doesn't pick up the right python, but if I do `python testing.py` in the workflow, it works.  So maybe I do have the paths right with what I am trying (using a github action to install poetry)

**Comment by twoertwein** [comment]
> So it seems if you refer to `sys.executable` from python, it doesn't pick up the right python, but if I do `python testing.py` in the workflow, it works. So maybe I do have the paths right with what I am trying (using a github action to install poetry)

Does that mean it is likely that something about github's windows machines changed? There is no new version of cpython, no new version of loguru, not related to caching, and it also fails with older versions of poetry.

**Comment by twoertwein** [comment]
There wasn't a recent release of setup-python tools either.

In the meantime, I would feel comfortable merging PRs if the linux/mac tests succeed.

**Comment by Dr-Irv** [comment]
Well, it worked if I had changed `loguru` to using the standard `logger`, so it seems that `poetry` is running using the default python, not the python from the virtual env created by poetry.  Trying some other ideas

**Comment by Dr-Irv** [comment]
> Why not just disable windows until we think it is working normally? Are there any important scenarios where a windows CI would fail while Linux/OSX would not?

I've seen it happen for legitimate reasons, possibly due to I/O, but I can't remember.
