### ISSUE TITLE
Selecting from a DataFrame with MultiIndex columns assumed to return a Series, rather than a DataFrame. 

### ISSUE THREAD

**Issue by MichaelHarrison-CE** [pandas-dev/pandas-stubs#257]
**Describe the bug**
Running mypy on the code snippet below gives the following error due to the `df_inner` definition:

> error: Incompatible types in assignment (expression has type "Series[Any]", variable has type "DataFrame"

However, `df_inner` _is_ a DataFrame since the columns of `df_data` are a MultiIndex and we're just selecting from the outer level.

**To Reproduce**
```python
import pandas as pd

df_data = pd.DataFrame({('outer', 'col1'): ['a', 'b', 'b', 'c', 'c', 'c'], 
                        ('outer', 'col2'): [1, 2, 2, 3, 3, 3],
                        })

df_inner: pd.DataFrame = df_data['outer']
print(df_inner.shape)
```
Using mypy, I get the error mentioned above.

**Please complete the following information:**
 - OS: Windows 10
 - OS Version: 10.0.19044
 - python version: 3.8.10
 - version of type checker: mypy 0.971
 - version of installed `pandas-stubs`: 1.4.3.220829

**Additional context**
For info, my python environment is:

<details>
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
</head>

<div style='display:inline-block'>

<body link="#0563C1" vlink="#954F72">

Package | Version
-- | --
mypy | 0.971
mypy-extensions | 0.4.3
nodeenv | 1.7.0
numpy | 1.23.2
pandas | 1.5.0rc0
pandas-stubs | 1.4.3.220829
pip | 22.2.2
pyright | 1.1.269
python-dateutil | 2.8.2
pytz | 2022.2.1
setuptools | 63.4.3
six | 1.16.0
tomli | 2.0.1
types-pytz | 2022.2.1.0
typing_extensions | 4.3.0
wheel | 0.37.1

</body>

</html>

</details>

And the  output from `pd.show_versions()` is:

<details>

INSTALLED VERSIONS
------------------
commit           : 224458ee25d92ccdf289d1ae2741d178df4f323e
python           : 3.8.10.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.1252

pandas           : 1.5.0rc0
numpy            : 1.23.2
pytz             : 2022.2.1
dateutil         : 2.8.2
setuptools       : 63.4.3
pip              : 22.2.2
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
tzdata           : None

</details>

This  issue is a cross-post of https://github.com/pandas-dev/pandas/issues/48366

**Comment by Dr-Irv** [comment]
From a static typing perspective, we can't support all the ways of doing `df['some_string']`.  There is no way to know if the underlying `DataFrame` has columns supported by a `MultiIndex` or a regular `Index`.  If we widen the return type to be `DataFrame | Series`, then the most common use case of  `df['single_column']` that returns a `Series` would require users to cast their results.

You'll just have to cast your result here, because this particular usage can't be supported with static typing.
