### ISSUE TITLE
CLEAN:  Resolve Axis and AxisType

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas-stubs#284]
In `_typing.pyi`, we have:
```python
Axis = Union[str, int]
SeriesAxisType = Literal["index", 0]  # Restricted subset of _AxisType for series
AxisType = Literal["columns", "index", 0, 1]
```
There are 23 places (assuming I did `grep` correctly) where we use `Axis`, but can probably change this to `AxisType` in many (if not all) of them.

**Comment by ramvikrams** [comment]
Now I think there is only a single place where `Axis` is used which is this `Axis: TypeAlias = str | int`

**Comment by Dr-Irv** [comment]
> Now I think there is only a single place where `Axis` is used which is this `Axis: TypeAlias = str | int`

The issue is that within the stubs themselves we have many places where we use `Axis`, so that is the reconciliation that needs to be done, especially with the introduction of `AxisInt`

**Comment by ramvikrams** [comment]
> > Now I think there is only a single place where `Axis` is used which is this `Axis: TypeAlias = str | int`
> 
> The issue is that within the stubs themselves we have many places where we use `Axis`, so that is the reconciliation that needs to be done, especially with the introduction of `AxisInt`

yeah i'll do it

**Comment by ramvikrams** [comment]
Actually i am not able to understand what is to be done with `Axis` in stubs because there are not many places where we can resolve Axis as it is declared it is mostly in inside funcs, but what is to be done I am not able to understand

**Comment by Dr-Irv** [comment]
> Actually i am not able to understand what is to be done with `Axis` in stubs because there are not many places where we can resolve Axis as it is declared it is mostly in inside funcs, but what is to be done I am not able to understand

In `_typing.pyi`, we have the following:
```python
AxisInt: TypeAlias = Literal[0, 1]
Axis: TypeAlias = AxisInt | Literal["index", "columns", "rows"]
SeriesAxisType: TypeAlias = Literal[
    "index", 0
]  # Restricted subset of _AxisType for series
AxisTypeIndex: TypeAlias = Literal["index", 0]
AxisTypeColumn: TypeAlias = Literal["columns", 1]
AxisType: TypeAlias = AxisTypeIndex | AxisTypeColumn
```
In the pandas source, we use `Axis` as an argument type, while in `pandas-stubs`, we use `AxisType`.  We should decide to go one way or the other, maybe by changing pandas.

Based on a discussion in https://github.com/pandas-dev/pandas/pull/48612 ,  I'd like @twoertwein to comment on which way he thinks we should go within `pandas-stubs`.

**Comment by twoertwein** [comment]
I like the idea of separating Series-only/DataFrame axis values! Making that change in pandas will probably take some effort (especially for the integer indexing).

I'm slightly shocked how many Axus-related types we have, can we simplify it a bit. Maybe:

```py
AxisInt: TypeAlias = Literal[0, 1]  # might not even be needed for the public API, typically used in private functions
AxisIndex: TypeAlias = Literal["index", 0]
AxisColumn: TypeAlias = Literal["columns", 1]
Axis: TypeAlias = AxisTypeIndex | AxisTypeColumn
```

**Comment by Dr-Irv** [comment]
> I like the idea of separating Series-only/DataFrame axis values! Making that change in pandas will probably take some effort (especially for the integer indexing).
> 
> I'm slightly shocked how many Axis-related types we have, can we simplify it a bit. Maybe:
> 
> ```python
> AxisInt: TypeAlias = Literal[0, 1]  # might not even be needed for the public API, typically used in private functions
> AxisIndex: TypeAlias = Literal["index", 0]
> AxisColumn: TypeAlias = Literal["columns", 1]
> Axis: TypeAlias = AxisTypeIndex | AxisTypeColumn
> ```

What about including "row" in `AxisIndex` ?

**Comment by twoertwein** [comment]
> What about including "rows" in `AxisIndex` ?

the pandas PR added it only because it is technically possible and to avoid a mypy error (but I think it is not very well documented/used). I'd be fine adding/excluding it.

**Comment by Dr-Irv** [comment]
@ramvikrams 
So the goal would be to use these:
```python
AxisInt: TypeAlias = Literal[0, 1]  # might not even be needed for the public API, typically used in private functions
AxisIndex: TypeAlias = Literal["index", 0]
AxisColumn: TypeAlias = Literal["columns", 1]
Axis: TypeAlias = AxisTypeIndex | AxisTypeColumn
```
and remove `AxisType`, `SeriesAxisType` and `AxisType` (changing where we have `AxisType` to the "new" `Axis`)

We can remove `AxisInt` - it is only used in `algorithms.take()`, and just use a `Literal[0, 1]` there.

So that would mean we would only see `AxisIndex`, `AxisColumn` and `Axis` throughout the stubs.

**Comment by ramvikrams** [comment]
> @ramvikrams So the goal would be to use these:
> 
> ```python
> AxisInt: TypeAlias = Literal[0, 1]  # might not even be needed for the public API, typically used in private functions
> AxisIndex: TypeAlias = Literal["index", 0]
> AxisColumn: TypeAlias = Literal["columns", 1]
> Axis: TypeAlias = AxisTypeIndex | AxisTypeColumn
> ```
> 
> and remove `AxisType`, `SeriesAxisType` and `AxisType` (changing where we have `AxisType` to the "new" `Axis`)
> 
> We can remove `AxisInt` - it is only used in `algorithms.take()`, and just use a `Literal[0, 1]` there.
> 
> So that would mean we would only see `AxisIndex`, `AxisColumn` and `Axis` throughout the stubs.



thanks, i'll get started now

**Comment by ramvikrams** [comment]
We don't have `AxisInt` but we have `Axis: TypeAlias = str | int` so should we remove this `Axis` to move forward with the orignal plan

**Comment by Dr-Irv** [comment]
> We don't have `AxisInt` but we have `Axis: TypeAlias = str | int` so should we remove this `Axis` to move forward with the orignal plan

Yes, the goal is to use what is now `AxisType` and make that `Axis`
