### ISSUE TITLE
Mypy complains when setting plotting backend

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas-stubs#294]
**Describe the bug**

Can not set the plotting backend

**To Reproduce**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.
2. Indicate which type checker you are using (`mypy` or  `pyright`).
3. Show the error message received from that type checker while checking your example.

```
pd.options.plotting.backend = "plotly"
```

errors with 

```
test.py:6: error: Item "str" of "Union[str, bool, int, DictWrapper, None]" has no attribute "backend"  [union-attr]
test.py:6: error: Item "bool" of "Union[str, bool, int, DictWrapper, None]" has no attribute "backend"  [union-attr]
test.py:6: error: Item "int" of "Union[str, bool, int, DictWrapper, None]" has no attribute "backend"  [union-attr]
test.py:6: error: Item "None" of "Union[str, bool, int, DictWrapper, None]" has no attribute "backend"  [union-attr]
```

after the latest release

According to the user guide this should work: https://pandas.pydata.org/docs/user_guide/options.html#overview

**Please complete the following information:**
 - OS: [e.g. Windows, Linux, MacOS] MacOS
 - OS Version [e.g. 22] 12.5.1
 - python version 3.10
 - version of type checker mypy 0.960
 - version of installed `pandas-stubs` [v1.4.4.220906]

**Additional context**

**Comment by Dr-Irv** [comment]
@bashtage can you take a look at this?

**Comment by bashtage** [comment]
I think will probably need to roll back to be much less specific.  The issue is that the settings dict is magic object that can have any value as an attribute, although one a specific set of values can be set on these.
