### ISSUE TITLE
Positional-only parameters are only supported in Python 3.8 and greater

### ISSUE THREAD

**Issue by ribeaud** [pandas-dev/pandas-stubs#296]
**Describe the bug**
I have a project running `mypy` on **panda-stubs**.

**To Reproduce**
See https://gitlab.com/biomedit/sett/-/jobs/3016695046:
```bash
$ mypy
/usr/local/lib/python3.10/site-packages/pandas-stubs/_config/config.pyi:28: error: Positional-only parameters are only supported in Python 3.8 and greater
Found 1 error in 1 file (errors prevented further checking)
```

**Please complete the following information:**
 - OS: macOS
 - OS Version:  12.6
 - python version: 3.10.7
 - version of type checker: **mypy** _v0.971_
 - version of installed `pandas-stubs`: 1.4.4.220912

**Comment by bashtage** [comment]
I think Python 3.7 is no longer a target of pandas.

**Comment by bashtage** [comment]
I think Python 3.7 is no longer a target of pandas.

**Comment by ribeaud** [comment]
I am using _3.10.7_

**Comment by bashtage** [comment]
I'm suggesting that if you want typing you need to migrate to a Python released in the past 4 years.

**Comment by ribeaud** [comment]
Sorry, I do not get it. As specified in the report, I am using **Python** _v3.10.7_, so a **py310** release.

**Comment by bashtage** [comment]
Ahh, sorry.  Why are you reporting this bug?

**Comment by ribeaud** [comment]
**mypy** is triggering an error and makes my build fail. This is pretty new and probably related to a newer release of **mypy**.

So, either this is a bug in **mypy** (up to my experience, this is pretty rar) or there is some issue at line 28 of file `config.pyi`. No?

**Comment by Dr-Irv** [comment]
@ribeaud You'd have to be able to replicate this with a simple example.  We tested the stubs with python 3.10, and do not get that error message.  It could be something to do with the `mypy` settings in your CI, or some other strange interaction with your CI environment and our stubs.

While the message is saying that positional parameters are only supported in python 3.8 or greater, and you are using python 3.10 based on the location of the installation of the stubs, there is something else going on in your environment.

**Comment by ribeaud** [comment]
OK, thank you for testing and sorry for disturbance. I will check my environment...

**Comment by twoertwein** [comment]
Do you have something like `python_version = "3.7"` in your mypy config file?

**Comment by ribeaud** [comment]
Seems to be a _v3.10.7_ specific problem:
- https://github.com/python/mypy/issues/13627
- https://github.com/python/mypy/issues/13635
- https://github.com/python/mypy/issues/13499
- https://github.com/python/mypy/issues/13639

**Comment by bashtage** [comment]
Thanks for checking and followign up.
