### ISSUE TITLE
Type is not infered when iterating over `df.columns`

### ISSUE THREAD

**Issue by alkatar21** [pandas-dev/pandas-stubs#30]
I don't know if currently only `pyright: basic` support is targeted? If not it would be nice if this could be infered, since as far as I know it should always be `str`.

```py
# pyright: strict
import pandas as pd

df = pd.DataFrame()

for name in df.columns:  # Type of "name" is unknown Pylance(reportUnknownVariableType)
    print(name)
```

**Comment by Dr-Irv** [comment]
The type of `df.columns` is `Index`.  An Index can contain any hashable type, not just strings.  For example, here is where column names could be integers and strings.  Also, column "names" could be a `MultiIndex`.

```python
>>> import pandas as pd
>>> df=pd.DataFrame({1: [10,20], "abc": [5, 6]})
>>> df
    1  abc
0  10    5
1  20    6
>>> df.columns
Index([1, 'abc'], dtype='object')
```
From a static typing perspective, there is no way to know the type inside of an `Index`.  It is known at runtime via `Index.dtype`.

**Comment by twoertwein** [comment]
Could silence this pyright error by changing this line
https://github.com/pandas-dev/pandas-stubs/blob/f2b783c99685cbb3d7decbf357541b6d0053a5be/pandas-stubs/core/indexes/base.pyi#L209

to `def __iter__(self) -> Iterator[Hashable]: ...` but hashable might not be very helpful.

**Comment by Dr-Irv** [comment]
Good idea @twoertwein .  I did this in #35
