### ISSUE TITLE
Error: Incompatible types in assignment  (expression has type `Type[Int64Dtype]`, variable has type `Type[ExtensionDtype]`)

### ISSUE THREAD

**Issue by randolf-scholz** [pandas-dev/pandas-stubs#315]
```python
import pandas as pd
from pandas.api.extensions import ExtensionDtype

assert issubclass(pd.Int64Dtype, ExtensionDtype)  # ✔
x: type[ExtensionDtype] = pd.Int64Dtype           # ✘ error: type[assignment]
```

**Please complete the following information:**
- python 3.10.6
- pandas                        1.5.0
- pandas-stubs                  1.4.4.220919

**Comment by Dr-Irv** [comment]
Need to fix declarations of the various types in `pandas-stubs/core/arrays/integer.pyi` to make them subclasses of `IntegerDtype`

Probably have to look at the other extension dtypes as well.

PR welcome!
