### ISSUE TITLE
pd.isna / pd.isnull raising mypy error for None

### ISSUE THREAD

**Issue by marcglobality** [pandas-dev/pandas-stubs#318]
**Describe the bug**
pd.isna / pd.isnull raising mypy error for None

**To Reproduce**

file.py
```
import pandas as pd
pd.isnull(None)
```

```
~  pdnull ❯ mypy file.py                                                                       9s 15:54:43
file.py:2: error: No overload variant matches argument type "None"
file.py:2: note: Possible overload variants:
file.py:2: note:     def isna(obj: DataFrame) -> DataFrame
file.py:2: note:     def isna(obj: Series[Any]) -> Series[bool]
file.py:2: note:     def isna(obj: Union[Index, List[Any], ExtensionArray, ndarray[Any, Any]]) -> ndarray[Any, dtype[bool_]]
file.py:2: note:     def isna(obj: Union[str, bytes, date, datetime, timedelta, bool, complex, Timestamp, Timedelta]) -> bool
file.py:2: note:     def isna(obj: Union[NaTType, NAType]) -> Literal[True]
Found 1 error in 1 file (checked 1 source file)
```

**Please complete the following information:**
 - MacOS
 - mypy-0.971
 - pandas: 1.5.0
 - python: 3.9
 - pandas-stubs-1.4.4.220919

Expected behaviour: No issue since `pd.isnull(None) == True` and works fine

**Comment by gandhis1** [comment]
The way I see it, people often use methods like `pd.isnull` on any arbitrary object because it works for most null equivalent values.

But the documentation does not actually say it can be used on any type. If we follow the documentation I think a lot of people will get type errors on perfectly legit code.

**Comment by bashtage** [comment]
> But the documentation does not actually say it can be used on any type. If we follow the documentation I think a lot of people will get type errors on perfectly legit code.

The deep question is whether it is legit code?  Are there examples of usage like this in the docs, even if not in the func docs?

**Comment by marcglobality** [comment]
> The way I see it, people often use methods like `pd.isnull` on any arbitrary object because it works for most null equivalent values.
> 
> But the documentation does not actually say it can be used on any type. If we follow the documentation I think a lot of people will get type errors on perfectly legit code.

that was exactly my use case. I have an object that can be None, np.nan or a string, and I'm using pd.isnull to find about the first two cases

**Comment by twoertwein** [comment]
The inline annotations of `isna` cover any `object` (in the fallback overload) but `None` is not special-cased in the first overload to return `bool`:
https://github.com/pandas-dev/pandas/blob/ce143a2fb0a41e78c85d5311d0e159552d651b00/pandas/core/dtypes/missing.py#L81

While we cannot enumerate all possible inputs for isna (would probably create overlapping overloads), I'm +1 on adding `None`.

**Comment by bashtage** [comment]
What about `np.nan` as well (special case True)?

**Comment by twoertwein** [comment]
`np.nan` and `float("NaN")` are covered by float/Scalar. I don't think there is currently a way to use `Literal` with `np.nan` (or `float("NaN")`).

**Comment by marcglobality** [comment]
> The inline annotations of `isna` cover any `object` (in the fallback overload) but `None` is not special-cased in the first overload to return `bool`: https://github.com/pandas-dev/pandas/blob/ce143a2fb0a41e78c85d5311d0e159552d651b00/pandas/core/dtypes/missing.py#L81
> 
> While we cannot enumerate all possible inputs for isna (would probably create overlapping overloads), I'm +1 on adding `None`.

does this mean a (potential) PR would be needed in pandas, not here?

**Comment by Dr-Irv** [comment]
> does this mean a (potential) PR would be needed in pandas, not here?

Possibly both.  The inline types in the pandas code are used to do type-checking within the pandas code.  If you introduce `None` there, then you may have to deal with issues within the pandas code with respect to making this kind of change work there.

The type stubs in `pandas-stubs` are used to allow users to type-check their code, and that's the bug you reported.

I think if you just change https://github.com/pandas-dev/pandas-stubs/blob/193095a6ac7300c3f488e6fcebaf7f19cebe1a86/pandas-stubs/core/dtypes/missing.pyi#L33 to include `None` as an argument, that would be sufficient.   Do something similar for `notna()` as well.

Also, please add tests for this.  Thanks!
