### ISSUE TITLE
Typing pandas Series

### ISSUE THREAD

**Issue by erencank** [pandas-dev/pandas-stubs#319]
```python
def testfunc(self) -> pd.Series[float]:
        return pd.Series([1.3, 2.5])
test_series = self.testfunc()
```

**To Reproduce**
1. Run mypy and get no complaints
2. Run code and get a TypeError
![image](https://user-images.githubusercontent.com/95034460/191294506-1a3a0d5b-3664-420b-805f-c3eed6c935dd.png)
3. Same thing also happens when typing input variables

**Please complete the following information:**
 - OS: Linux Mint
 - OS Version 20.3
 - Python 3.10
 - pandas-stubs 1.4.4.220919

**Additional context**
How do you go about typing series?

**Comment by bashtage** [comment]
Need to use quotes for now since actual Series  doesn't support arguments.

**Comment by Dr-Irv** [comment]
```python
def testfunc(self) -> "pd.Series[float]":
        return pd.Series([1.3, 2.5])
```

See discussion at https://github.com/pandas-dev/pandas-stubs/blob/main/docs/philosophy.md
