### ISSUE TITLE
Why the new location?

### ISSUE THREAD

**Issue by gramster** [pandas-dev/pandas-stubs#34]
I'm a bit surprised that you would rename the top-level directory of the stub files to something other than pandas. Surely it should reflect the package/main module name? 

(This change also broke our github actions to pull stubs from here, but that's our problem. In investigating the break I noticed this change and it seems wrong to me to use this name. Want to raise this ASAP in case it results in further changes).

**Comment by BrenoJesusFernandes** [comment]
Hi I guess I am responsible for this chance. To simplify the project I added "poetry" to manage and distribuite the project easily. So, poetry build a wheel to a "stubs only package" if the stubs dir follows the pattern "package-stubs", following strictly the PEP 561.

**Comment by gramster** [comment]
Ah, got it. For various reasons I sometimes hack importlib to get it to import .pyi files rather than .py files, so my concern is that would break for me with this name change.

**Comment by Dr-Irv** [comment]
@gramster I'm going to close this - assuming conversation resolved the issue, but if not, feel free to re-open
