### ISSUE TITLE
Generic type for Indexes

### ISSUE THREAD

**Issue by jonyscathe** [pandas-dev/pandas-stubs#340]
Hi,

We have just moved over to pandas-stubs from data-science-types.
Overall it is vastly superior so I am enjoying being able to remove countless type-ignores that we needed due to the incompleteness of the data-science-types stubs.

However, one thing that is not ideal is that we did have a lot of Indexes with types specified, i.e., `Index[int]` as data-science-types have their Index class as Generic: `class Index(Generic[_T]):`
Now with pandas-stubs we are having to remove those index types which isn't the end of the world, but they are nice to have.
If it isn't too hard to get that working, I would definitely appreciate having generic types for Indexes

**Comment by Dr-Irv** [comment]
This did exist in the Microsoft predecessor of these stubs about 10 months ago, but we had to remove it because of various `mypy` failures.  

Certainly open to adding it back in and having someone do a PR for that!

**Comment by gandhis1** [comment]
IMO this is arguably one of the most important features that could be added to this module...as I continue to annotate my own code bases and discover gaps in the stubs, one of the recurring themes is the the propagation of `Any` types where we do have the ability to know better - especially relating to `Series` and `Index` (and `DataFrame` as well, but that also suffers from the lack of types on individual columns, which is probably a substantially more complex problem to solve).

**Comment by twoertwein** [comment]
@jonyscathe #760 will need more time and work but it would address this issue, or?

**Comment by twoertwein** [comment]
I will create a follow-up PR for truediv

**Comment by Dr-Irv** [comment]
> I will create a follow-up PR for truediv

I was considering doing a release with the new generic index.  Should I wait for that PR?
