### ISSUE TITLE
Convert typing declarations to use TypeAlias

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas-stubs#345]
See discussion here:  https://github.com/pandas-dev/pandas-stubs/pull/341#issuecomment-1262928643

Should we change `_typing.pyi` to make all these types that we create be declared with `TypeAlias` (imported from `typing_extensions`) ?

@twoertwein - your opinion?

**Comment by AlexWaygood** [comment]
Fun fact: typeshed pretends that `typing_extensions` is part of the standard library, meaning that all type checkers also believe that `typing_extensions` is part of the standard library. This means that you should be able to use types from `typing_extensions` (and also `_typeshed`, which we treat similarly) without adding a dependency on `typing_extensions`.

**Comment by twoertwein** [comment]
> Should we change `_typing.pyi` to make all these types that we create be declared with `TypeAlias` (imported from `typing_extensions`) ?

I think flake8-pyi recommends that and checks for it (disable in our config for now). Definitely good to make it more explicit.

**Comment by twoertwein** [comment]
> This means that (since this is a stubs-only project, and will never be executed at runtime) you should be able to use types from `typing_extensions` (and also `_typeshed`, which we treat similarly) without adding a dependency on `typing_extensions` :)

Could also start using `_typeshed.Self` in the stubs (Y019) @Dr-Irv

**Comment by Dr-Irv** [comment]
> Could also start using `_typeshed.Self` in the stubs (Y019)

Or from `typing_extensions`, since `Self` is part of python 3.11

https://docs.python.org/3.11/library/typing.html#typing.Self

**Comment by AlexWaygood** [comment]
> > Could also start using `_typeshed.Self` in the stubs (Y019)
> 
> Or from `typing_extensions`, since `Self` is part of python 3.11
> 
> https://docs.python.org/3.11/library/typing.html#typing.Self

`typing_extensions.Self` is unfortunately not yet supported by mypy or pytype (pyright supports it, not sure about pyre). But `_typeshed.Self` is just a common-or-garden TypeVar with a special name (`Self = TypeVar("Self")`), so it works fine with all type checkers.
