### ISSUE TITLE
DataFrame/Series dt.tz_localize() and dt.tz_convert() should accept str | BaseTzInfo | None

### ISSUE THREAD

**Issue by gandhis1** [pandas-dev/pandas-stubs#362]
```
    import pandas as pd
    import pytz
    dtr = pd.Series(data=pd.date_range("1/1/2020", "2/1/2020"))
    dtr1 = dtr.dt.tz_localize("US/Eastern")
    dtr2 = dtr.dt.tz_localize(pytz.UTC)
    dtr3 = dtr.dt.tz_localize(pytz.timezone("US/Pacific"))
    dtr4 = dtr.dt.tz_localize("US/Eastern").dt.tz_convert("US/Eastern")
    dtr5 = dtr.dt.tz_localize("US/Eastern").dt.tz_convert(pytz.UTC)
    dtr6 = dtr.dt.tz_localize("US/Eastern").dt.tz_convert(pytz.timezone("US/Pacific"))
```

> tests/test_pandas.py:331: error: Argument 1 to "tz_localize" of "_DatetimeLikeNoTZMethods" has incompatible type "_UTCclass"; expected "Optional[str]"  [arg-type]
tests/test_pandas.py:332: error: Argument 1 to "tz_localize" of "_DatetimeLikeNoTZMethods" has incompatible type "Union[_UTCclass, StaticTzInfo, DstTzInfo]"; expected "Optional[str]"  [arg-type]
tests/test_pandas.py:334: error: Argument 1 to "tz_convert" of "_DatetimeLikeNoTZMethods" has incompatible type "_UTCclass"; expected "Optional[str]"  [arg-type]
tests/test_pandas.py:335: error: Argument 1 to "tz_convert" of "_DatetimeLikeNoTZMethods" has incompatible type "Union[_UTCclass, StaticTzInfo, DstTzInfo]"; expected "Optional[str]"  [arg-type]

**Comment by Dr-Irv** [comment]
Just have to change the argument type here:
https://github.com/pandas-dev/pandas-stubs/blob/b12acc17a6bd9f337789fa2a434b933124694e89/pandas-stubs/core/indexes/accessors.pyi#L206

and add appropriate tests.
