### ISSUE TITLE
Cannot assign a list (or presumably any sequence) to DataFrame.columns

### ISSUE THREAD

**Issue by gandhis1** [pandas-dev/pandas-stubs#364]
I am breaking this issue out of https://github.com/pandas-dev/pandas-stubs/issues/361 so this becomes more of a single-purpose issue.

```
    import pandas as pd
    df = pd.DataFrame(data=[range(10), ['a'] * 5 + ['b'] * 5]).T
    df.columns = ["value", "category"]
```
> error: Incompatible types in assignment (expression has type "List[str]", variable has type "Index") [assignment]

@Dr-Irv I see you have commented at length on the nuances behind this problem at: https://github.com/python/mypy/issues/3004
Did that ever get resolved? Even if it wasn't, still think it's worth having an issue open in this repo for tracking.

Having to ignore types like the test does is a bit unfortunate:

https://github.com/pandas-dev/pandas-stubs/blob/b12acc17a6bd9f337789fa2a434b933124694e89/tests/test_frame.py#L1440-L1454

**Comment by Dr-Irv** [comment]
> @Dr-Irv I see you have commented at length on the nuances behind this problem at: [python/mypy#3004](https://github.com/python/mypy/issues/3004)
> Did that ever get resolved? Even if it wasn't, still think it's worth having an issue open in this repo for tracking.

Doesn't seem to be.  We convinced the `pyright` author to have a setting for this, but nothing has happened with `mypy`.

**Comment by Dr-Irv** [comment]
@gandhis1 It seems that with `pyright`, the line `df.columns = ["c", "d"]` is failing as `list[str]` is not matching `list[HashableT]` .  We should see if we can fix this.  Not sure how to test it because of the mypy issue.

**Comment by Dr-Irv** [comment]
Seems to be a pyright issue.  https://github.com/microsoft/pyright/issues/4293

**Comment by gandhis1** [comment]
This one that I opened is sort of duplicative with #73 so closing it.
