### ISSUE TITLE
Fix  Series.astype() to return a Series[type] dependent on argument

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas-stubs#372]
Deprecations in 1.5 on `Series.astype()` revealed that we have to work on that method.

See https://github.com/pandas-dev/pandas-stubs/issues/227#issuecomment-1260164389

Ideally, things like `s.astype(int)` and `s.astype("int")` would both return `Series[int]` .  Have to deal with each of the possible types, as well as the possible strings.

**Comment by ramvikrams** [comment]
So we just have to change the return type to `Series[S1]`

**Comment by Dr-Irv** [comment]
> So we just have to change the return type to `Series[S1]`

No, it's more nuanced than that, because you can pass strings to `astype()` that correspond to dtypes, and there are dtype arguments that are not in the `S1` typevar.  So you need a lot of overloads to appropriately do the mappings.  Have to handle a variety of numpy types as well.

I'd suggest making a table of values of `S1` in one column, and then in the second column, you list all the possible arguments for `astype()` that could generate that value of `S1`.  Then, from that table, you build a set of overloads.

There might be cases where there is no possible value for the `astype()` argument that give a particular value in `S1`.  We'll need to review them one by one.

**Comment by ramvikrams** [comment]
> > So we just have to change the return type to `Series[S1]`
> 
> No, it's more nuanced than that, because you can pass strings to `astype()` that correspond to dtypes, and there are dtype arguments that are not in the `S1` typevar. So you need a lot of overloads to appropriately do the mappings. Have to handle a variety of numpy types as well.
> 
> I'd suggest making a table of values of `S1` in one column, and then in the second column, you list all the possible arguments for `astype()` that could generate that value of `S1`. Then, from that table, you build a set of overloads.
> 
> There might be cases where there is no possible value for the `astype()` argument that give a particular value in `S1`. We'll need to review them one by one.



i'll get started with it now then
