### ISSUE TITLE
error: No overload variant of "DataFrame" matches argument types "Sequence[int]"  [call-overload]

### ISSUE THREAD

**Issue by randolf-scholz** [pandas-dev/pandas-stubs#384]
```python
import pandas as pd
from collections.abc import Sequence

index: Sequence[int] = [3, 2, 7]
columns = ["a", "b", "c"]
df = pd.DataFrame(index=index, columns=columns)  # ✘ error: [call-overload]
print(df)
```

If the annotation `Sequence[int]` is removed, the file parses.

**Please complete the following information:**
 - Ubuntu 22.04.1
 - Python 3.10.6
 - mypy 0.982
 - pandas 1.5.0
 - pandas-stubs 1.5.0.221012

**Comment by Dr-Irv** [comment]
The types for `index` and `columns` are `Axes`, which are defined as:
```python
AnyArrayLike: TypeAlias = Union[Index, Series, np.ndarray]
Axes: TypeAlias = Union[AnyArrayLike, list, dict, range]
```
We left out `Sequence` on purpose as an `Axes` argument, because a plain string is a `Sequence`.  If you change your code to use `List[int]` instead of `Sequence[int]`, it will work fine.

Because of this unfortunate aspect of python typing, we avoid using `Sequence` as the type of an argument when we the argument would accept allow a list of strings, but not accept a pure string.

**Comment by randolf-scholz** [comment]
Seems like this is another case where the absence of a [NOT type](https://github.com/python/typing/issues/801) bites.

Potentially one could discuss allowing at least `MutableSequence` to catch user types, as strings are immutable.

**Comment by bashtage** [comment]
Sounds like a good way forward for all of the places where we really want `Sequence[Scalar]` but can't because of `str`.

**Comment by gandhis1** [comment]
That would exclude things that should be included though, `tuple`, `FrozenSet`, etc.

**Comment by bashtage** [comment]
> That would exclude things that should be included though, `tuple`, `FrozenSet`, etc.

Mostly we are using `list[ScalarT]` as a work around though, so it seems like it is likely an improvement in many cases. There are also quite a few places where tuple are poorly handled (e.g., anything that indexes).

**Comment by randolf-scholz** [comment]
@gandhis1 using `tuple[int, int, int]` or `tuple[int, ...]` in my example currently also raises [call-overload] errors.

**Comment by Dr-Irv** [comment]
I think that if we add `tuple` to the definition of `Axes` in `_typing.pyi`, we should be OK, as `Axes` is only used as a type for the argument for the `Series` and `DataFrame` constructors, and for `reindex()`.  

We just can't support `Sequence`
