### ISSUE TITLE
CustomBusinessHour accepts a time as start and end

### ISSUE THREAD

**Issue by gandhis1** [pandas-dev/pandas-stubs#396]
This requires updating the docs in pandas as well, because it is not accurate:  https://pandas.pydata.org/docs/reference/api/pandas.tseries.offsets.CustomBusinessHour.html

```
import pandas as pd
from datetime import time
a = time(6, 0)
b = time(14, 0)

In: pd.tseries.offsets.CustomBusinessHour(start=a, end=b)
Out: <CustomBusinessHour: CBH=06:00-14:00>
```

Example error:

> error: Argument "start" to "CustomBusinessHour" has incompatible type "Optional[time]"; expected "str"
error: Argument "end" to "CustomBusinessHour" has incompatible type "Optional[time]"; expected "str"

**Comment by Dr-Irv** [comment]
@gandhis1 Thanks for reporting this.  Can you also create an issue in the pandas repo about the doc issue?  Same issue probably exists for `BusinessHour` as well.
