### ISSUE TITLE
Figure out how to package the stubs as a pandas-stubs project for distribution

### ISSUE THREAD

**Issue by simonjayhawkins** [pandas-dev/pandas-stubs#4]

**Comment by Dr-Irv** [comment]
See #22 that has a procedure for building a wheel and tests the wheel in CI.  It is merged in.  There is an issue with installing `pandas-stubs` and `pandas` side by side, where `pyright` is using the PYI files with `pandas` over the ones in `pandas-stubs`, when both exist.  See https://github.com/microsoft/pyright/issues/3540 .

**Comment by Dr-Irv** [comment]
Closing this as the pyright issue was resolved by removing `py.typed`.  After  #24, we have a procedure for building wheels.  That procedure likely to use poetry in the future based on work in  #23
