### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by nth10sd** [pandas-dev/pandas-stubs#400]
**Describe the bug**
https://github.com/pandas-dev/pandas-stubs/blob/581c1eb1d98916734f9378baa61d1446e227abd5/pyproject.toml#L34

Python 3.11 is not supported.

**To Reproduce**
Try installing in a `venv` from Python 3.11

**Additional context**
It seems pandas already has Python 3.11 support.

**Comment by Dr-Irv** [comment]
Our tests are failing because `pyarrow` is used in the testing, and `pyarrow` doesn't support 3.11 yet.

PR created:  #398
