### ISSUE TITLE
Various `Index` operators missing

### ISSUE THREAD

**Issue by adamchainz** [pandas-dev/pandas-stubs#405]
**Describe the bug**
I discovered that `Index.__rpow__` is missing when trying to lint my code.

**To Reproduce**

```py
import pandas

df = pandas.DataFrame({"nums": [1, 2]})
print(2**df.index)
```

Runs:

```
$ python example.py
0    2
1    4
Name: nums, dtype: int64
```

But Mypy not happy:

```
$ pre-commit run mypy --file example.py
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

example.py:4: error: No overload variant of "__pow__" of "int" matches argument type "Index"  [operator]
example.py:4: note: Possible overload variants:
example.py:4: note:     def __pow__(self, Literal[0]) -> Literal[1]
example.py:4: note:     def __pow__(self, Literal[0], None) -> Literal[1]
example.py:4: note:     def __pow__(self, Literal[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25], None = ...) -> int
example.py:4: note:     def __pow__(self, Literal[-1, -2, -3, -4, -5, -6, -7, -8, -9, -10, -11, -12, -13, -14, -15, -16, -17, -18, -19, -20], None = ...) -> float
example.py:4: note:     def __pow__(self, int, None = ...) -> Any
example.py:4: note:     def __pow__(self, int, Literal[0]) -> NoReturn
example.py:4: note:     def __pow__(self, int, int) -> int
Found 1 error in 1 file (checked 1 source file)
```

It seems that various dunder funcs on `Index` are missing.

**Please complete the following information:**
 - OS: macOS
 - OS Version 12
 - python version: 3.10
 - version of type checker: 0.982
 - version of installed `pandas-stubs`: 1.5.1.221024 

**Additional context**
n/a

**Comment by adamchainz** [comment]
In the implementation, the methods are inherited [from `OpsMixin`](https://github.com/pandas-dev/pandas/blob/main/pandas/core/arraylike.py#L33), through `IndexOpsMixin`.

But in the stubs, `IndexOpsMixin` does not inherit from `OpsMixin`. I guess this is because `OpsMixin` is hardcoded right now to only return `DataFrame`s.

**Comment by Dr-Irv** [comment]
Since we want to be more specific about what types are returned for these operators when applied to `Series`, `DataFrame` and `Index`, probably the best solution is to define all of the relevant methods for `Index` in typing, as is done for `Series`.   Some of them, e.g., `__add__()`, `__sub__()` are already defined in `core/indexes/base.pyi`, so we just need to add the missing ones.  

PR with tests welcome!

**Comment by adamchainz** [comment]
I think you could use [`Self`](https://docs.python.org/3.11/library/typing.html#typing.Self) in `OpsMixin`, if using such ops always returns the same type as the index/dataframe/series?

Like:

```python
def __pow__(self, other: Any) -> Self: ...
```

Or one could be specific about the `other` types that are supported:

```python
def __pow__(self, other: int | float | Decimal | ...) -> Self: ...
```

Not sure what types pandas allows here though - I don't really use it, I am just helping a project that uses it to roll out type hints.

WDYT?

**Comment by Dr-Irv** [comment]
> Not sure what types pandas allows here though - I don't really use it, I am just helping a project that uses it to roll out type hints.
> 
> WDYT?

In `Series`, we try to do some better type checking based on the type of the `Series`, e.g.:
```python
    @overload
    def __add__(self, other: TimestampSeries) -> TimestampSeries: ...
    @overload
    def __add__(self, other: DatetimeIndex) -> TimestampSeries: ...
    @overload
    def __add__(self, other: Timestamp) -> TimestampSeries: ...
    @overload
    def __add__(
        self, other: num | _str | Timedelta | _ListLike | Series[S1]
    ) -> Series: ...
```
So for `Index` (and things like `DatetimeIndex`), we also want to be more restrictive on the allowed types for the operators.

So I think the best way to go is to just copy the various operators over to `Index`, or create an internal hidden type equivalent to `OpsMixin` that would be used by `Index` and `DataFrame`, but not by `Series`

**Comment by ramvikrams** [comment]
Sir then pow,rmul,mul,rdiv etc. has to be added
