### ISSUE TITLE
Typing error with Series.rolling() when window is a str(time interval) such as "3D"

### ISSUE THREAD

**Issue by ramonbotella** [pandas-dev/pandas-stubs#407]
I'm having a mypy type-checking error when trying to commit code with the pandas.DataFrame.rolling() function. Particularly when the dataframe has a datetimelike index and I pass a frequency as a string in the form "2D" (for two days), for instance. I have tried to set the index as a column and pass on="column_name" to rolling and to use other time intervals ("3D" and "7D"), but the error is the same. Any insights? 
Thanx!

To Reproduce
Error type-checking on pandas.DataFrame.rolling()

import pandas as pd
s = pd.Series(range(5), index=pd.date_range("2023-01-01", periods=5, freq="1D"))
s.rolling(window="2D").sum()
Actual Behavior

error: No overload variant of "rolling" of "Series" matches argument type "str"
note: Possible overload variants:
note: def rolling(self, window: Union[int, BaseOffset, BaseIndexer], min_periods: int = ..., center: bool = ..., *, win_type: str, on: str = ..., axis: Union[Literal['index'], Literal[0]] = ..., closed: str = ..., step: int = ..., method: Union[Literal['single'], Literal['table']] = ...) -> Window[Series[Any]]
note: def rolling(self, window: Union[int, BaseOffset, BaseIndexer], min_periods: int = ..., center: bool = ..., *, win_type: None = ..., on: str = ..., axis: Union[Literal['index'], Literal[0]] = ..., closed: str = ..., step: int = ..., method: Union[Literal['single'], Literal['table']] = ...) -> Rolling[Series[Any]]

My Environment

Mypy version used: 0.971
Mypy command-line flags: error: No overload variant of "rolling" of "Series" matches argument type "str"
Mypy configuration options from mypy.ini (and other config files):
Python version used: 3.8.10
Pandas version used: 1.4.3
Pandas-stubs version used: 1.5.1.221024

**Comment by gandhis1** [comment]
I believe this was fixed. You are on an old pandas-stubs version, can you upgrade?

**Comment by ramonbotella** [comment]
I have updated Pandas-stubs to version 1.5.1.221024 but I'm getting the same error message

**Comment by bashtage** [comment]
Looks like it should be OK.

https://github.com/pandas-dev/pandas-stubs/blob/356ed096035358296afe705475543c9bfeea2846/pandas-stubs/core/series.pyi#L1588

**Comment by ramonbotella** [comment]
Wasn't able to solve the problem, even though the pandas-stubs/pandas-stubs/core/series.pyi file on y my environment looked exactly the same as the version linked by @bashtage. Deleting and re-installing the whole virtual environment was an option, but finally I found the following workaround to use a string window on rolling().
Thanks to you all!

```
from pandas.tseries.frequencies import to_offset
import pandas as pd

s = pd.Series(range(5), index=pd.date_range("2023-01-01", periods=5, freq="1D"))
s.rolling(to_offset("7D")).sum()
```

**Comment by Dr-Irv** [comment]
@ramonbotella It may be due to some `mypy` setting in your environment.  Also, try running `mypy` with the `--no-incremental` option to clear its cache.

Having said that, since you got it to work, I'm going to close this issue.
