### ISSUE TITLE
Typing says pd.DataFrame has nonexistent property to_list

### ISSUE THREAD

**Issue by anishathalye** [pandas-dev/pandas-stubs#414]
**Describe the bug**

Typing stubs indicate that `pd.DataFrame` has an attribute `to_list` when it does not.

**To Reproduce**

- Provide a minimal runnable `pandas` example that is not properly checked by the stubs.

```python
import pandas as pd

def f(x: pd.DataFrame) -> None:
    # reveal_type(x.to_list) # note: Revealed type is "pandas.core.series.Series[Any]"
    x.to_list  # just accessing the attribute

f(pd.DataFrame([1, 2, 3]))
```

- Indicate which type checker you are using (`mypy` or  `pyright`).

mypy

- Show the error message received from that type checker while checking your example.

The above passes the type checker but fails at runtime.

**Please complete the following information:**
 - OS: macOS
 - OS Version: 12.5.1
 - python version: 3.9.15
 - version of type checker: mypy 0.981
 - version of installed `pandas-stubs`: pandas-stubs==1.5.1.221024

**Comment by gandhis1** [comment]
You say it fails at runtime. Is that actually true? `to_list` is a method and I would expect the way you are accessing it to be perfectly fine (although it won't do anything of substance). The revealed type certainly isn't right.

**Comment by Dr-Irv** [comment]
This is expected behavior.

In order to support specifying a column name as an attribute, we translate any non-existent function to return a `Series`. 

For example, the following code works:
```python
df = pd.DataFrame({"to_list":[3,4,5]})
df.to_list
```
So the reason you get `pandas.core.series.Series[Any]`  as the revealed type is because it thinks that `to_list` is the name of a column.
