### ISSUE TITLE
is_numeric_dtype not considering Index as a valid type

### ISSUE THREAD

**Issue by williamjamir** [pandas-dev/pandas-stubs#415]
**Describe the bug**
As stated in the docs, the `is_numeric_dtype` function accepts Dtypes, Arrays, and Index as well.
https://pandas.pydata.org/docs/reference/api/pandas.api.types.is_numeric_dtype.html?highlight=example

However, the typings are only contemplating `_ArrayOrDtype` 
https://github.com/pandas-dev/pandas-stubs/blob/001c0afb3ef0dfe21e96ced87c9e455c657a50c3/pandas-stubs/core/dtypes/common.pyi#L50

**To Reproduce**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.
```python
from pandas.core.dtypes.common import is_numeric_dtype

is_numeric_dtype(pd.Index([1, 2.0]))


```
```
>>> mypy --version 
mypy 0.982 (compiled: yes)
```

Show the error message received from that type checker while checking your example.
(I put one type per line to make the output more readable)
```python
>>> mypy test.py     
/tmp/test.py:4: error: Argument 1 to "is_numeric_dtype" has incompatible type "Index"; 
expected 
"
Union[
    Union[ExtensionArray, ndarray[Any, Any]],
    Union[
        dtype[Any],
        None,
        Type[Any],
        _SupportsDType[dtype[Any]],
        str,
        Union[
            Tuple[Any, int],
            Tuple[Any, Union[SupportsIndex, Sequence[SupportsIndex]]],
            List[Any],
            _DTypeDict,
            Tuple[Any, Any],
        ],
    ],
    Series[Any],
    DataFrame,
]

"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

**Please complete the following information:**
OS: MacOS M1
OS Version Ventura 13.0
python version: 3.9.12
version of type checker: mypy 0.982 (compiled: yes)
version of installed pandas-stubs
pandas==1.5.1
pandas-stubs==1.5.1.221024

**Comment by Dr-Irv** [comment]
Need to expand definition of `_ArrayOrDtype` to include `pd.Index` at https://github.com/pandas-dev/pandas-stubs/blob/001c0afb3ef0dfe21e96ced87c9e455c657a50c3/pandas-stubs/core/dtypes/common.pyi#L31

Need to add more tests to `tests/test_api_types.py` to cover the various types that can be passed to `is_numeric_dtype` as well as the other functions defined in `pandas-stubs/core/dtypes/common.pyi` .

Maybe @bashtage can have a look, although this should be pretty straightforward to do.  Just have to add lots of tests.

**Comment by ramvikrams** [comment]
Sir can you please tell any one of the test for pd.Index, I am not able to write it

**Comment by Dr-Irv** [comment]
> ```
> 
> def test_is_numeric_dtype() -> None:
>     check(assert_type(api.is_numeric_dtype(pd.Index([1, 2.0])), bool), bool)
> ```
> 
> Sir can you please tell if this test is correct for pd.Index.

Yes, it appears to be so.  If you work on this, you should add a lot of tests for all the other functions there, as well as the other types that those functions accept.  Test locally before creating a PR.

**Comment by ramvikrams** [comment]
Yes sir

**Comment by ramvikrams** [comment]
Sir I ran on my local system it is working with no issues and as for `  as well as the othe types that those functions accept` are you talking about adding test for  pd.DataFrame, pd.Series

**Comment by Dr-Irv** [comment]
> Sir I ran on my local system it is working with no issues and as for ` as well as the othe types that those functions accept` are you talking about adding test for pd.DataFrame, pd.Series

Yes, and for the other functions that are in `pandas-stubs/pandas-stubs/core/dtypes/common.pyi`

What you should do is modify each of the single test functions that exist for each of the functions that are in there.  E.g., one for ` is_numeric_dtype`, one for `is_float_dtype` , etc.  Then within each function, you have a test for the 5 possible argument types:  `ArrayLike, npt.DTypeLike, pd.Series, pd.DataFrame, pd.Index` .  Only do this for the functions that accept `_ArrayOrDtype` as an argument type.

**Comment by ramvikrams** [comment]
> > Sir I ran on my local system it is working with no issues and as for ` as well as the othe types that those functions accept` are you talking about adding test for pd.DataFrame, pd.Series
> 
> Yes, and for the other functions that are in `pandas-stubs/pandas-stubs/core/dtypes/common.pyi`
> 
> What you should do is modify each of the single test functions that exist for each of the functions that are in there. E.g., one for ` is_numeric_dtype`, one for `is_float_dtype` , etc. Then within each function, you have a test for the 5 possible argument types: `ArrayLike, npt.DTypeLike, pd.Series, pd.DataFrame, pd.Index` . Only do this for the functions that accept `_ArrayOrDtype` as an argument type.

Thanks sir I'll do it

**Comment by ramvikrams** [comment]
Sir just a small question for `ArrayLike` should I use `pd.array` and for `npt.DtypeLike` should I use `np.array` for writing tests for them respectively

**Comment by Dr-Irv** [comment]
For `ArrayLike`, use `np.array` (already declared at top as `nparr`.  For `npt.DtypeLike`, use `np.dtype(np.int32) `  `npt.DtypeLike` is a numpy dtype, so let's pass in a `dtype` for that test.

**Comment by ramvikrams** [comment]
> 

Thanks Sir
