### ISSUE TITLE
Sample example does not work

### ISSUE THREAD

**Issue by ongietorri** [pandas-dev/pandas-stubs#416]
**Describe the bug**
I can't reproduce the results of example given in the documentation: https://github.com/pandas-dev/pandas-stubs#usage
When I install `pandas-stubs` and either run `mypy` or `pytype`, no typing error is reported.

**To Reproduce**

0. Install pandas-stubs along with mypy and pytype
1. cat the example in https://github.com/pandas-dev/pandas-stubs#usage to a python file `sandbox.py`
2. run `mypy` or `pytype` on the file

mypy result: Success: no issues found in 1 source file
pypype result: Success: no errors found

**Additional information:**
 - OS: Linux
 - python version: 3.8.11
 - version of type checker: mypy 0.790, pytype 2022.10.26
 - version of pandas: 1.1.5
 - version of installed `pandas-stubs`:  1.5.1.221024

**Comment by Dr-Irv** [comment]
Can you try with `mypy` version 0.971 ?  

We don't have tests for `pytype`, so won't be able to support that.

**Comment by twoertwein** [comment]
I get the expected error with a recent version of mypy/pyright

**Comment by Dr-Irv** [comment]
Seems to be a mypy version issue, so closing
