### ISSUE TITLE
Index.is_unique is considered as a function for mypy rather than a property

### ISSUE THREAD

**Issue by williamjamir** [pandas-dev/pandas-stubs#420]
**Describe the bug**

mypy considers that `is_unique` is a function rather than a property; and with the new mypy version there is a check now "truthy-function" which caught this usse.

**To Reproduce**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.
```python
import pandas as pd

index = pd.Index([1, 2, 3])

if index.is_unique:
    ...
```

2. Indicate which type checker you are using (`mypy` or  `pyright`).
```
>>> mypy --version
mypy 0.990 (compiled: yes)

>>> pip freeze | grep pan
pandas==1.5.1
pandas-stubs==1.5.1.221024

```
5. Show the error message received from that type checker while checking your example.
```
error: Function "Callable[[], bool]" could always be true in boolean context  [truthy-function]
```
Output of `reveal_type(index.is_unique)`
```
note: Revealed type is "def () -> builtins.bool"
```

**Please complete the following information:**
- OS: MacOS M1
- OS Version Ventura 13.0
- python version: 3.9.12
- version of type checker: mypy 0.990 (compiled: yes)
- version of installed pandas-stubs: pandas-stubs==1.5.1.221024

**Additional context**

**Comment by bashtage** [comment]
Is this true on master?  There was a PR accepted yesterday that added `@property` to many subclasses of Index.

**Comment by bashtage** [comment]
See https://github.com/pandas-dev/pandas-stubs/search?q=def+is_unique

**Comment by williamjamir** [comment]
Yeap, indeed!

 I checked with the main branch, and the error is fixed:
```
>>> pip freeze | grep pandas  
pandas==1.5.1
pandas-stubs @ git+ssh://git@github.com/pandas-dev/pandas-stubs.git@8333a142292f1c0bcc84602b9f4314539401b556
```

This explains why the Github search was showing the correct typing for the is_unique with`@property` before I posted this issue 😅 

Sorry for not trying the main branch first before opening this issue.

I appreciate the help; thank you for your time!
