### ISSUE TITLE
Series arithmetic methods accepting a Timedelta should also accept a np.timedelta64

### ISSUE THREAD

**Issue by gandhis1** [pandas-dev/pandas-stubs#423]
```
import numpy as np
import pandas as pd

s1 = pd.Series(data=pd.date_range("1/1/2020", "2/1/2020"))
s2 = pd.Series(data=pd.date_range("1/1/2021", "2/1/2021"))
s3 = (s1 - s2) / np.timedelta64(1, "M")  # pd.Series[float]
```
>`  error: No overload variant of "__truediv__" of "Series" matches argument type "timedelta64"  [operator]`

This applies to most arithmetic methods that accept a `Timedelta`

**Comment by Dr-Irv** [comment]
There's a couple of issues here.  One is that we do need to add `np.timedetla64` as accepted in different arithmetic methods for `Series`.  But we should also  add a `__truediv__()` method for `TimestampSeries`, as well as the other arithmetic operators that accept either a `pd.Timedelta` or `np.timedelta64`
