### ISSUE TITLE
pd.cut() should allow datetime-like bins when applied to a datetime-like series

### ISSUE THREAD

**Issue by gandhis1** [pandas-dev/pandas-stubs#424]
```
import numpy as np
import pandas as pd

s1 = pd.Series(data=pd.date_range("1/1/2020", "1/1/2021"))
s2 = pd.cut(s1, bins=[np.datetime64("3/1/2020"), np.datetime64("9/1/2020")])  # error
```

**Comment by Dr-Irv** [comment]
In `pandas-stubs\core\reshape\tile.pyi`, need to change the `bins` argument of `cut` wherever we say `Sequence[int] | Sequence[float]` to `List[Scalar]` .  I think that will fix this.  Can't use `Sequence[str]`, because that will match a single string.

**Comment by twoertwein** [comment]
Could maybe even do something like:

```py
def cut(
    x: Series[S1],
    bins: Sequence[S1],  # or with list[S1]
    ...
```

Not sure whether that is too strict.

**Comment by bashtage** [comment]
Definitely too strict.  There is no Series[np.datetime64], for example.
