### ISSUE TITLE
Annotations for categorical accessors

### ISSUE THREAD

**Issue by crusaderky** [pandas-dev/pandas-stubs#43]
mypy 0.961
pandas-stubs 1.4.2.220626
```python
s: pandas.Series
s.cat.codes
```
output:
```
 "ellipsis" has no attribute "codes"
```

**Comment by twoertwein** [comment]
In general Series `.cat` does not return anything:
```py
pd.Series([1]).cat
AttributeError: Can only use .cat accessor with a 'category' dtype
```
Could probably change this line
https://github.com/pandas-dev/pandas-stubs/blob/f3e5a496542eb3b8c9f4ee266006346864b2684a/pandas-stubs/core/series.pyi#L1163

to use overloads (I'm not familiar with the exact types):

- self: Series[category] -> CategoryType
- self: Series -> CategoryType | typing.NoReturn

Would need to return a union to have compatible overloads.
