### ISSUE TITLE
BUG: incorrect type hint for subset in dropna

### ISSUE THREAD

**Issue by StevenLi-DS** [pandas-dev/pandas-stubs#434]
**Describe the bug**

`dropna()` should accept any array like object.

![](https://user-images.githubusercontent.com/33796896/201767430-fad99feb-3495-4b5a-9788-e027769ad395.png)

**To Reproduce**
`pylance` in vscode
```python
import pandas as pd
data = {'col1': [1, 3, 4], 'col2': [2, 3, 5], 'col2': [2, 4, 4]}
df = pd.DataFrame(data)

df.dropna(subset=df.columns.drop('col1'))
```

**Please complete the following information:**
 - OS: [MacOS]
 - OS Version [e.g. 13]
 - python version 3.9.12
 - version of type checker ? 
 - version of installed `pandas-stubs` ?

**Additional context**
OP: https://github.com/pandas-dev/pandas/issues/49702

**Comment by Dr-Irv** [comment]
Have to change the `subset` argument for the 4 overloads in `core/frame.pyi` from `list | None` to `LikeLikeU |  Scalar | None` since you can pass `Index`, `Series`, `np.ndarray`, any `Sequence`, as well as individual scalars.

PR and tests welcome.

**Comment by shubhankarunhale** [comment]
Hi @Dr-Irv , I was hoping to get started with this as a first contribution, but I don't understand what you mean by "LikeLikeU" in the changes suggested by you

**Comment by Dr-Irv** [comment]
> Hi @Dr-Irv , I was hoping to get started with this as a first contribution, can I work on this? Also I don't understand what you meant by "LikeLikeU" in the suggested changes

Sorry that was a typo.  Meant `ListLikeU`.  Will fix in the comment above.
