### ISSUE TITLE
BUG: Series.clip should accept array-like for upper and lower

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas-stubs#437]
**Describe the bug**
Series.clip currently types upper and lower arguments as accepting Optional[float]. However they also accept array-like.

**To Reproduce**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.
2. Indicate which type checker you are using (`mypy` or  `pyright`).
3. Show the error message received from that type checker while checking your example.

```
ser = pd.Series([1, 2, 3])
ser.clip(upper=ser)
```

With mypy 0.991: `error: Argument "upper" to "clip" of "Series has incompatible type "Series[Any]"; expected "Optional[float]"`

**Comment by ramvikrams** [comment]
> Need to change `lower` and `upper` arguments here:
> 
> https://github.com/pandas-dev/pandas-stubs/blob/44f804c7f9600f4651041a3ac002e3700bfc0890/pandas-stubs/core/series.pyi#L1065
> 
> And add tests.

Sir if we chamge will we not have duplicate arguments in clip
