### ISSUE TITLE
groupby(...).transform is untyped

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas-stubs#438]
**Describe the bug**
`SeriesGroupBy.transform` and `DataFrameGroupBy.transform` are currently not typed:

https://github.com/pandas-dev/pandas-stubs/blob/001c0afb3ef0dfe21e96ced87c9e455c657a50c3/pandas-stubs/core/groupby/generic.pyi#L159

Running mypy with `--disallow-untyped-calls` reports an issue with any usage of this method.

**Comment by Dr-Irv** [comment]
Need to return `Series` for `SeriesGroupBy.transform` and `DataFrame` for `DataFrameGroupBy.transform`.

PR with tests welcome

**Comment by ramvikrams** [comment]
Do we not have to change the arguments of transform? will it work if we just add the return types

**Comment by rhshadrach** [comment]
> For now, you could just annotate `f` as `Callable`

I would do `str | Callable`; using a string alias is a very common use case (at least for me). Looks like the docs need updating in this regard.
