### ISSUE TITLE
DataFrameGroupBy attribute access for columns

### ISSUE THREAD

**Issue by rhshadrach** [pandas-dev/pandas-stubs#439]
**Describe the bug**
When accessing a column on a DataFrameGroupBy object via attribute-access (see below), mypy complains that no such attribute exists.

**To Reproduce**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.
2. Indicate which type checker you are using (`mypy` or  `pyright`).
3. Show the error message received from that type checker while checking your example.

```
df = pd.DataFrame({'a': [1, 1, 2], 'b': [3, 4, 5]})
gb = df.groupby('a').b
```

mypy 0.991 says: `"_DataFrameGroupByNonScalar" has no attribute "b"`

**Comment by Dr-Irv** [comment]
Need to do what we did in `core/frame.pyi` by adding `__getattr__()` to `DataFrameGroupBy`

**Comment by ramvikrams** [comment]
> Need to do what we did in `core/frame.pyi` by adding `__getattr__()` to `DataFrameGroupBy`

but `DataFrameGroupBy` is in `core/groupby/generic.pyi`

**Comment by Dr-Irv** [comment]
> > Need to do what we did in `core/frame.pyi` by adding `__getattr__()` to `DataFrameGroupBy`
> 
> but `DataFrameGroupBy` is in `core/groupby/generic.pyi`

Yes, so what's the issue.  The change that was made for `DataFrame.__getattr__()` should be the same for `DataFrameGroupBy.__getattr__()`

**Comment by ramvikrams** [comment]
> Yes, so what's the issue. 

I misunderstood, no issue thanks
