### ISSUE TITLE
FEATURE:  Start using `Never` as return types for disallowed operations

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas-stubs#441]
See #432 where methods were added to `TimestampSeries` and `TimedeltaSeries` that return `Never`, which `pyright` will pick up as invalid.

We could add more of these to disallow certain operations between incompatible types, and then use the `TYPE_CHECKING_INVALID_USAGE` pattern to check for these.

**Comment by twoertwein** [comment]
Or `NoReturn` https://github.com/PyCQA/flake8-pyi/issues/272

**Comment by Dr-Irv** [comment]
Turns out that we should not do this. See discussion here:
https://github.com/python/mypy/issues/14424

If you have a base class `Base` and a subclass `Sub`, then just declare the valid parameters for a method in `Sub`.  This will override any declaration in `Base`.  For mypy, probably need `# type: ignore[override]`.

If you have a method `xyz(self, x: Any)` in `Base` and you don't want to allow `Sub` to be called then add `def xyz(self, x: Never) -> Never` in `Sub`, or in `Sub`, you can write `xyz = None`.
