### ISSUE TITLE
CLN: Fix tests not executed by pytest

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas-stubs#444]
We have tests that are not beginning with the word `test_` so then `pytest` doesn't execute them.  Need to rename them and then see if they really work.
```
test_api_types.py:def check_extension_dtypes() -> None:
test_frame.py:def df_accepting_dicts_iterator() -> None:
test_frame.py:def series_added_in_astype() -> None:
test_io.py:def btest_read_fwf():
test_timefuncs.py:def fail_on_adding_two_timestamps() -> None:
```

**Comment by ramvikrams** [comment]
All these test work fine when adding `test_` before them, but when running pyright the `test_read_excel` in `test_io.py` gives this `pytest.PytestUnraisableExceptionWarning`

**Comment by Dr-Irv** [comment]
> All these test work fine when adding `test_` before them, but when running pyright the `test_read_excel` in `test_io.py` gives this `pytest.PytestUnraisableExceptionWarning`

I'd have to see it.  Could be a version issue.

**Comment by ramvikrams** [comment]
Sure Sir

**Comment by twoertwein** [comment]
When a released pandas includes this https://github.com/pandas-dev/pandas/pull/50397, we could re-use that script for pandas-stubs
