### ISSUE TITLE
Pandas and Matplotlib Dependency in the Stubs Package

### ISSUE THREAD

**Issue by lovetheguitar** [pandas-dev/pandas-stubs#45]
Could you please remove pandas and matplotlib from the dependencies of the pandas-stubs package.

Why would you have a separate stubs package and then depend on the main package and even matplotlib?

This package was super slim until 6 days ago: https://github.com/VirtusLab/pandas-stubs/blob/master/setup.py#L38-L40

Thank you.

**Comment by Dr-Irv** [comment]
> Most of matplotlib is not annotated. I think the matplotlib type used the most is `Axes` which unfortunately resolves to `Any`.

`matplotlib` *does* have annotations that are shipped with VS Code.  
> 
> ```python
> from matplotlib.axes import Axes
> 
> reveal_type(Axes)  # mypy: any, pyright: Unknown
> ```
> 
In the above example, within VS Code, you will get `Type[Axes]` on the `reveal_type()`

> If the goal of pandas-stubs is to eventually be part of typeshed and be recommeneded by mypy, I think pandas-stubs cannot depend on any actual code (and only contain pyi files).

I'm not sure that the goal is to make `pandas-stubs` part of `typeshed`, although I could see that happening in the future.

**Comment by twoertwein** [comment]
> matplotlib does have annotations that are shipped with VS Code.

Thank you, I didn't know that! If they have a standalone stub package, pandas-stubs (and pandas) should install that at least for the CI. mypy&pyright infer Axes on the pandas CI as Any/Unknown.

**Comment by Dr-Irv** [comment]
> > matplotlib does have annotations that are shipped with VS Code.
> 
> Thank you, I didn't know that! If they have a standalone stub package, pandas-stubs (and pandas) should install that at least for the CI. mypy&pyright infer Axes on the pandas CI as Any/Unknown.

To clarify, the `matplotlib` annotations are maintained by Microsoft in https://github.com/microsoft/python-type-stubs, and then Microsoft merges those stubs into the VS Code distribution.

**Comment by Dr-Irv** [comment]
closed via #66
