### ISSUE TITLE
Incorrect return type when slicing a dataframe with a mask (Series[bool])

### ISSUE THREAD

**Issue by DillonSteyl** [pandas-dev/pandas-stubs#452]
**Describe the bug**
`mypy` seems to think the return type of filtering a dataframe using a series of booleans is a series, not a dataframe. I only get this error with `mpy`, not `pyright`.

**To Reproduce**
A small example:
```py
def filter_dataframe(dataframe: pd.DataFrame) -> pd.DataFrame:
    filtered_dataframe = dataframe[~dataframe["Column"].isna()]
    return filtered_dataframe
```
This should be fine, but MyPy provides the following:
```
error: Incompatible return value type (got "Series[Any]", expected "DataFrame")  [return-value]
```

**Please complete the following information:**
 - OS: [e.g. Windows, Linux, MacOS]
   Windows 11, running Ubuntu using WSL2
 - OS Version [e.g. 22]
   20.04.2 LTS
 - python version
    3.9.14
 - version of type checker
   `mypy==0.991`
 - version of installed `pandas-stubs`
    `pandas-stubs==1.5.2.221124`

**Comment by Dr-Irv** [comment]
I can't replicate this.  I used this example:
```python
import pandas as pd

def filter_dataframe(dataframe: pd.DataFrame) -> pd.DataFrame:
    filtered_dataframe = dataframe[~dataframe["Column"].isna()]
    reveal_type(dataframe["Column"].isna())
    reveal_type(~dataframe["Column"].isna())
    reveal_type(filtered_dataframe)
    return filtered_dataframe
```
Got this result:
```text
filter.py:5: note: Revealed type is "pandas.core.series.Series[builtins.bool]"
filter.py:6: note: Revealed type is "pandas.core.series.Series[builtins.bool]"
filter.py:7: note: Revealed type is "pandas.core.frame.DataFrame"
Success: no issues found in 1 source file
```
I did use mypy 0.991 as well.  Double check that you don't have any settings in `pyproject.toml` or `mypy.ini` file - I didn't use any.

**Comment by DillonSteyl** [comment]
@Dr-Irv thanks for this - it turns out this issue popped up because I was using the [mypy extension for pandera](https://pandera.readthedocs.io/en/v0.8.1/mypy_integration.html). I wouldn't have expected this extension to cause issues with the existing pandas typing - I would have expected it to only touch the pandera-specific constructs.

I'll close this issue now as it is clearly not a `pandas-stubs` issue.
