### ISSUE TITLE
Missing values in JsonSeriesOrient

### ISSUE THREAD

**Issue by DaveMDS** [pandas-dev/pandas-stubs#458]
hi guys,
`JsonSeriesOrient` in _typing.py is missing two values, namely `table` and `values`

it should be:
`JsonSeriesOrient: TypeAlias = Literal["split", "records", "index", "table", "values"]`

`values` is also missing in panda docs, but I tested both on pandas 1.5.1 and they work as expected

Can they be added? forking and making a pr seems a bit overkill for this task ;)

Thanks in advance
DaveMDS

**Comment by bashtage** [comment]
We try not to add things that aren't documented.  The process to fix this would be:

1. Open a PR with pandas with the doc fix.
2. Open a PR here with the typing fix.

**Comment by ramvikrams** [comment]
@bashtage should I open the issue in pandas and open the pr here

**Comment by Dr-Irv** [comment]
Closing this.  `values` is not documented.  When documented, can re-open the issue.  `table` was fixed in #482

**Comment by DaveMDS** [comment]
Thanks !!
