### ISSUE TITLE
nightly failing - possibly due to pandas bug

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas-stubs#468]
nightly is failing due to arithmetic between offsets and period index changing result.  

So either we see if that gets fixed, or change our tests.

See https://github.com/pandas-dev/pandas/issues/50162

**Comment by ramvikrams** [comment]
Sir should we modify our tests or should wait for him to reply in the pandas issue.

**Comment by Dr-Irv** [comment]
We have to modify the tests, based on a discussion during the pandas development meeting.

Should build a function similar to `pytest_warns_bounded` that allows us to skip the test at runtime if the pandas version is greater than a passed value, and then use it in appropriate places where nightly is failing.

**Comment by ramvikrams** [comment]
> We have to modify the tests, based on a discussion during the pandas development meeting.
> 
> Should build a function similar to `pytest_warns_bounded` that allows us to skip the test at runtime if the pandas version is greater than a passed value, and then use it in appropriate places where nightly is failing.

thanks, I'll do it
