### ISSUE TITLE
Return type of Series.mean() and .median() is incorrect when series contains Timedeltas or Timestamps

### ISSUE THREAD

**Issue by sliedes** [pandas-dev/pandas-stubs#469]
**Describe the bug**

When `s` is a series of Timedelta series, `s.mean()` returns a Timedelta, but the stubs type the return value as `float`.

**To Reproduce**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.

```
import pandas as pd

s = pd.Series([pd.Timedelta("1 ns"), pd.Timedelta("2 ns"), pd.Timedelta("3 ns")])
mean: pd.Timedelta = s.mean()
median: pd.Timedelta = s.median()

s2 = pd.Series(
    [pd.Timestamp("2021-01-01"), pd.Timestamp("2021-01-02"), pd.Timestamp("2021-01-03")]
)
mean2: pd.Timestamp = s2.mean()
median2: pd.Timestamp = s2.median()
```

2. Indicate which type checker you are using (`mypy` or  `pyright`).

mypy

3. Show the error message received from that type checker while checking your example.

td_bug.py:5: error: Incompatible types in assignment (expression has type "float", variable has type "Timedelta")  [assignment]
td_bug.py:11: error: Incompatible types in assignment (expression has type "float", variable has type "Timestamp")  [assignment]

**Please complete the following information:**
 - OS: Linux
 - OS Version: Ubuntu 22.04.1 LTS
 - python version: 3.10.6
 - version of type checker: mypy 0.990 (compiled: yes)
 - version of installed `pandas-stubs`: pandas-stubs-1.5.2.221124

**Comment by Dr-Irv** [comment]
There are a couple of issues here:
1. With static typing, we can't infer the type of `s` in  `s = pd.Series([pd.Timedelta("1 ns"), pd.Timedelta("2 ns"), pd.Timedelta("3 ns")])`.  If you used `s = pd.Series(pd.TimedeltaIndex([pd.Timedelta("1 ns"), pd.Timedelta("2 ns"), pd.Timedelta("3 ns")]))`, then we could know that it was a `TimedeltaSeries`, and could then type the `mean()` correctly.  Same is true for `s2`, where you would use `pd.DatetimeIndex()` instead and typing can then know the seris is a `TimestampSeries`.
2.  We should add `mean()` and `median()` for `TimedeltaSeries` and `TimestampSeries` to be `Timedelta` and `Timestamp` , respectively.

PR welcome.

**Comment by gandhis1** [comment]
What is the type of the `list`? If it's `List[pd.Timedelta]` then I believe we would be able to create a generic constructor that could carry the type over.

**Comment by Dr-Irv** [comment]
> What is the type of the `list`? If it's `List[pd.Timedelta]` then I believe we would be able to create a generic constructor that could carry the type over.

I had the same idea after writing the above.

We can change
https://github.com/pandas-dev/pandas-stubs/blob/52f8ebd94a09213ffacef943e6708cba816280f6/pandas-stubs/core/series.pyi#L207
to include `Sequence[Timedelta | np.timedelta64 | datetime.timedelta]`
and change
https://github.com/pandas-dev/pandas-stubs/blob/52f8ebd94a09213ffacef943e6708cba816280f6/pandas-stubs/core/series.pyi#L187
to include `Sequence[Timestamp | np.datetime64 | datetime.datetime]`
and then the type would be correctly inferred to be `TimedeltaSeries` and `TimestampSeries`, respectively.

Then add `mean()` and `median()` to those 2 classes.

**Comment by SimonDR-Boltzmann** [comment]
The same issue occurs for `pd.Timestamp` with functions like `std()`
