### ISSUE TITLE
Problem with `.to_dict()` type inference

### ISSUE THREAD

**Issue by filipelauarqantev** [pandas-dev/pandas-stubs#483]
**Describe the bug**

I have a dataframe or pandas series and when I use the `.to_dict()` the inferred type by pandas-stubs is `Dict[Hashable, Any]`. In my case I know that that the index is an int but there is an error when I type the output as `Dict[int, Any]` saying that int is not a Hashable type.

Is there any solution for better inferring the type in this case?

**To Reproduce**

**Please complete the following information:**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.
```
import pandas as pd

id=[1,2,3]
value=["a", "b", "c"]

df = pd.DataFrame(zip(id, value), columns=["id", "value"])
df.set_index("id")["value"].to_dict()

def funct(df_dict: Dict[int, Any]) -> None:
     pass
```

2. Indicate which type checker you are using (`mypy` or  `pyright`).3. 
Mypy

3. Show the error message received from that type checker while checking your example.4. 

`error: Argument 4 to "funct" has incompatible type "Dict[Hashable, Any]"; expected "Dict[int, Any]" `

**Additional context**
I am running it in `python version 3.10`

**Comment by twoertwein** [comment]
DataFrame/Series are not Generic with respect to the index type, so we cannot return `dict[int, Any`. I think we would need to relax the annotation to just `dict` to avoid any mypy/pyright errors when users implicitly "cast" it to `dict[int, Any]`. I'd be okay with that change (for input arguments, I would still require something like `dict[HashableT, Any]` but for return values, it might be worth relaxing it).

@Dr-Irv @bashtage

**Comment by Dr-Irv** [comment]
I see two ways of looking at this:
1. By us saying that we are returning `Mapping[Hashable, Any]`, and then the user has created a function expecting `dict[int, Any]`, we've alerted the user that they can't just assume all the keys of the `dict` will be `int`, so they should do a `cast` if they are sure that will be the case.
2. Any `Mapping` must have a `Hashable` as its key, so if we just return `Mapping` for `to_dict()`, we don't lose anything, and people aren't forced to `cast`.

I'm leaning towards (1), because we are making it clear that you can't assume the type of the keys of that dict.  I could be persuaded towards (2).

**Comment by gandhis1** [comment]
Given a `Mapping[Hashable, Any]` doesn't add anything, I like 2. If there was actually any type specificity I would be firmly in camp 1.

**Comment by Dr-Irv** [comment]
> Given a `Mapping[Hashable, Any]` doesn't add anything, I like 2.

One could argue that it is a signal that the `dict` we return has an unknown key type, so if you are assuming the keys are `int` (as in this example), that is a wrong assumption.  So in that sense, we have "added" something.

**Comment by twoertwein** [comment]
`Mapping` makes only the values covariant. I would prioritize getting the container type right (`dict` vs `(Mutable)Mapping`) as opposed to differentiating `Any` vs `Hashable`.

**Comment by Dr-Irv** [comment]
> `Mapping` makes only the values covariant. I would prioritize getting the container type right (`dict` vs `(Mutable)Mapping`) as opposed to differentiating `Any` vs `Hashable`.

So should we change the return type to be `dict[Hashable, Any]` ?

**Comment by gandhis1** [comment]
> One could argue that it is a signal that the `dict` we return has an unknown key type

Unknown to the type checker, because we do not have generic indexes. I'd imagine most users are aware of what type it is, so forcing users to `cast` for what is arguably a limitation of the annotations can be a bit cumbersome.

**Comment by Dr-Irv** [comment]
> Unknown to the type checker, because we do not have generic indexes. I'd imagine most users are aware of what type it is, so forcing users to `cast` for what is arguably a limitation of the annotations can be a bit cumbersome.

Fair enough.  Hopefully someone can do a PR changing the return type to just `dict` .
