### ISSUE TITLE
mypy complaining on sorted, min and max builtins on Version 1.5.2.221213

### ISSUE THREAD

**Issue by williamjamir** [pandas-dev/pandas-stubs#497]
**Describe the bug**

Starting with this commit https://github.com/pandas-dev/pandas-stubs/commit/bc615436797f4fd49b590428050fb9bd153a56df, I started to see complaints in my codebase about the `SupportsRichComparison` type.

One example is with the `sorted` method, but it also happens with `min` and `max`:

**To Reproduce**

```python
df = pd.DataFrame({'x': [1], 'y': [2], 'z': [3]})
sorted(df.columns)
reveal_types
```

```
>>> mypy test.py

error: Value of type variable "SupportsRichComparisonT" of "sorted" cannot be "Union[str, bytes, date, timedelta, int, float, complex, Tuple[Hashable, ...]]"  [type-var]
note: Revealed local types are:
note:     df: pandas.core.frame.DataFrame
```

Before that commit, the type from `df.columns` was `iterable[any]`, but after the commit, it now has this `complex` type, which doesn't have support for `__lt__` and `__gt__`

How do you think we should proceed on this case? 
`cast`/`ignore` on the code base is the indicated solution, or is there something we can "fix" on the stubs?

**Additional context**

Just to disclose, this is my "full use case" that started my investigation:
```
def acme(df: pd.DataFrame, metrics: set[str]) -> pd.DataFrame:
    df_metrics = set(df.columns) - set(Dimensions)
    if unknown_metrics := df_metrics - metrics:
        raise MyCustomException(f'My cool msg: {", ".join(sorted(metrics))}')

    return df
```

**Please complete the following information:**

OS: MacOS M1
OS Version Ventura 13.0
python version: 3.9.12 
version of type checker: mypy 0.991 (compiled: yes)
version of installed pandas-stubs
pandas==1.5.2
pandas-stubs==1.5.2.221213

**Comment by gandhis1** [comment]
I did that change. Thinking out loud here, would changing `tuple[Hashable, ...]` to just `tuple` avoid this issue? Or should we just make it a `tuple[Scalar, ...]`?

**Comment by Dr-Irv** [comment]
I think the change to make is to say that `Index` supports comparisons.  To do this, add to `core/indexes/base.pyi` the following:

```python
from _typeshed import SupportsRichComparisonT
```
and change the definition of the `Index` class to:
```python
class Index(IndexOpsMixin, PandasObject, Iterable[SupportsRichComparisonT]):
```
That makes the example work with pyright.  But mypy still complains.  It may be that we have to declare that `Timestamp` and `Timedelta` are subclasses of `SupportsAllComparisons` for this to work, or just do a `#type: ignore` for mypy on the definition of `__iter__()` in that file.

**Comment by williamjamir** [comment]
Hmmm, but would we not be "violating" the Pandas API?

I mean, it's possible to use any hashable object on the Index (including `complex`) 
```
import pandas as pd

>>> df = pd.DataFrame({complex(1,1): [1,2], 1: [1,2], 1.2: [1,2], '1.3': [1,2]})
>>> df
   (1+1j)  1  1.2  1.3
0       1  1    1    1
1       2  2    2    2

>>> df.columns
Index([(1+1j), 1, 1.2, '1.3'], dtype='object')
```


```
>>> sorted(df.columns)
Traceback (most recent call last):
  File "/Users/william.silva/.pyenv/versions/3.9.7/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
TypeError: '<' not supported between instances of 'int' and 'complex'

**Comment by Dr-Irv** [comment]
> Hmmm, but by saying that `Index` supports `SupportsRichComparisonT` would we not be a "violation" of the Pandas API?
> Besides, I don't know how practical it is to use `complex` in `Index` 😅

You'd have the same issue without `complex`:
```python
>>> import pandas as pd
>>> df = pd.DataFrame({ 1: [1,2], 1.2: [1,2], '1.3': [1,2]})
>>> df
   1  1.2  1.3
0  1    1    1
1  2    2    2
>>> df.columns
Index([1, 1.2, '1.3'], dtype='object')
>>> sorted(df.columns)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'str' and 'float'
```
And you can fool even lists with python:
```python
x = [1, 1.2, 1.3]
def modify(q: list):
    q[2] = '1.3'
modify(x)
print(x)
print(sorted(x))
```
The above code will fail for the same reason, but neither pyright nor mypy will pick up that this is invalid.

If we make this change, we are supporting the typical uses of pandas.  We are not tracking what are the dtypes within an `Index`.  So if we make the suggested change, we've made the type of `Index` a bit too wide if the underlying values don't support comparisons, but most people have a consistent comparable dtype within an `Index`.

**Comment by gandhis1** [comment]
@williamjamir I think your example is just pointing out sorting of heterogeneous types. I think a better example would be a single-type index of type `complex`. Those are `Hashable`, but not sortable. So you are correct insofar as there is no guarantee `DataFrame.columns` is sortable. However, the way these stubs are now, we kind of need to think practically. The most common use case is `str` columns and other sortable types, and it's probably rare someone is going to have a non-sortable type.

I wonder if there's a good way to organize the issues on this repo such that we can isolate all of the issues that have something to do with the lack of generic indices. At some point that's going to have to be addressed, and it's a huge undertaking, so crowding the repo with issues (or closing them) is not as ideal as moving these issues to a some dedicated place.

**Comment by Dr-Irv** [comment]
> I wonder if there's a good way to organize the issues on this repo such that we can isolate all of the issues that have something to do with the lack of generic indices. At some point that's going to have to be addressed, and it's a huge undertaking, so crowding the repo with issues (or closing them) is not as ideal as moving these issues to a some dedicated place.

I created a new label "Generic Index" that we can use for that.  Feel free to apply it to the other related issues.

**Comment by Dr-Irv** [comment]
> I think the change to make is to say that `Index` supports comparisons. To do this, add to `core/indexes/base.pyi` the following:
> 
> ```python
> from _typeshed import SupportsRichComparisonT
> ```
> 
> and change the definition of the `Index` class to:
> 
> ```python
> class Index(IndexOpsMixin, PandasObject, Iterable[SupportsRichComparisonT]):
> ```
> 
> That makes the example work with pyright. But mypy still complains. It may be that we have to declare that `Timestamp` and `Timedelta` are subclasses of `SupportsAllComparisons` for this to work, or just do a `#type: ignore` for mypy on the definition of `__iter__()` in that file.

This doesn't work.  It breaks when you do `list(some_index)` where that no longer returns the correct type.  More investigation needed.

**Comment by Dr-Irv** [comment]
Turns out that the issue may be that `np.datetime64` and `np.timedelta64` don't support the `SupportsRichComparison`, so can handle that by changing the return type of `Index.__iter__()` to not include them, which is fine because if they are used in an index, pandas converts them to `pd.Timestamp()` and `pd.Timedelta()` respectively anyway.
