### ISSUE TITLE
nightly failing due to timedelta and NA values

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas-stubs#499]
Nightly failing due to restriction on `to_numpy()` values for `na_value`

In `test_timefuncs.py`, we have this test:
```python
check(assert_type(td_s.to_numpy(na_value=0), np.ndarray), np.ndarray)
```
Need to change it to
```python
check(assert_type(td_s.to_numpy(na_value=pd.Timedelta(0)), np.ndarray), np.ndarray)
```

**Comment by bashtage** [comment]
The definitions probably also adjustment since looks like int is not allowed.
