### ISSUE TITLE
`is_*_dtype` functions don't accept extension dtypes

### ISSUE THREAD

**Issue by gsakkis** [pandas-dev/pandas-stubs#514]
The [`_ArrayOrDtype`](https://github.com/pandas-dev/pandas-stubs/blob/db3b883dbe8d22863c8aca37c89431afce3b57e2/pandas-stubs/core/dtypes/common.pyi#L31-L33) alias doesn't include `ExtensionDtype`, which I believe all the `is_*_dtype` functions accept.

**Comment by Dr-Irv** [comment]
Thanks for the report.  Simple fix is to add `ExtensionDtype` here:
https://github.com/pandas-dev/pandas-stubs/blob/db3b883dbe8d22863c8aca37c89431afce3b57e2/pandas-stubs/core/dtypes/common.pyi#L32

Should add tests for various types like `str`, `"str"`, `ExtensionDtype`, etc. to the tests in https://github.com/pandas-dev/pandas-stubs/blob/main/tests/test_api_types.py

**Comment by ramvikrams** [comment]
> Should add tests for various types like `str`, `"str"`, `ExtensionDtype`, etc. to the tests in https://github.com/pandas-dev/pandas-stubs/blob/main/tests/test_api_types.py

I think we had test for `ExtensionDtype` in this file.

**Comment by Dr-Irv** [comment]
> I think we had test for `ExtensionDtype` in this file.

Yes, but not for the `is_*_dtype` functions.

**Comment by ramvikrams** [comment]
> Yes, but not for the `is_*_dtype` functions.

Ya, i'll add them.

**Comment by ramvikrams** [comment]
Sir, do you have a short example for ExtensionDtype i am unable to get one

**Comment by Dr-Irv** [comment]
> Sir, do you have a short example for ExtensionDtype i am unable to get one

You just want to make sure that things like `is_bool_dtype(ExtensionDtype)` work  (and similar for the other `is_*_dtype()` functions.

Also want to add tests for native types and their string representations.

**Comment by ramvikrams** [comment]
`ExtensionDtype` is a custom data-type but many `is_*_dtype()` functions in `pytest` are saying that they cannot interpret it as data-type

**Comment by Dr-Irv** [comment]
> `ExtensionDtype` is a custom data-type but many `is_*_dtype()` functions in `pytest` are saying that they cannot interpret it as data-type

Write an example that fails and show it, and I can look into it

**Comment by ramvikrams** [comment]
```
    check(assert_type(api.is_object_dtype(ExtensionDtype), bool), bool)

```
this returns 
```
FAILED tests/test_api_types.py::test_is_object_dtype - TypeError: Cannot interpret '<property object at 0x7fc56b581fd0>' as a data...
```

**Comment by Dr-Irv** [comment]
I think that's a bug in `is_object_dtype()` that I'll have to report.  So leave out that test for now there.

**Comment by ramvikrams** [comment]
Actually 11 of the are failing which are 
```
is_complex_dtype
is_datetime64_any_dtype
is_datetime64_dtype
is_float_dtype
is_int64_dtype
is_integer_dtype
is_numeric_dtype
is_object_dtype
is_signed_integer_dtype
is_timedelta64_dtype
is_unsigned_integer_dtype
```

**Comment by Dr-Irv** [comment]
Thanks.  I created https://github.com/pandas-dev/pandas/issues/50923 to report this.

Can you still include them in the tests, but comment them out.  E.g.
```python
# check(assert_type(api.is_object_dtype(ExtensionDtype), bool), bool)   pandas GH 50923
```

Then whenever that gets fixed, we can put back the tests in the future.

**Comment by ramvikrams** [comment]
> Thanks. I created [pandas-dev/pandas#50923](https://github.com/pandas-dev/pandas/issues/50923) to report this.
> 
> Can you still include them in the tests, but comment them out. E.g.
> 
> ```python
> # check(assert_type(api.is_object_dtype(ExtensionDtype), bool), bool)   pandas GH 50923
> ```
> 
> Then whenever that gets fixed, we can put back the tests in the future.


Yes i'll do that
