### ISSUE TITLE
CLEAN:  Remove some unnecessary types from `S1`

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas-stubs#520]
I think that `S1` has types that are not needed, e.g., the `datetime` types.  

As discussed here https://github.com/pandas-dev/pandas-stubs/pull/519#pullrequestreview-1271164311

we should see which ones we can safely remove without changing any tests or other parts 

For things like `Timestamp`, `Timedelta`, `Period`, we may be able to get rid of all references to `Series[Timestamp]`, `Series[Timedelta]` and `Series[Period]` because we have `TimestampSeries`, `TimedeltaSeries` and `PeriodSeries`, but we leave the references just in the class definition there from an inheritance perspective.

@ramvikrams to investigate

**Comment by ramvikrams** [comment]
> I think that `S1` has types that are not needed, e.g., the `datetime` types.
> 
> As discussed here [#519 (review)](https://github.com/pandas-dev/pandas-stubs/pull/519#pullrequestreview-1271164311)
> 
> we should see which ones we can safely remove without changing any tests or other parts
> 
> For things like `Timestamp`, `Timedelta`, `Period`, we may be able to get rid of all references to `Series[Timestamp]`, `Series[Timedelta]` and `Series[Period]` because we have `TimestampSeries`, `TimedeltaSeries` and `PeriodSeries`, but we leave the references just in the class definition there from an inheritance perspective.
> 
> @ramvikrams to investigate


i'll look into it

**Comment by ramvikrams** [comment]
1)For Series[Timestamp] 

 from test_scalars.py we have this TimestampSeries can't be used here
```
    c_series_dt64: pd.Series[pd.Timestamp] = pd.Series(
        [1, 2, 3], dtype="datetime64[ns]"
    )
```
We have instances like this, herealso we can't replace it
```
_EdgesTimestamp: TypeAlias = Union[
    Sequence[DatetimeLike],
    npt.NDArray[np.datetime64],
    pd.Series[pd.Timestamp],
    TimestampSeries,
    pd.DatetimeIndex,
]
```
we also have this I thik both these are req.
```
    def __eq__(self, other: TimestampSeries | Series[Timestamp]) -> Series[bool]: ...  # type: ignore[misc]
```



2) Series[Timedelta] can be changed with TimedeltaSeries at most places and similary with Series[Period]
3) we cannot also remove `interval[*]`  as they are referenced
4) we can remove `datetime.*`

**Comment by Dr-Irv** [comment]
> 1)For Series[Timestamp]
> 
> from test_scalars.py we have this TimestampSeries can't be used here
> 
> ```
>     c_series_dt64: pd.Series[pd.Timestamp] = pd.Series(
>         [1, 2, 3], dtype="datetime64[ns]"
>     )
> ```
> 
OK, that's actually a bug in the tests and the types because the correct type should be `Series[np.datetime64]` but if you make that change, then the operators aren't properly defined and you'll get other errors, so for now, you can leave that test alone and it is something I can look to fix.  (It's non-trivial)

> We have instances like this, here also we can't replace it
> 
> ```
> _EdgesTimestamp: TypeAlias = Union[
>     Sequence[DatetimeLike],
>     npt.NDArray[np.datetime64],
>     pd.Series[pd.Timestamp],
>     TimestampSeries,
>     pd.DatetimeIndex,
> ]
> ```

Are you saying if you remove `pd.Series[pd.Timestamp]` from that declaration, a test will fail?

> 
> we also have this I think both these are req.
> 
> ```
>     def __eq__(self, other: TimestampSeries | Series[Timestamp]) -> Series[bool]: ...  # type: ignore[misc]
> ```
> 
Yes, it's related to (1) above.  So you have to leave it in for now.

> 2. Series[Timedelta] can be replaced with TimedeltaSeries at most places and similary with Series[Period]

That's good.

> 3. we cannot also remove `interval[*]`  as they are referenced

Yes, I think that has to stay.

> 4. we can remove `datetime.*`

Good.

**Comment by ramvikrams** [comment]
> > We have instances like this, here also we can't replace it
> > ```
> > _EdgesTimestamp: TypeAlias = Union[
> >     Sequence[DatetimeLike],
> >     npt.NDArray[np.datetime64],
> >     pd.Series[pd.Timestamp],
> >     TimestampSeries,
> >     pd.DatetimeIndex,
> > ]
> > ```
> 
> Are you saying if you remove `pd.Series[pd.Timestamp]` from that declaration, a test will fail?
> 


No, test do not fail but it is  `_EdgeTimestamp` is called in a func in that file, So will it be a good option to remove it

**Comment by ramvikrams** [comment]
> > ```
> >     def __eq__(self, other: TimestampSeries | Series[Timestamp]) -> Series[bool]: ...  # type: ignore[misc]
> > ```
> 
> Yes, it's related to (1) above. So you have to leave it in for now.

I don't think it's related to 1 as we have more declarations like this in `pandas-stubs\_libs\tslibs\timestamps.pyi` they are used in `Timestamp` funcs

**Comment by Dr-Irv** [comment]
> > Are you saying if you remove `pd.Series[pd.Timestamp]` from that declaration, a test will fail?
> 
> No, test do not fail but `_EdgeTimestamp` is called in a func in that file, So will it be a good option to remove it

So just to clarify you can remove `pd.Series[pd.Timestamp]` in that `TypeAlias`

**Comment by Dr-Irv** [comment]
> > > ```
> > >     def __eq__(self, other: TimestampSeries | Series[Timestamp]) -> Series[bool]: ...  # type: ignore[misc]
> > > ```
> > 
> > 
> > Yes, it's related to (1) above. So you have to leave it in for now.
> 
> I don't think it's related to 1 as we have more declarations like this in `pandas-stubs\_libs\tslibs\timestamps.pyi` they are used in `Timestamp` funcs

Try removing them all and see which tests fail, then put back the minimal number so the current tests pass.  It's related because I think if you take `Series[Timestamp]` out of the `def __eq__()`, a test will fail, but that's because of (1) above.

**Comment by ramvikrams** [comment]
> > > > ```
> > > >     def __eq__(self, other: TimestampSeries | Series[Timestamp]) -> Series[bool]: ...  # type: ignore[misc]
> > > > ```
> > > 
> > > 
> > > Yes, it's related to (1) above. So you have to leave it in for now.
> > 
> > 
> > I don't think it's related to 1 as we have more declarations like this in `pandas-stubs\_libs\tslibs\timestamps.pyi` they are used in `Timestamp` funcs
> 
> Try removing them all and see which tests fail, then put back the minimal number so the current tests pass. It's related because I think if you take `Series[Timestamp]` out of the `def __eq__()`, a test will fail, but that's because of (1) above.



Actually there are 5, from 3 of them we can remove `Series[Timestamp]` mypy,pyright pass the test but pytest shows 0 errors some time,1 the other time or 2 sometime. Don't know what is wrong with pytest

**Comment by Dr-Irv** [comment]
> Actually there are 5(`__eq__ , __ne__ , __gt__ , __ge__ , __le__`), from 3(`__gt__ , __ge__ , __le__`) of them we can remove `Series[Timestamp]` mypy,pyright pass the test but pytest shows 0 errors some time,1 the other time or 2 sometime. Don't know what is wrong with pytest

It might relate to (1).  If you want, create a PR with what you have and I can take a look.

**Comment by ramvikrams** [comment]
> > Actually there are 5(`__eq__ , __ne__ , __gt__ , __ge__ , __le__`), from 3(`__gt__ , __ge__ , __le__`) of them we can remove `Series[Timestamp]` mypy,pyright pass the test but pytest shows 0 errors some time,1 the other time or 2 sometime. Don't know what is wrong with pytest
> 
> It might relate to (1).  If you want, create a PR with what you have and I can take a look.


Yes I'll create a pr

**Comment by ramvikrams** [comment]
@Dr-Irv Sir i'll make the PR tommorow, i am not feeling well today So taking rest.

**Comment by Dr-Irv** [comment]
> @Dr-Irv Sir i'll make the PR tommorow, i am not feeling well today So taking rest.

No rush!
