### ISSUE TITLE
DataFrame xs method's axis parameter is typed as SeriesAxisType

### ISSUE THREAD

**Issue by jbiz25** [pandas-dev/pandas-stubs#524]
The DataFrame xs method's axis parameter is typed as SeriesAxisType.  Should be AxisType.

Using pandas-stubs version 1.5.2.230105.

**Comment by Dr-Irv** [comment]
@jbiz25 can you provide an example that fails with the current typing?

**Comment by jbiz25** [comment]
Sure, sorry, should have included one.

import pandas as pd

df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
axis = 1
df.xs(0, axis=axis)  # pyright tells me Literal[1] isn't allowed 

According to pandas docs, DataFrame.xs method's `axis` can be axis{0 or ‘index’, 1 or ‘columns’}, default 0

**Comment by Dr-Irv** [comment]
Thanks.

Need to remove definition of `xs` from `core/generic.pyi` and place copies in both `core/frame.pyi` and `core/series.pyi`.

In `series.pyi`, use `SeriesAxisType` for `axis` argument, and make return type `Series`.   In `frame.pyi`, use `AxisType`, but don't change the return type.

PR welcome.
