### ISSUE TITLE
The DataFrame.sample function does not accept Generator objects for random_state

### ISSUE THREAD

**Issue by intermezzio** [pandas-dev/pandas-stubs#525]
**Describe the bug**
When calling [DataFrame.sample](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sample.html) with a random_state argument, a type warning is
raised if a numpy.random.RandomState object is used, claiming that only an integer
can be inputted as an argument.

**To Reproduce**

```python
import numpy as np
import pandas as pd

rng = np.random.default_rng(0)

df = pd.DataFrame(data={'col1': [1, 2], 'col2': [3, 4]})
df.sample(n=1, random_state=rng)
```

Error message:
```
Argument of type "Generator" cannot be assigned to parameter "random_state" of type "int | None" in function "sample"
  Type "Generator" cannot be assigned to type "int | None"
    "Generator" is incompatible with "int"
```

**Please complete the following information:**
 - OS: Manjaro Linux
 - python 3.10.9
 - version of type checker: pyright 1.1
 - version of installed `pandas-stubs`: 1.5.2

**Comment by Dr-Irv** [comment]
Thanks for the report.  Need to change this line:
https://github.com/pandas-dev/pandas-stubs/blob/93f3b2418abc7becf08e63318cb236d8dee4e1c1/pandas-stubs/core/frame.pyi#L1919

to include all the possible arguments that are documented here:  
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html

Easiest solution is to borrow from the pandas source.  Add this to `_typing.pyi`:
```python
RandomState = Union[
    int,
    ArrayLike,
    np.random.Generator,
    np.random.BitGenerator,
    np.random.RandomState,
]
```

And add appropriate tests.

**Comment by intermezzio** [comment]
I'm working on that and can make a pull request soon.
