### ISSUE TITLE
BUG: DataFrame.insert value is too strict

### ISSUE THREAD

**Issue by phofl** [pandas-dev/pandas-stubs#529]
**Describe the bug**

**To Reproduce**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.
2. Indicate which type checker you are using (`mypy` or  `pyright`).
3. Show the error message received from that type checker while checking your example.

```
df = DataFrame({"a": [1, 2]})
df.insert(loc=0, column="b", value=None)
```

```
error: Value of type variable "ListLike" of "insert" of "DataFrame" cannot be "None"  [type-var]
```

**Please complete the following information:**
 - OS: [e.g. Windows, Linux, MacOS] MacOS
 - OS Version [e.g. 22] Venturar 13.1
 - python version 3.10
 - version of type checker mypy 0.991
 - version of installed `pandas-stubs` latest

**Additional context**

According to the main repo, any Scalar is allowed

**Comment by Dr-Irv** [comment]
Need to change
https://github.com/pandas-dev/pandas-stubs/blob/495e91f28b6777e412e71e1f591caf65f8adea8e/pandas-stubs/core/frame.pyi#L546

to be `value: Scalar | ListLikeU | None` with appropriate tests.
