### ISSUE TITLE
pandas.StringDtype's optional argument is reported by pyright as not optional

### ISSUE THREAD

**Issue by jbiz25** [pandas-dev/pandas-stubs#534]
**Describe the bug**
If I instantiate pd.StringDtype without args, pyright is complaining that it's missing an arg. 

**To Reproduce**
import pandas as pd
d = pd.StringDtype()  # pyright says missing the `storage` arg, but that arg is optional

**Please complete the following information:**
 Windows
pyright
pandas-stubs-1.5.3.230203

**Comment by Dr-Irv** [comment]
Thanks for the report.

Need to change https://github.com/pandas-dev/pandas-stubs/blob/b76dbb6952f661c6e8314bd8c1dfefeda181125d/pandas-stubs/core/arrays/string_.pyi#L10 to be ` storage: Literal["python", "pyarrow"] | None = None` with appropriate tests added to https://github.com/pandas-dev/pandas-stubs/blob/b76dbb6952f661c6e8314bd8c1dfefeda181125d/tests/test_dtypes.py#L127
