### ISSUE TITLE
SeriesGroupBy Doesn't contain idxmax attribute

### ISSUE THREAD

**Issue by wadhah101** [pandas-dev/pandas-stubs#548]
**Describe the bug**
SeriesGroupBy type lacks the idxmax attribute.

**To Reproduce**
Using mypy
```python
import pandas as pd

example_df = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})

example_df_groupby = example_df.groupby("a")

# reveal_type(example_df_groupby)
# Revealed type is 'pandas.core.groupby.generic._DataFrameGroupByScalar'

example_series_groupby = example_df_groupby["a"]

# reveal_type(example_series_groupby)
# pandas.core.groupby.generic.SeriesGroupBy[Any]

result = example_series_groupby.idxmax()
#  mypy error: "SeriesGroupBy[Any]" has no attribute "idxmax"  [attr-defined]

print(result)
# a
# 1    0
# 2    1
# 3    2
# Name: a, dtype: int64

```

**Please complete the following information:**
 - OS: MacOS
 - OS 13.1
 - python : 3.10.9
 - mypy==1.0.1 
 - version of installed `pandas-stubs` :  pandas-stubs==1.5.3.230214

**Comment by Dr-Irv** [comment]
Thanks for the report.  Looks like we have to fix `idxmax()` and `idxmin()` in `core/groupby/generic.pyi`, including it in both `DataFrameGroupBy` and `SeriesGroupBy` and make sure we get the return types correct (along with tests).
