### ISSUE TITLE
Series.mean() does not return an float

### ISSUE THREAD

**Issue by alkatar21** [pandas-dev/pandas-stubs#552]
**Describe the bug**
`Series.mean()` [is typed as float](https://github.com/pandas-dev/pandas-stubs/blob/main/pandas-stubs/core/series.pyi#L1533), but actually returns a `numpy.float64`.

This errors because I need to call `.item()` to get the actual float.

**To Reproduce**
```py
# pyright: strict
import pandas as pd

mean = pd.Series([1, 2, 3, 4]).mean()
print(type(mean)) # numpy.float64 instead of float
mean.item() # Cannot access member "item" for type "float"  Member "item" is unknown Pylance (reportGeneralTypeIssues)
```

**Please complete the following information:**
 - OS: Linux
 - OS Version 20.04
 - python 3.8.10
 - version of type checker: 1.1.293
 - version of installed `pandas-stubs`: Pylance v2023.2.31

**Additional context**
I must have the actual float for `yaml.safe_dump`.

**Comment by Dr-Irv** [comment]
I couldn't find docs in numpy for `numpy.float64.item()`, but it is in the type stubs for numpy.

Just needs a change here:
https://github.com/pandas-dev/pandas-stubs/blob/300adaf094d18537a6812223c357e476acda737c/pandas-stubs/core/series.pyi#L1540

But I'm also guessing that some tests will need to be updated as well, e.g., 
https://github.com/pandas-dev/pandas-stubs/blob/300adaf094d18537a6812223c357e476acda737c/tests/test_series.py#L294

which should be converted to the `check(assert_type(...` pattern used elsewhere

**Comment by ramvikrams** [comment]
I think we would also have to change it in `frame.pyi` because `test_frame.py` fails mypy checks

**Comment by Dr-Irv** [comment]
> I think we would also have to change it in `frame.pyi` because `test_frame.py` fails mypy checks

Not sure that I see what you mean.  In `frame.pyi`, `mean()` returns a `Series`, so the `np.float64` versus `float` doesn't apply.
