### ISSUE TITLE
Invalid index type _LocIndexerFrame

### ISSUE THREAD

**Issue by sonderyugen** [pandas-dev/pandas-stubs#555]
**Describe the bug**

I've recently upgraded from pandas 1.4.3 and pandas-stubs 1.4.3.220829 to pandas 1.5.3 and pandas-stubs 1.5.3.230214 index a dataframe using df.loc[] of type:     `Tuple[List[str], str]]` so as to get a series from a list of row index values at the column str value.  

This passes all my existing tests from pre upgrade so it functions and it should because it isn't uncommon to pass .loc[] a single column or row value using a string.

Type checker error output:

_error: Invalid index type "Tuple[List[Any], str]" for "_LocIndexerFrame"; expected type "Union[Callable[[DataFrame], List[<nothing>]], List[<nothing>], Tuple[Union[List[<nothing>], Hashable], Union[List[<nothing>], slice, Series[bool], Callable[..., Any]]]]")_

**To Reproduce**

    dataframe = pd.Dataframe(data=[range(0, 10), range(0, 10)], columns=["desired_column", "other_column"]
    index_list  = list(dataframe.sort_values(by="desired_column).head(3).index)
    new_series_list = list(dataframe.loc[index_list, "desired_column"])

using:

mypy = "==0.910"
pandas = "==1.5.3"
pandas-stubs = "==1.5.3.230214"

python 3.9

 Windows 10
 wsl 2.0

**Additional context**
I did not upgrade mypy at all.

If I try putting the 'desired column' str inside a list so as to satisfy the type checker as follows:

`
    dataframe = pd.Dataframe(columns=["desired_column", "other_column"]
    index_list  = list(dataframe.sort_values(by="desired_column).head(10).index)
    new_series_list = list(dataframe.loc[index_list, ["desired_column"]])
`

the type checker is happy but instead of a list of the series from the dataframe column I get apparently a list that just contains the string 'desired_column':

Logged error output:
 LOG.error(new_series_list)
ERROR  ['desired_column']

This did not throw any kind of type error on the previous versions of pandas and stubs 1.4.3 and 1.4.3.220829 respectively.

I am sure there is a work around here but I this shouldn't throw an error.

**Comment by Dr-Irv** [comment]
I tried the following code with `mypy` version 1.0, and it works fine, so please try upgrading `mypy` and see if that fixes the problem.
```python
import pandas as pd

dataframe = pd.DataFrame(data=[range(0, 10), range(0, 10)], columns=["desired_column", "other_column"])
index_list  = list(dataframe.sort_values(by="desired_column").head(3).index)
new_series_list = list(dataframe.loc[index_list, "desired_column"])
```

Note that there were some syntax errors in what you provided, and that is fixed in the above.
