### ISSUE TITLE
Cannot assign member "columns" for type "DataFrame"

### ISSUE THREAD

**Issue by NeilGirdhar** [pandas-dev/pandas-stubs#564]
Looks like the `column` property is [missing](https://github.com/pandas-dev/pandas-stubs/blob/6829a993697f8c5d65b721ca1cec3980ac79e69c/pandas-stubs/core/interchange/dataframe_protocol.pyi#L93) from `DataFrame`.

**Comment by gandhis1** [comment]
That's not the main `DataFrame` stubs location. The main location is here: https://github.com/pandas-dev/pandas-stubs/blob/master/pandas-stubs/core/frame.pyi

I suspect the issue you are touching on is this one: https://github.com/pandas-dev/pandas-stubs/issues/73

Which is a bug in MyPy

**Comment by Dr-Irv** [comment]
I agree with @gandhis1 .  So I will close this.  If you have an example that illustrates otherwise, please feel free to comment here and we can reopen.

**Comment by NeilGirdhar** [comment]
@gandhis1 I'm using Pyright, and are you sure that it's a bug with Pyright?  Pyright is extremely solid.

**Comment by NeilGirdhar** [comment]
Okay thanks, it's probably this regression: https://github.com/microsoft/pyright/issues/4743

**Comment by gandhis1** [comment]
Unrelated to the pyright regression, is it worth re-opening #73 and tagging with "mypy bug" as has been done recently for other `mypy` issues?
