### ISSUE TITLE
`Series.astype(object)` not supported anymore

### ISSUE THREAD

**Issue by tcrasset** [pandas-dev/pandas-stubs#565]
**Describe the bug**

`Series.astype(object)` runs fine, and used to typecheck properly before, but since updating `mypy` and/or `pandas-stubs`, it doesn't anymore. Didn't take the time to find a working version that did not throw errors.

**To Reproduce**
```python
import pandas as pd

s = pd.Series([1, 1])
s = s.astype(object)
```

Getting the following error message:

```text
error: Argument 1 to "astype" of "Series" has incompatible type "Type[object]"; expected "Union[Type[bool], BooleanDtype, Type[bool_], Literal['bool', 'boolean']]"  [arg-type]
    s = s.astype(object)
```

**Please complete the following information:**
 - OS: `Ubuntu 20.04.5`, `uname -a` yields: `Linux REDACTED 5.14.0-1058-oem #66-Ubuntu SMP Fri Feb 10 09:46:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

 - python version = `3.9.5`
 - version of type checker: `mypy=1.0.1`
 - version of installed `pandas-stubs`: `pandas_stubs=1.5.3.230304`

**Comment by tcrasset** [comment]
Seems to be causing the issue with `DataFrame` too:

```python
import pandas as pd

df = pd.DataFrame([1, 1])
df = df.astype(object)
```

yields

`
error: Argument 1 to "astype" of "DataFrame" has incompatible type "Type[object]"; expected
"Union[Union[Union[Type[bool], BooleanDtype, Type[bool_], Literal['bool', 'boolean']], Union[Type[int], Int8Dtype, Int16Dtype, Int32Dtype, Int64Dtype, Type[signedinteger[Any]], Type[signedinteger[_8Bit]], Type[signedinteger[_16Bit]], Type[signedinteger[_32Bit]], Type[signedinteger[_64Bit]], Type[signedinteger[Any]], Type[unsignedinteger[Any]], Type[unsignedinteger[_8Bit]], Type[unsignedinteger[_16Bit]], Type[unsignedinteger[_32Bit]], Type[unsignedinteger[_64Bit]], Type[unsignedinteger[Any]], Literal['int', 'Int8', 'Int16', 'Int32', 'Int64', 'byte', 'int8', 'int16', 'int32', 'int64', 'intp', 'ubyte', 'uint8', 'uint16', 'uint32', 'uint64', 'uintp']], Union[Type[str], StringDtype, Literal['str', 'string']], Type[bytes], Union[Type[float], Float32Dtype, Float64Dtype, Type[floating[_16Bit]], Type[floating[_32Bit]], Type[floating[_64Bit]], Literal['float', 'Float32', 'Float64', 'float16', 'float32', 'float64']], Union[Type[complex], Type[complexfloating[_32Bit, _32Bit]], Type[complexfloating[_64Bit, _64Bit]], Literal['complex', 'complex64', 'complex128']], Literal['timedelta64[Y]', 'timedelta64[M]', 'timedelta64[W]', 'timedelta64[D]', 'timedelta64[h]', 'timedelta64[m]', 'timedelta64[s]', 'timedelta64[ms]', 'timedelta64[us]', 'timedelta64[μs]', 'timedelta64[ns]', 'timedelta64[ps]', 'timedelta64[fs]', 'timedelta64[as]'], Literal['datetime64[Y]', 'datetime64[M]', 'datetime64[W]', 'datetime64[D]', 'datetime64[h]', 'datetime64[m]', 'datetime64[s]', 'datetime64[ms]', 'datetime64[us]', 'datetime64[μs]', 'datetime64[ns]', 'datetime64[ps]', 'datetime64[fs]', 'datetime64[as]'], Union[CategoricalDtype, Literal['category']], ExtensionDtype], Mapping[Any, Union[ExtensionDtype, Union[str, dtype[generic], Type[str], Type[complex], Type[bool], Type[object]]]], Series[Any]]"
 [arg-type]
    df = df.astype(object)
`

but I see that `Type[object]` is present in the error message: `Mapping[Any, Union[ExtensionDtype, Union[str, dtype[generic], Type[str], Type[complex], Type[bool], Type[object]]]]`, which would indicate that

`df.astype({col: object})` should work

**Comment by Dr-Irv** [comment]
Thanks for the report.  We just introduced making `astype()` accept specific types and mapping that to different generic `Series` types.

We need to add `object` as a valid type here:
https://github.com/pandas-dev/pandas-stubs/blob/6829a993697f8c5d65b721ca1cec3980ac79e69c/pandas-stubs/core/series.pyi#L1121
and here:
https://github.com/pandas-dev/pandas-stubs/blob/6829a993697f8c5d65b721ca1cec3980ac79e69c/pandas-stubs/_typing.pyi#L194

Tagging @ramvikrams to do this and add appropriate test.

**Comment by ramvikrams** [comment]
> Thanks for the report.  We just introduced making `astype()` accept specific types and mapping that to different generic `Series` types.
> 
> We need to add `object` as a valid type here:
> https://github.com/pandas-dev/pandas-stubs/blob/6829a993697f8c5d65b721ca1cec3980ac79e69c/pandas-stubs/core/series.pyi#L1121
> and here:
> https://github.com/pandas-dev/pandas-stubs/blob/6829a993697f8c5d65b721ca1cec3980ac79e69c/pandas-stubs/_typing.pyi#L194
> 
> Tagging @ramvikrams to do this and add appropriate test.
> 


I'll do the change
