### ISSUE TITLE
mypy_nightly failing due to missing ignore

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas-stubs#568]
Did a merge from a PR, and `mypy_nightly` failed:
https://github.com/pandas-dev/pandas-stubs/actions/runs/4394778938/jobs/7696025817

I think this is a correct fix for `mypy`.

If we add a `# type: ignore[override]` for that line, then our regular tests fail.

@twoertwein Any ideas on how to handle this, or do we just have to ignore the failures in `mypy_nightly` until a new `mypy` release is done?

**Comment by twoertwein** [comment]
I think we have the following options:

1. We might get away by changing the mypy config file for the nightly run (I'll look into that later today)
2. Ignore it
3. Ignore it but run nightly only on main and not for PRs (I think there is an option for that)
4. Remove the nightly run

I wouldn't mind running the mypy nightly (and pandas nightly) workflow only on main. In case they error, there is no immediate need for action. This might be a better trade-off compared to annoying contributors with failing workflows.

**Comment by Dr-Irv** [comment]
> I wouldn't mind running the mypy nightly (and pandas nightly) workflow only on main. In case they error, there is no immediate need for action. This might be a better trade-off compared to annoying contributors with failing workflows.

That sounds like a good idea.  Then I just get the noise when I do merges of PR's.

**Comment by Dr-Irv** [comment]
Closing via #569
