### ISSUE TITLE
TST: Reference to non-existing class TimedeltaSeries and TimestampSeries

### ISSUE THREAD

**Issue by twoertwein** [pandas-dev/pandas-stubs#57]
Pandas doesn't define `TimedeltaSeries` and `TimestampSeries`:
https://github.com/pandas-dev/pandas-stubs/blob/b4db0a62efb0e7e1ca890bcd99c6ae78e1af7f19/tests/test_timefuncs.py#L12

**Comment by Dr-Irv** [comment]
Yes, but those types are defined in `pandas-stubs` and the import is surrounded by `if TYPE_CHECKING` .

The tests will only work with the stubs, not without them.
