### ISSUE TITLE
Empty Series is considered `TimestampSeries`

### ISSUE THREAD

**Issue by randolf-scholz** [pandas-dev/pandas-stubs#571]
**Describe the bug**

Instantiating an empty `Series` object creates a `TimestamptSeries`, should probably be `Series[Any]`.

**To Reproduce**

```python
from pandas import Series
baz = Series([])
reveal_type(baz)  # pandas.core.series.TimestampSeries
```

**Please complete the following information:**
- pandas                        1.5.3
- pandas-stubs                  1.5.3.230304

**Comment by Dr-Irv** [comment]
I'm not sure that this is something that can be fixed.  There is not a way for a type checker to differentiate between an empty list that has no type information, and a list/sequence containing specific types.

**Comment by randolf-scholz** [comment]
@Dr-Irv  Right, but then it should fall back to the most general type `Series[Any]` instead of a highly specialized type `TimestampSeries`.

I think one could fix this by carefully changing the order of the overloads. The problem is that [the first overload of `Series.__new__`](https://github.com/pandas-dev/pandas-stubs/blob/main/pandas-stubs/core/series.pyi) already matches an empty Series. If I read https://mypy.readthedocs.io/en/stable/more_types.html#type-checking-calls-to-overloads correctly, then if the first overload was e.g. of the form `data: Sequence[Scalar] -> Series[Scalar]`, then mypy would correctly impute `Any`.

**Comment by Dr-Irv** [comment]
> I think one could fix this by carefully changing the order of the overloads. The problem is that [the first overload of `Series.__new__`](https://github.com/pandas-dev/pandas-stubs/blob/main/pandas-stubs/core/series.pyi) matches an empty Series and returns `TimestampSeries`. If I read https://mypy.readthedocs.io/en/stable/more_types.html#type-checking-calls-to-overloads correctly, then if the first overload was e.g. of the form `data: Sequence[Scalar] -> Series[Scalar]`, then mypy would correctly impute `Any`.

The problem with that solution is that we want to have a `Sequence[Timestamp]` match to create `TimestampSeries`, (and similar with the `Timedelta` related types), so we have to use a proper subset of `S1` that doesn't include the other types we want to match inside of sequences.

This might be possible if we split `S1` into two groups, with one group including the types that we don't want to explicitly match.  Not sure - some investigation would be required to get this right.

**Comment by randolf-scholz** [comment]
Empty Sequence can be handled by `Sequence[Never]` in pyright, currently it seems unsupported in mypy: https://github.com/python/mypy/issues/15763

So, one might have to wait for newer version of mypy.
