### ISSUE TITLE
Simplify `DataFrame.loc.__getitem__` overload

### ISSUE THREAD

**Issue by randolf-scholz** [pandas-dev/pandas-stubs#574]
**Describe the bug**

We can simplify
 
https://github.com/pandas-dev/pandas-stubs/blob/d2e3f74e20ddbaf8375e29f84cbaa8a139cf8353/pandas-stubs/core/frame.pyi#L162-L166

towards 

```python
        | tuple[
            Iterable[Hashable] | slice | Hashable,
            list[HashableT] | slice | Series[bool] | Callable,
        ],
    ) -> DataFrame: ...
```

**Please complete the following information:**
- pandas 1.5.3
- pandas-stubs 1.5.3.230304

**Comment by Dr-Irv** [comment]
As discussed here:  https://github.com/pandas-dev/pandas-stubs/pull/575#discussion_r1135747714 ,  `Iterable[Hashable]` is too wide

**Comment by randolf-scholz** [comment]
Matching str is fine here, because the second component of the tuple ensures multiple columns are selected.

Both df.loc["row", ["col1", "col2", "col3"]] and df.loc[["r", "o", "w"], ["col1", "col2", "col3"]] return DataFrame which is the only thing this overload ensures.
