### ISSUE TITLE
pd.array().tolist() is not recognized

### ISSUE THREAD

**Issue by andsav** [pandas-dev/pandas-stubs#583]
**Describe the bug**

`.tolist()` is not recognized as a method for a pandas array. You can compare with generating the stubs using `stubgen -p pandas` which does provide it in `core/arrays/base.pyi`:

```
class ExtensionArray:
  ....
  def tolist(self) -> list: ...
``` 

Should pandas-stub support this? Could be something wrong with my typechecker, but I don't see `tolist` in the corresponding pandas-stubs' pyi.

**To Reproduce**

```
import pandas as pd
return pd.array([1,2,3]).tolist()
```

<img width="562" alt="image" src="https://user-images.githubusercontent.com/5506087/225753388-c9095a34-521f-400d-a24c-ebcefb4b123d.png">

**Please complete the following information:**
 - python version: 3.10.8
 - version of type checker: [fork of pyright](https://github.com/microbit-foundation/pyright). Should be compatible with pyright 1.1.279
 - version of installed `pandas-stubs`: 1.5.3.230304

**Comment by Dr-Irv** [comment]
Need to add `tolist()` to `pandas-stubs\core\arrays\base.pyi` , with appropriate test.  PR welcome.
