### ISSUE TITLE
`Series[bool].sum()` incorrectly returns `bool` instead of `int`

### ISSUE THREAD

**Issue by Azureblade3808** [pandas-dev/pandas-stubs#595]
**Describe the bug**
As the title.

**To Reproduce**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.
```python
from pandas import Series
from typing_extensions import assert_type

series = assert_type(Series([False, True] * 5, dtype=bool), "Series[bool]")
sum = assert_type(series.sum(), int)  # Fails.
assert sum == 5
```

2. Indicate which type checker you are using (`mypy` or  `pyright`).
pyright

4. Show the error message received from that type checker while checking your example.
![image](https://user-images.githubusercontent.com/15389744/228457232-6d74eb93-7095-412b-9c0d-ff6ad2d067ad.png)

**Please complete the following information:**
 - OS: Windows
 - OS Version: 10
 - python version: 3.10.10
 - version of type checker: Pyright v1.1.300 (bundled in Pylance v2023.3.31)
 - version of installed `pandas-stubs`: 1.5.3.230321

**Additional context**
None.

**Comment by Dr-Irv** [comment]
Thanks for the report.  This will be a challenge to fix.  The following will **NOT** work:
```python
 @overload
    def sum(
        self: Series[bool],
        axis: AxisIndex | None = ...,
        skipna: _bool | None = ...,
        level: None = ...,
        numeric_only: _bool = ...,
        min_count: int = ...,
        **kwargs,
    ) -> int: ...
    @overload
    def sum(
        self: Series[S1],
        axis: AxisIndex | None = ...,
        skipna: _bool | None = ...,
        level: None = ...,
        numeric_only: _bool = ...,
        min_count: int = ...,
        **kwargs,
    ) -> S1: ...
```
One thing to try would be to split up the various values for `S1` and specify the result for each of those values, and have a specific match for `Series[Any]` (as the first match) that would return `float` (since most series that don't specify `dtype` would be `float`).

Another possibility would be to create a `BoolSeries` type (similar to `TimestampSeries`), replace `Series[bool]` throughout with `BoolSeries`, and then just create `sum()` for `BoolSeries`.  This might be the easiest solution.

**Comment by twoertwein** [comment]
> The following will **NOT** work:

It would only trigger an overlapping overload when checking pandas-stubs itself - not for user-code?

**Comment by Dr-Irv** [comment]
> It would only trigger an overlapping overload when checking pandas-stubs itself - not for user-code?
> 
> (but it might have some weird interactions if S1 is unknown.)

That's the issue.  If you had `s = pd.Series([1.3, 2.4])`, then the type checker sees `s` as `Series[Unknown]` and it matches `Series[bool]`.

**Comment by Azureblade3808** [comment]
Will this fit in?
```python
from typing_extensions import Never

    @overload
    def sum(
        self: Series[Never],
        axis: AxisIndex | None = ...,
        skipna: _bool | None = ...,
        level: None = ...,
        numeric_only: _bool = ...,
        min_count: int = ...,
        **kwargs,
    ) -> Any: ...
    @overload
    def sum(
        self: Series[bool],
        axis: AxisIndex | None = ...,
        skipna: _bool | None = ...,
        level: None = ...,
        numeric_only: _bool = ...,
        min_count: int = ...,
        **kwargs,
    ) -> int: ...
    @overload
    def sum(
        self: Series[S1],
        axis: AxisIndex | None = ...,
        skipna: _bool | None = ...,
        level: None = ...,
        numeric_only: _bool = ...,
        min_count: int = ...,
        **kwargs,
    ) -> S1: ...
```
Aside from overlapping overloads, it seems to work for both pyright and mypy. Looks a bit hacky though.
