### ISSUE TITLE
"apply" of "Series" does not accept returns of an object of type set[Any]

### ISSUE THREAD

**Issue by JasonMendoza2008** [pandas-dev/pandas-stubs#598]
**Describe the bug**
"apply" of "Series" does not accept returns of an object of type set[Any]

**To Reproduce**
**1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.**
```py
import pandas as pd

data = {'list1': [1, 2, 3], 'list2': ['a', 'b', 'c'], 'list3': [True, False, True]}
series_of_lists: pd.Series = pd.Series(data)

series_of_lists = series_of_lists.apply(lambda x: set(x))
```
**2. Indicate which type checker you are using (`mypy` or  `pyright`).**
I'm using `mypy 1.1.1`
**3. Show the error message received from that type checker while checking your example.**
```py
6: error: Argument 1 to "apply" of "Series" has incompatible type "Callable[[Any], Set[Any]]"; expected "Callable[..., Union[str, bytes, date, timedelta, datetime64, timedelta64, int, float, complex, Sequence[Any], Mapping[Any, Any]]]"  [arg-type]
6: error: Incompatible return value type (got "Set[Any]", expected "Union[str, bytes, date, timedelta, datetime64, timedelta64, int, float, complex, Sequence[Any], Mapping[Any, Any]]")  [return-value]
```

**Please complete the following information:**
 - OS: Windows
 - OS Version 11
 - python version 3.11.1
 - version of type checker: `mypy 1.1.1`
 - version of installed `pandas-stubs` `pandas-stubs 1.5.3.230321`

**Additional context**
It seems that mypy is still not satisfied with the lambda function used in the apply method, as it expects the return value to be one of the types listed in the error message. But when I print type(series_of_lists[0]), I do get <class 'set'>.

**Comment by Dr-Irv** [comment]
Need to add `Set` here:
https://github.com/pandas-dev/pandas-stubs/blob/e3d9a1f69f481015c47b5716e7cfefcdffd9d63b/pandas-stubs/core/series.pyi#L764

PR welcome.

**Comment by Dr-Irv** [comment]
> For tests, you use `from typing_extensions import assert_type`, what is `assert_type`, it checks if the types are coherent with the stubs?

It tells the type checker to verify that the type we expect is the type that the type checker infers.  At runtime, it just returns the first argument. 

See https://docs.python.org/3/library/typing.html#functions-and-decorators

**Comment by JasonMendoza2008** [comment]
The test I would've wanted to do is the following:
```py
def test_types_apply_set() -> None:
    series_of_lists: pd.Series = pd.Series(
        {
            'list1': [1, 2, 3],
            'list2': ['a', 'b', 'c'],
            'list3': [True, False, True]
        }
    )
    check(assert_type(series_of_lists.apply(lambda x: set(x)), pd.Series), pd.Series)
```

But it obviously already works because apply can use the `lambda x: set(x)` function.

**Comment by Dr-Irv** [comment]
> But it obviously already works because apply can use the `lambda x: set(x)` function.

Does the test pass with `pyright` and `mypy` ?  I would think that both of those would fail without changing the stubs.  

Our tests are valid runtime code, but we also run the tests through the type checkers.  See https://github.com/pandas-dev/pandas-stubs/blob/main/docs/setup.md for setting up your environment, and https://github.com/pandas-dev/pandas-stubs/blob/main/docs/tests.md to see how to run specific tests.

**Comment by JasonMendoza2008** [comment]
My bad, I just realized what I was running wrong, sorry. PR should be coming in a bit.
