### ISSUE TITLE
timedelta_range or interval_range should accept Timedelta or timedelta as freq

### ISSUE THREAD

**Issue by bemoody** [pandas-dev/pandas-stubs#600]
**Describe the bug**
The `timedelta_range` and `interval_range` functions should accept a `pandas.Timedelta` or `datetime.timedelta` object as the `freq` argument.

**To Reproduce**
Example:
```
import pandas

def foo(step: float):
    return pandas.timedelta_range(
        start=pandas.Timedelta(0),
        periods=10,
        freq=pandas.Timedelta(seconds=step),
    )
```

Using `mypy foo.py`:
```
foo.py:7: error: Argument "freq" to "timedelta_range" has incompatible type "Timedelta"; expected "Union[str, DateOffset, None]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

**Please complete the following information:**
 - OS: Debian 11.6
 - Python: 3.9.2
 - mypy: 1.1.1
 - pandas: 1.5.3
 - pandas-stubs: 1.5.3.230321

**Additional context**
https://github.com/pandas-dev/pandas-stubs/issues/223 mentions `date_range` and `bdate_range`.

https://github.com/pandas-dev/pandas/pull/48631 updates the documentation for `date_range`, `bdate_range`, and `interval_range`.

https://github.com/pandas-dev/pandas-stubs/pull/322 updates the stubs for `date_range` and `bdate_range`.

However, using `Timedelta` or `timedelta` with `timedelta_range` seems to work as well.  (I'm not sure I fully understand the difference between Timedelta and DateOffset, but I don't see why a Timedelta *shouldn't* be accepted here.)

**Comment by Dr-Irv** [comment]
We generally follow a policy that the stubs follow what is documented for pandas.

So before we change the stubs, we should get agreement from the pandas maintainers that `Timedelta` and `timedelta` are supposed to be allowed with `timedelta_range()` and `interval_range()`.  Can you open a doc issue in the pandas project there and cross-reference to here, so we can track that?

**Comment by bemoody** [comment]
The documentation has now been updated (thanks to @allisonkwan for the quick response.)

**Comment by Dr-Irv** [comment]
> The documentation has now been updated (thanks to @allisonkwan for the quick response.)

Great.  Now someone can do a PR to update the stubs here for `date_range()`, `interval_range()`, `bdate_range()`, and `timedelta_range()`, with appropriate tests.
