### ISSUE TITLE
`DeprecationWarning` regarding the use of `LegacyVersion`

### ISSUE THREAD

**Issue by jtilahun** [pandas-dev/pandas-stubs#612]
**Describe the bug**
The below `DeprecationWarning` appears since installing `pandas-stubs`:
```
07:59:41.56 [WARN] /home/jtilahun/.cache/pants/setup/bootstrap-Linux-x86_64/2.15.0_py38/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/specifiers.py:255: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
```

**To Reproduce**
1. Install `pandas-stubs` via `pip` by running `pip install pandas-stubs` from within the virtual environment.
2. Run a Python test. Using the Pants build system, this can be done as shown below:
```
$ ./pants test ops/utils/rpc_utils_test.py
07:59:41.56 [WARN] /home/jtilahun/.cache/pants/setup/bootstrap-Linux-x86_64/2.15.0_py38/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/specifiers.py:255: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(

07:59:47.18 [INFO] Completed: Run Pytest - ops/utils/rpc_utils_test.py:tests - succeeded.
Partition: ops_unit_tests

✓ ops/utils/rpc_utils_test.py:tests succeeded in 5.38s.

Wrote test reports to dist/test_results
```

**Please complete the following information:**
 - OS: Linux
 - OS Version Ubuntu 20.04
 - python version `3.8.10`
 - version of type checker `pyright 1.1.295`
 - version of installed `pandas-stubs` `pandas-stubs 1.5.3.230321`

**Additional context**
I never saw this warning prior to installing `pandas-stubs`, but this warning shows up constantly now. It's difficult to trace the contents of the warning message directly to `pandas-stubs` though.

**Comment by Dr-Irv** [comment]
We'd need a simple test case in order to replicate.

Looking at where the warning comes from, it might be due to how we specify the dependencies of `pandas-stubs`  and how that specification interacts with `pants`.  But in order to investigate, we'd have to be able to replicate this.

**Comment by twoertwein** [comment]
You could probably run `python -Werror ....` to get a trace of where the warning is coming from.

**Comment by jtilahun** [comment]
Hmm, there was actually a typo in `requirements.txt`. Changing
```
pandas-stubs>=1.5.3<2.0.0
```
to
```
pandas-stubs>=1.5.3,<2.0.0
```
in `requirements.txt` and regenerating constraints appears to make the warning go away. Having said this, I'm unsure of how a typo in `requirements.txt` leads to a `DeprecationWarning` of all things. The constraints generation did not complain when the typo was present, which confuses me. Is there an actual deprecation present somewhere or is this a misleading warning? If there is an actual deprecation, the deprecation should still be addressed. However, if there are actually no deprecations, I guess that this may be simply be a case of a warning being misleading.

**Comment by Dr-Irv** [comment]
Based on this issue in `pants` https://github.com/pantsbuild/pants/issues/17848, I think this is what happened.  Nothing to do with `pandas-stubs`.  Closing
