### ISSUE TITLE
Repository tags and releases do not reflect PyPi versions

### ISSUE THREAD

**Issue by aholmes** [pandas-dev/pandas-stubs#63]
Hi,
This is a duplicate of https://github.com/VirtusLab/pandas-stubs/issues/53. Opening here because the repository moved.

> I updated pandas-stubs from 1.1.0.7 to 1.1.0.11 and wanted to see what specifically changed. I came here hoping to see a tag or release, but cannot find either. It would really help with discoverability and usage efforts if the repository tag versions (at minimum, releases would be nice too) reflected release versions on PyPi/vice versa.

**Comment by BrenoJesusFernandes** [comment]
The CI/CD update is gonna fix this. Soon we are going to release it.

**Comment by Dr-Irv** [comment]
I did a tag for release 1.4.3.220702, and will do tags going forward, or we'll get them done automatically.  Thanks for the suggestion.
