### ISSUE TITLE
pd.concat: overload for keys=[dict].keys()

### ISSUE THREAD

**Issue by fostermaier** [pandas-dev/pandas-stubs#633]
While there is an overload to pass dictionary values as parameter to `pd.concat(dict.values())` this is not possible for the `pd.concat(..., keys=dict.keys())` kwarg.

**To Reproduce**

    pd.concat(mydict.values(), axis=1, keys=mydict.keys())

results in

    $ mypy
    error: No overload variant of "concat" matches argument types "dict_values[str, DataFrame]", "int", "dict_keys[str, DataFrame]"  [call-overload]
    note: Possible overload variants:
    [...]

in contrast, `mypy` does not complain about `pd.concat(mydict.values(), axis=1)` so this issue targets the `keys` kwarg.

**Current Workaround**

Cast the dictionary keys to list as

    pd.concat(mydict.values(), axis=1, keys=list(mydict.keys()))
  

**Environment**
 - OS: Linux
 - OS Version: 5.15
 - Python 3.11.2
 - mypy 1.0.1
 - pandas-stubs==1.5.3.230321

**Comment by Dr-Irv** [comment]
@fostermaier  Can you provide a more complete example that will also run?

**Comment by fostermaier** [comment]
here you go

    import pandas as pd
    
    col_pairs = {
        'foo': pd.DataFrame([[42, 'a'], [43, 'b']], columns=['x', 'y']),
        'bar': pd.DataFrame([[4.2, 'A'], [4.3, 'B']], columns=['x', 'y']),
    }
    
    # this raises a mypy error
    # error: No overload variant of "concat" matches argument types
    # "Dict[str, DataFrame]", "int", "dict_keys[str, DataFrame]"
    df_err = pd.concat(col_pairs, axis=1, keys=col_pairs.keys())
    
    # this runs fine
    df_ok = pd.concat(col_pairs, axis=1, keys=list(col_pairs.keys()))
    
    print(df_err.equals(df_ok))

While pandas is totally fine with `dict_keys` as `keys=`, the stubs request a list
https://github.com/pandas-dev/pandas-stubs/blob/24288ee6f919e8c971a29832415b69c3c8b1ae93/pandas-stubs/core/reshape/concat.pyi#L32

**Comment by Dr-Irv** [comment]
Thanks for the example.

Need to change that to `Iterable[HashableT2]` .  PR with tests welcome.
