### ISSUE TITLE
`DataFrame.sample` output is typed as `Series`

### ISSUE THREAD

**Issue by Bonnevie** [pandas-dev/pandas-stubs#67]
`DataFrame.sample` generally returns a `DataFrame` object with a subsample of the original's rows, but mypy is complaining saying that the output is a `Series`.  From what I can tell, it is also typed as `Series[S1]` in the stubs code: https://github.com/pandas-dev/pandas-stubs/blob/7a5d7a81e0ecc37a494068aedfff3df12330fc73/pandas-stubs/core/frame.pyi#L1800

Is this a bug, or is it the intended type and I'm missing a step?

**Comment by Dr-Irv** [comment]
It's a bug in the stubs.  PR is welcome
