### ISSUE TITLE
`__getitem__` returns `Dataframe` type; expected `Series`

### ISSUE THREAD

**Issue by taoufik07** [pandas-dev/pandas-stubs#671]
**Describe the bug**
Starting with `v2.0.1.230501`, accessing e.g. a column in a dataframe returns a `Dataframe` type while expecting a `Series`.

**To Reproduce**

```python
import pandas as pd

def func1(df: pd.Series[float]) -> pd.Series[float]:
    return df[0]

def func2(df: pd.DataFrame) -> pd.Series[float]:
    reveal_type(df[0])
    return func1(df[0])

func2(pd.DataFrame({"test": ["b", "b", "a", "c", "b"]}))
```

`mypy` returns

```python
note: In function "func2":
note: Revealed type is "pandas.core.frame.DataFrame"
error: Argument 1 to "func1" has incompatible type "DataFrame"; expected "Series[float]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

**Please complete the following information:**
 - OS: [e.g. Windows, Linux, MacOS] MacOS
 - OS Version [e.g. 22] 
 - python version: 3.10.7
 - version of type checker: 1.2.0
 - version of installed `pandas-stubs`: v2.0.1.230501

**Additional context**

**Comment by taoufik07** [comment]
I bet this was due to https://github.com/pandas-dev/pandas-stubs/commit/ca274467daa8c1a50b1ac0fcbce8a24c9ca3b577, as `npt.NDArray[X]` reveals an `Any` which matches any passed key

**Comment by taoufik07** [comment]
Apologies, I think I forgot to enable the numpy typing plugin 😓

**Comment by Dr-Irv** [comment]
> Apologies, I think I forgot to enable the numpy typing plugin 😓

Actually, it may have been the version of numpy that you were using, and enabling the plugin may have upgraded your numpy.

Nevertheless, I had to change your code to make it pass:
```python
import pandas as pd

def func1(df: pd.Series[float]) -> float:
    return df[0]

def func2(df: pd.DataFrame) -> float:
    reveal_type(df[0])
    return func1(df[0])

func2(pd.DataFrame({"test": ["b", "b", "a", "c", "b"]}))
```
