### ISSUE TITLE
`read_sql_*` methods should accept `dtype` argument with same type as `DataFrame.astype()`

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas-stubs#676]
For the `read_sql_*` methods, the argument `dtype` is just passed to `DataFrame.astype()`, where we allow `dtype: AstypeArg | Mapping[Any, Dtype] | Series`, so the `read_sql_*()` methods should do the same.

In particular, doing something like `dtype: {"col": "str"}` is totally allowed, but not permitted in the stubs.

pandas-stubs version 2.0.1.230501

**Comment by Dr-Irv** [comment]
@ramvikrams can you fix this?  You added the argument before, so maybe you can do this?

**Comment by ramvikrams** [comment]
Thank you  @Dr-Irv I will surely do it

**Comment by Dr-Irv** [comment]
The solution here is actually simpler than I thought.  Try changing https://github.com/pandas-dev/pandas-stubs/blob/6c0eed6b58790414d9e991a1d621a4bd313cfd40/pandas-stubs/_typing.pyi#L79 to use `Mapping` instead of `dict`, and then just add a test that has a string in the value of the dict.
