### ISSUE TITLE
Argument 1 to "apply" of "Series" has incompatible type "Callable[[Any], Union[int, NAType]]"

### ISSUE THREAD

**Issue by bersbersbers** [pandas-dev/pandas-stubs#681]
**To Reproduce**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.
```python
import pandas as pd

# these values are allowed
allowed = ["A", "B", "C"]

df = pd.DataFrame()

# we add a few that are not allowed
df["Column"] = ["A", "B", "C", "D"]

# replace values by index, and NA if not allowed
df["Label"] = df.Column.apply(lambda x: allowed.index(x) if x in allowed else pd.NA)

print(df.Label)
```

2. Indicate which type checker you are using (`mypy` or  `pyright`).
`mypy 1.2.0 (compiled: yes)`

3. Show the error message received from that type checker while checking your example.
```
bug.py:12: error: Argument 1 to "apply" of "Series" has incompatible type "Callable[[Any], Union[int, NAType]]"; expected "Callable[..., Union[str, bytes, date, datetime, timedelta, datetime64, timedelta64, bool, int, float, Timestamp, Timedelta, integer[Any], floating[Any], complex, Sequence[Any], Set[Any], Mapping[Any, Any]]]"  [arg-type]
bug.py:12: error: Incompatible return value type (got "Union[int, NAType]", expected "Union[str, bytes, date, datetime, timedelta, datetime64, timedelta64, bool, int, float, Timestamp, Timedelta, integer[Any], floating[Any], complex, Sequence[Any], Set[Any], Mapping[Any, Any]]")  [return-value]
Found 2 errors in 1 file (checked 1 source file)
```

**Please complete the following information:**
 - OS: Windows 11
 - OS Version: 22H2
 - python version: 3.10.11
 - version of type checker: 1.2.0
 - version of installed `pandas-stubs`: 2.0.1.230501

Related: #262?

**Comment by twoertwein** [comment]
Probably need to add NAType here https://github.com/pandas-dev/pandas-stubs/blob/6c0eed6b58790414d9e991a1d621a4bd313cfd40/pandas-stubs/core/series.pyi#L784 or even to Scalar / S1.

**Comment by Dr-Irv** [comment]
> Probably need to add NAType here

Correct
> 
> https://github.com/pandas-dev/pandas-stubs/blob/6c0eed6b58790414d9e991a1d621a4bd313cfd40/pandas-stubs/core/series.pyi#L784
> 
> or even to Scalar / S1.

I'm wary (as I wrote https://github.com/pandas-dev/pandas-stubs/issues/262#issuecomment-1236456366) of doing the latter because it may make some of our existing declarations too wide.

So better to make the change as suggested above to handle this case.
