### ISSUE TITLE
from `pandas.api.types` import `is_numeric_dtype` is not recognized

### ISSUE THREAD

**Issue by DLI1996** [pandas-dev/pandas-stubs#689]
**Describe the bug**
when running `mypy {file_name}.py`, it gives the following error: 

  File "mypy/main.py", line 95, in main
  File "mypy/main.py", line 174, in run_build
  File "mypy/build.py", line 194, in build
  File "mypy/build.py", line 277, in _build
  File "mypy/build.py", line 2930, in dispatch
  File "mypy/build.py", line 3321, in process_graph
  File "mypy/build.py", line 3402, in process_fresh_modules
  File "mypy/build.py", line 2121, in fix_cross_refs
  File "mypy/fixup.py", line 53, in fixup_module
  File "mypy/fixup.py", line 122, in visit_symbol_table
  File "mypy/lookup.py", line 49, in lookup_fully_qualified
AssertionError: Cannot find component '_libs' for 'pandas._libs.interval.Interval' 

**To Reproduce**
```
import logging
import pandas as pd
from pandas.api.types import is_numeric_dtype

logger = logging.getLogger(__name__)

def multiply(data:pd.DataFrame, feature_name:str, paired_col_names:list) -> pd.DataFrame:
    """multiply specified columns and append to data as features
    Args:
        data: data to be enriched
        feature_name: name of the new feature
        paired_col_names: two columns to be multiplied
    Returns:
        data: enriched data
    """
    first_col_name, second_col_name = paired_col_names
    # note that 
    if not is_numeric_dtype(data[first_col_name]) or not is_numeric_dtype(data[second_col_name]):
        warnings.warn('Multiplying non-numeric columns: {} and {}'.format(first_col_name, second_col_name), UserWarning)
        logger.warning('first_col_name type: %s, second_col_name type: %s', data[first_col_name].dtype, data[second_col_name].dtype)
    data[feature_name] = data[first_col_name].multiply(data[second_col_name])
    logger.info('multiply completed')
    return data
```

**Please complete the following information:**
 - OS: Windows (WSL)
 - OS Version: Windows 11, Ubuntu default
 - python version: 3.10.9
 - version of type checker: mypy==1.2.0
 - version of pandas: pandas==1.5.3; pandas-stubs==2.0.1.230501

**Additional context**

**Comment by Dr-Irv** [comment]
I think this is a `mypy` issue.  

First, you need to add `import warnings` to your code.
Second, can you run it as `mypy --no-incremental yourfile.py` ?  I've seen the kind of error you are showing when the cache for mypy gets messed up.

**Comment by twoertwein** [comment]
I tested your code snippet - it works with the latest version of pandas-stubs (with both mypy and pyright). 

Feel free to re-open the issue if you still have it after upgrading pandas-stubs and mypy.
