### ISSUE TITLE
DataFrame.interpolate method return type does not honor default inplace argument

### ISSUE THREAD

**Issue by jbiz25** [pandas-dev/pandas-stubs#691]
Using pandas-stubs-2.0.1.230501.

inplace defaults to False, so the below shoudl return a new DataFrame.  But pyright thinks the return type is DataFrame | None. Here is some code showing the problem:

import pandas as pd
df: pd.DataFrame = -pd.DataFrame()
df = df.interpolate(method="linear")   # pyright reports the below message for this line

Expression of type "DataFrame | None" cannot be assigned to declared type "DataFrame"
  Type "DataFrame | None" cannot be assigned to type "DataFrame"
    Type "None" cannot be assigned to type "DataFrame"

But if I repalce the line with the below, then pyright is happy:

df = df.interpolate(method="linear", inplace=False)

**Comment by Dr-Irv** [comment]
Thanks for the report.  I think the fix is to change
https://github.com/pandas-dev/pandas-stubs/blob/002f0cc4c8a341c5db4f50048978936d3e62c63d/pandas-stubs/core/frame.pyi#L1711
to be `Literal[False] = ...`

PR with test welcome.

**Comment by gandhis1** [comment]
FYI looks like this might also affect `GroupBy.fillna`: https://github.com/search?q=repo%3Apandas-dev%2Fpandas-stubs%20%22inplace%3A%20Literal%5BFalse%5D%2C%22&type=code

**Comment by Dr-Irv** [comment]
> FYI looks like this might also affect `GroupBy.fillna`: https://github.com/search?q=repo%3Apandas-dev%2Fpandas-stubs%20%22inplace%3A%20Literal%5BFalse%5D%2C%22&type=code

Yes, I think you're correct.  Thanks for finding that.

**Comment by twoertwein** [comment]
> FYI looks like this might also affect `GroupBy.fillna`: https://github.com/search?q=repo%3Apandas-dev%2Fpandas-stubs%20%22inplace%3A%20Literal%5BFalse%5D%2C%22&type=code

[Docs say:](https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.fillna.html) `Broken. Do not set to True.` :)

**Comment by Dr-Irv** [comment]
> [Docs say:](https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.fillna.html) `Broken. Do not set to True.` :)

So we should fix the stubs to not allow the `True` value!  Probably can remove the overloads and just change `inplace` to `inplace: Literal[False] = ...` and always have it return `DataFrame`
