### ISSUE TITLE
`dtype` argument of `read_json()` should use `Mapping` not `dict`

### ISSUE THREAD

**Issue by JanEricNitschke** [pandas-dev/pandas-stubs#700]
**Describe the bug**
I am seeing a difference between the inlined type hints in pandas 2.0.1 and pandas-stubs 2.0.1.230501.
Where the latter leads to an unexpected type checker error from pyright as reported here: https://github.com/microsoft/pyright/issues/5136

Uninstalling the stubs and using the default inline hints the case passes.

**To Reproduce**
```import pandas as pd
with open("testpath", encoding="utf-8") as pre_analyzed:
    prev_dataframe = pd.read_json(pre_analyzed, dtype={"MatchID": str})
```

pyright 1.1.309 gives the following error:

```
error: Argument of type "dict[str, Type[str]]" cannot be assigned to parameter "dtype" of type "bool | dict[HashableT@read_json, DtypeArg] | None" in function "read_json"
    Type "dict[str, Type[str]]" cannot be assigned to type "bool | dict[HashableT@read_json, DtypeArg] | None"
      "dict[str, Type[str]]" is incompatible with "bool"
      "dict[str, Type[str]]" is incompatible with "dict[HashableT@read_json, DtypeArg]"
        TypeVar "_KT@dict" is invariant
          Type "str" cannot be assigned to type "HashableT@read_json"
        TypeVar "_VT@dict" is invariant
          Type "Type[str]" cannot be assigned to type "DtypeArg"
            "Type[type]" is incompatible with "Type[ExtensionDtype]"
    ... (reportGeneralTypeIssues)
```

**Please complete the following information:**
 - OS: Windows
 - Windows 10 Pro 21H2
 - python 3.11
 - pyright 1.1.309
 - pandas-stubs 2.0.1.230501

**Comment by Dr-Irv** [comment]
Need to change the argument `dtype` here (and in 3 other places in that file):

https://github.com/pandas-dev/pandas-stubs/blob/64c339b09b28ca28f32e36c47f5f002bd8968d40/pandas-stubs/io/json/_json.pyi#L32


to
```python
    dtype: bool | Mapping[HashableT, DtypeArg] | None = ...,
```

PR with tests welcome
