### ISSUE TITLE
Series.apply gives type error for function dict->pd.Dataframe

### ISSUE THREAD

**Issue by JanEricNitschke** [pandas-dev/pandas-stubs#701]
**Describe the bug**
I am getting a type checking error from pyright on  in pandas 2.0.1 with pandas-stubs 2.0.1.230501 when trying to apply a dict->pd.Dataframe function via series.apply.

**To Reproduce**
```
import pandas as pd
dataframe: pd.DataFrame = pd.DataFrame(
    {"col1": [{"subcol1": [1, 2, 3], "subcol2": ["a", "b", "c"]}]}
)
def _dict_to_df(my_dict: dict) -> pd.DataFrame:
    return pd.DataFrame(my_dict)
dataframe["col1"] = dataframe["col1"].apply(_dict_to_df)
```

Pyright gives the following error:
```
 error: Argument of type "(my_dict: dict[Unknown, Unknown]) -> DataFrame" cannot be assigned to parameter "func" of type "(...) -> Series[Unknown]" in function "apply"
    Type "(my_dict: dict[Unknown, Unknown]) -> DataFrame" cannot be assigned to type "(...) -> Series[Unknown]"
      Function return type "DataFrame" is incompatible with type "Series[Unknown]"
        "DataFrame" is incompatible with "Series[Unknown]" (reportGeneralTypeIssues)
```
**Please complete the following information:**
 - OS: Windows
 - Windows 10 Pro 21H2
 - python 3.11
 - pyright 1.1.309
 - pandas-stubs 2.0.1.230501

**Comment by Dr-Irv** [comment]
I don't think we can support this type of usage.  The result of `DataFrame.apply()` in your example at runtime is a `Series`,  We have `Series` as a generic type, where we are able to handle typical scalar types.  In your case, the contents of the `Series` is an object (and it could be any type of object, not just `DataFrame`).   So if you change the declaration of your function `def _dict_to_df(my_dict: dict) -> pd.DataFrame:` to be `def _dict_to_df(my_dict: dict) -> Any`, then you won't get a type error.

**Comment by JanEricNitschke** [comment]
Since a Series can handle any object i dont quite see why the line here: https://github.com/pandas-dev/pandas-stubs/blob/v2.0.1.230501/pandas-stubs/core/series.pyi#L778

`func: Callable[..., Scalar | Sequence | set | Mapping],`
cant just be
`func: Callable[..., object],`

especially since pyright/mypy have the return type of apply as `Series[unkown]`/`Series[Any]` anyway?

**Comment by Dr-Irv** [comment]
If you change that to `object`, it will be too broad, and will mess up a lot of the other more common usages for type checking that we have in place.

We want to differentiate the case where you have a function that returns a `Series` passed to `apply()` versus a function that returns a general object (e.g., `np.exp`)

See the tests in https://github.com/pandas-dev/pandas-stubs/blob/159b497a33a3a4a038e28baf931300c7e25ad7dc/tests/test_series.py#L439

You're welcome to create a PR that makes sure our current tests work along with your use case, but I'm not sure it will be possible.

**Comment by JanEricNitschke** [comment]
Ok, so the base issue is that there is no way for the `-> Series` version of apply to be annotated as `Any` or `object` without messing with the `-> Dataframe` version. One would basically have to add all other types people want to use into the union.

It would be easy if the was a way to specifcy (Any - Series) or do the equivalent by ordering the overloads so that they can overlap and are checked from top to bottom.

But a the moment it does not seem possible. Unfortunate, but thanks anyway.

**Comment by gandhis1** [comment]
> do the equivalent by ordering the overloads so that they can overlap and are checked from top to bottom.

I thought this was possible. You just need to ignore the overlapping errors, but the overloads would get used.

**Comment by JanEricNitschke** [comment]
it might work with that but then its actually not typesafe. Because if you type hinted the function to return `object` and it returns a Series (which is an object so that type checks). The overload would think it returns a Series when it actually returns a Dataframe.

So you really do need an `object - Series` type which does not exist.
