### ISSUE TITLE
`.rolling` should accept `Timedelta` as values.

### ISSUE THREAD

**Issue by pinealan** [pandas-dev/pandas-stubs#704]
Timedelta is not an allowed argument type on `pd.Series.rolling` nor `pd.DataFrame.rolling`, even though they are supported and [official docs](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rolling.html) states so too.

**To Reproduce**
The following was run with `mypy`
```python
import pandas as pd

idx = pd.date_range('2023-01-01', '2023-02-01')

pd.Series(range(32) index=idx).rolling(pd.Timedelta('7D')).mean()
pd.DataFrame(range(32), index=idx).rolling(pd.Timedelta('7D')).mean()
```

This will produce the error messages

> No overload variant of "rolling" of "Series" matches argument type "Timedelta"  [call-overload]
> No overload variant of "rolling" of "DataFrame" matches argument type "Timedelta"  [call-overload]

**Please complete the following information:**
 - OS: MacOS Monterey
 - OS Version: 12.5.1
 - python version: 3.10.11
 - version of type checker: mypy 1.3.0
 - version of installed `pandas-stubs`: 2.0.1.230501

**Comment by Dr-Irv** [comment]
Thanks for the report.

Need to change
https://github.com/pandas-dev/pandas-stubs/blob/70c412c84ec70fabdeb6b774b06811758b1b4b2b/pandas-stubs/core/frame.pyi#L1958
to include `pd.Timedelta`

Not just that line, but also the other overload in that file, plus overloads in `core/series.pyi`

PR plus tests welcome!
