### ISSUE TITLE
Module has no attribute "interchange"

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas-stubs#712]
**Describe the bug**

**To Reproduce**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.
2. Indicate which type checker you are using (`mypy` or  `pyright`).
3. Show the error message received from that type checker while checking your example.

```console
(.venv) marcogorelli@DESKTOP-U8OKFP3:~/tmp$ cat t.py
import pandas as pd

df = pd.DataFrame({'a': [1, 2, 3]})

res = pd.api.interchange.from_dataframe(df)
print(res)

(.venv) marcogorelli@DESKTOP-U8OKFP3:~/tmp$ mypy t.py
t.py:5: error: Module has no attribute "interchange"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
(.venv) marcogorelli@DESKTOP-U8OKFP3:~/tmp$ pip freeze | grep pandas
pandas==2.0.1
pandas-stubs==2.0.1.230501
(.venv) marcogorelli@DESKTOP-U8OKFP3:~/tmp$ pip freeze | grep mypy
mypy==1.3.0
mypy-extensions==1.0.0
```

**Please complete the following information:**
 - OS: [e.g. Windows, Linux, MacOS] linux
 - OS Version [e.g. 22]
 - python version 3.10.6
 - version of type checker mypy
 - version of installed `pandas-stubs` 2.0.1.230501

**Additional context**

**Comment by Dr-Irv** [comment]
Need to add
```python
    interchange as interchange,
```
to `pandas-stubs/api/__init__.pyi`

PR with tests welcome.
