### ISSUE TITLE
Create `__iter__()` for `DatetimeIndex`

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas-stubs#723]
I also ran in to this using [`date_range`](https://pandas.pydata.org/docs/reference/api/pandas.date_range.html).

Workaround is good for now:
```py
for ts in cast(Iterator[datetime], date_range(start='1/1/2023', end='1/08/2023', freq='6H', tz=timezone.utc)):
   ....
```

_Originally posted by @davetapley in https://github.com/pandas-dev/pandas-stubs/issues/502#issuecomment-1571003583_

Should create `DatetimeIndex.__iter__()` returning `Timestamp`

**Comment by twoertwein** [comment]
Is there a reason that `IndexOpsMixin` is not generic (except for it taking quite some work)? Pandas seems to define `__iter__` on `IndexOpsMixin`. I have locally a branch that tries to make `IndexOpsMixin`  generic. If I get it to work, I will open a PR.

**Comment by twoertwein** [comment]
I created #760 - still needs some time to be ready but it is getting there. Feel free to skim it to see if something could clearly be better :)
