### ISSUE TITLE
`pd.isnull` not guarding against `None`

### ISSUE THREAD

**Issue by DavidLeber** [pandas-dev/pandas-stubs#731]
**Describe the bug**
pd.isnull should TypeGuard against None, but currently does not. 

**To Reproduce**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.
![image](https://github.com/pandas-dev/pandas-stubs/assets/87345286/1f91bca7-14cf-4efb-9640-ee07e6b70c04)
2. Indicate which type checker you are using (`mypy` or  `pyright`).
pyright
3. Show the error message received from that type checker while checking your example.
Operator "+=" not supported for types "int | None" and "Literal[1]"

**Please complete the following information:**
 - OS: Ubuntu
 - OS Version [e.g. 22]: 5.15.0-73-generic
 - python version: 3.10.8
 - version of type checker: 1.1.313
 - version of installed `pandas-stubs`: 2.0.2.230605

**Additional context**

**Comment by Dr-Irv** [comment]
I don't think we can do this because of this use case:
```python
>>> s = pd.Series([1, None, 3])
>>> pd.isnull(s)
0    False
1     True
2    False
dtype: bool
```

From the python docs:
> TypeGuard can be used to annotate the return type of a user-defined type guard function. TypeGuard only accepts a single type argument. At runtime, functions marked this way should return a boolean.

Since `pd.isnull()` can return a `Series`, a type guard can't be used.

**Comment by gandhis1** [comment]
I had discussed this issue at length here: https://github.com/python/typing/discussions/1013#discussioncomment-3961006

That thread has a lot of contextual discussion on how the type system could be updated to support this.
