### ISSUE TITLE
numpy 1.25.0 incompatible with stubs

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas-stubs#735]
Had a CI failure when we test the installed stubs and numpy 1.25.0 gets installed, where `mypy` complained.  

Needs investigation.

**Comment by twoertwein** [comment]
Poetry doesn't let you install numpy 1.25.0 as it requires python >=3.9 (which is incompatible since pandas-stubs is also possible with 3.8).

Using numpy 1.25.0 (on python >=3.9) triggers some new warnings:

> FAILED tests/test_io.py::test_hdfstore - DeprecationWarning: `alltrue` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `all` instead.
> FAILED tests/test_io.py::test_read_hdf_iterator - UserWarning: problems loading leaf ``/df/table``::
> FAILED tests/test_io.py::test_hdf_context_manager - UserWarning: problems loading leaf ``/df/table``::

**Comment by gandhis1** [comment]
I would have thought that a project like Numpy would support Python 3.8 until it's actual EOL in about a year. Seems odd, unless it's a Poetry thing.

**Comment by twoertwein** [comment]
> I would have thought that a project like Numpy would support Python 3.8 until it's actual EOL in about a year. Seems odd, unless it's a Poetry thing.

https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table Pandas follows Numpy's policy
