### ISSUE TITLE
DataFrameGroupBy.aggregate can return Series with argument "size", typed as only returning DataFrame

### ISSUE THREAD

**Issue by ljmc-github** [pandas-dev/pandas-stubs#736]
**Describe the bug**
See title, and following line.
https://github.com/pandas-dev/pandas-stubs/blob/6fe90bbb37128a79068ba41c8ebaaf269ddeab90/pandas-stubs/core/groupby/generic.pyi#L162

**To Reproduce**

MRE:

```py
import pandas as pd

df = pd.DataFrame(
    [[pd.NA], [pd.NA], [pd.NA]],
    index=[0, 1, 1],
)

gdf = df.groupby(level=0)

s = gdf.aggregate("size")

reveal_type(s)  # DataFrame
type(s)  # Series
```

Type checker = mypy 1.4.1

When I use `s > 1` for indexing in `loc` I get:

```py
Invalid index type "tuple[DataFrame, str]" for "_LocIndexerFrame"; expected type "Series[bool] | ndarray[Any, dtype[bool_]] | list[bool] | str | str_ | tuple[Index | Series[bool] | ndarray[Any, dtype[bool_]] | list[bool] | str | bytes | date | datetime | timedelta | datetime64 | timedelta64 | bool | int | float | Timestamp | Timedelta | complex | list[Any] | slice | tuple[str | bytes | date | datetime | timedelta | datetime64 | timedelta64 | bool | int | float | Timestamp | Timedelta | complex, ...], ...] | list[<nothing>]"  [index]
```

**Please complete the following information:**
 - MacOS 13.4.1 (22F82)
 - Python 3.10.11
 - Mypy 1.4.1
 - pandas-stubs-2.0.2.230605

**Comment by Dr-Irv** [comment]
Need to add overload when `"size"` is passed, as that returns a `Series`.  Other strings return `DataFrame`

**Comment by ljmc-github** [comment]
This should be the case for any function which reduces a Series to a scalar, no ?

**Comment by Dr-Irv** [comment]
> ```python
> df = pd.DataFrame(
>     [[pd.NA], [pd.NA], [pd.NA]],
>     index=[0, 1, 1],
> )
> 
> gdf = df.groupby(level=0)
> 
> s = gdf.aggregate("size")
> ```

In this case, you are applying the `groupby` operation on a `DataFrame`, so all reductions except `"size"` will return a `DataFrame`.  (If there are others, we can add them as well) For example, if you use `"sum"` or `"count"`, you get a `DataFrame` as the result.  If you were to use `gdf.size()`, then the stubs do show the result as a `Series[int]`.

**Comment by ljmc-github** [comment]
I have switched to `gdf.size()` yes. I’ll send PR when I get the chance.
