### ISSUE TITLE
Pandas loc incorrect type with multi-index

### ISSUE THREAD

**Issue by amgcc** [pandas-dev/pandas-stubs#750]
My previous issue was immediately closed as user-error but there I would like to better understand this behavior.  The response suggested that the return type is Series or DataFrame despite mypy is reporting it as a Series.  The suggested fix to use `cast` works but doesn't explain why mypy output is wrong.  Sorry for reposting but I see no way to reopen my original issue.  If a moderator can close this and reopen the linked issue it would be greatly appreciated.

I attempted to reveal type on df.loc["a"] and df["a"] - both reveal_type to be pd.Series but the pyi files from what limited understanding I have of them seem to suggest the return should instead be pd.Series | pd.DataFrame.

I see stub files in my site-packages in both pandas/_libs and pandas-stubs and I'm wondering how this gets resolved with the correct priority?

https://github.com/pandas-dev/pandas-stubs/issues/749

**Comment by Dr-Irv** [comment]
I reopened #749
