### ISSUE TITLE
DataFrame.__getitem__ returns wrong type for a dict_keys object

### ISSUE THREAD

**Issue by gandhis1** [pandas-dev/pandas-stubs#770]
```python
import pandas as pd

some_columns = {
    "a": 1,
    "b": 2,
}
x  = pd.DataFrame.from_dict(some_columns)
y = x[some_columns.keys()]
reveal_type(y)  # note: Revealed type is "pandas.core.series.Series[Any]"
```

`__getitem__` with a `Generator` is already annotated correctly, not clear to me why it doesn't use that overload here.

**Comment by twoertwein** [comment]
`Generator` requires a few different methods. I assume `dict.keys()` is `Hashable` and therefore the first matching overload is the `Series` overload.

Assuming `str` is the only iterable that we want to special case (@Dr-Irv), we could first have an overload for `str`, and then use `Iterable` (covers, lists, generators and dict.keys) but add an ignore comment (overlapping overloads).

There might be more places were we could first special case the exceptions, e.g., str, to then replace large list-like Unions with Iterable+ignore.
