### ISSUE TITLE
new `.map` method of `pd.DataFrame` and `mypy`

### ISSUE THREAD

**Issue by JasonMendoza2008** [pandas-dev/pandas-stubs#774]
Minimal Reproducible Example:
```py
import pandas as pd

df = pd.DataFrame([[1, 2.12], [3.356, 4.567]])
df.map(lambda x: len(str(x)))
```
Versions:
```
pandas            2.1.0
pandas-stubs      2.0.3.230814
mypy              1.5.1
```

Additional information:
 - OS: Windows
 - OS Version 11
 - python version 3.11.1

Error message:
```py
4: error: "Series[Any]" not callable  [operator]
```

**Comment by Dr-Irv** [comment]
Thanks for the report.  We have some work to do to get the stubs up to date with pandas 2.1.

In this case, need to rename `applymap` to `map` here, and add tests.

https://github.com/pandas-dev/pandas-stubs/blob/6bb12157a810cc26e034e012bff6a0ec2da191d0/pandas-stubs/core/frame.pyi#L1311
