### ISSUE TITLE
`pd.core.frame.set_index` stubbing is not accurate

### ISSUE THREAD

**Issue by stdedos** [pandas-dev/pandas-stubs#780]
https://github.com/pandas-dev/pandas-stubs/blob/b7d23a538ae2661c2cab37fcc99be3e2b6755624/pandas-stubs/core/frame.pyi#L755-L784

https://github.com/pandas-dev/pandas-stubs/pull/154 had the right idea, but then https://github.com/pandas-dev/pandas-stubs/pull/151 sorta-reverted it

Is there plans to partially revert at least these lines back to what they were?

**Comment by twoertwein** [comment]
Can you please provide an example that doesn't work for mypy/pyright?

**Comment by stdedos** [comment]
... oh. You are right 😅 

e.g., for this:

```py
"""Test `pd.set_index`."""

import pandas as pd

# Assume df is your DataFrame
data = {"Year": [2000, 2001, 2002, 2003], "Quarter": [1, 2, 3, 4], "Revenue": [200, 220, 250, 275]}
df = pd.DataFrame(data)

# Create a multi-index using Year and Quarter
df.set_index(["Year", "Quarter"], inplace=True)

# Now you can perform more complex queries
q2_revenue = df.loc[(2001, 2), "Revenue"]
print(q2_revenue)  # Output: 220


print(df)
```

my IDE complains

![image](https://github.com/pandas-dev/pandas-stubs/assets/133706/1e5909e7-0559-4ded-a79e-989be1da7d5e)

... but not mypy:

```console
$ mypy test.py
Success: no issues found in 1 source file
```

**Comment by Dr-Irv** [comment]
> my IDE complains

Do you know which type checker your IDE is using?

**Comment by stdedos** [comment]
It's PyCharm. So ... it uses a combination of "it's own stuff" and `typeshed`. Which "somehow" is hardcoded and not "auto-fetched+updated".

https://youtrack.jetbrains.com/issue/PY-63391

**Comment by Dr-Irv** [comment]
> It's PyCharm. So ... it uses a combination of "it's own stuff" and `typeshed`. Which "somehow" is hardcoded and not "auto-fetched+updated".

Note that we only test the validity of the stubs against `mypy` and `pyright`.  I believe we have heard reports that the type checker within PyCharm has errors, as compared to those other 2 type checkers.
