### ISSUE TITLE
Elements of Union of differently-types Series not detected as same type

### ISSUE THREAD

**Issue by bersbersbers** [pandas-dev/pandas-stubs#783]
**Describe the bug**
mypy, pyright and PyLance all report the same error on the below code:

```
error: Operator "+" not supported for types "str | float" and "str | float"
    Operator "+" not supported for types "str" and "float" when expected type is "object"
    Operator "+" not supported for types "float" and "str" when expected type is "object" (reportGeneralTypeIssues)
1 error, 0 warnings, 0 informations
```

**To Reproduce**

```python
from __future__ import annotations

import numpy as np
import numpy.typing as npt
import pandas as pd

def get_series() -> pd.Series[str] | pd.Series[float]:
    return pd.Series(["0", "1"])

series = get_series()
print(series[0] + series[1])

def get_array() -> npt.NDArray[np.str_] | npt.NDArray[np.float64]:
    return np.array(["0", "1"])

array = get_array()
print(array[0] + array[1])
```

Since it works fine for `np.array` and is reported by two independent type checkers, I guess the stubs can use improving.

**Please complete the following information:**
 - python version: 3.11.5
 - version of type checker: mypy 1.5.1, pyright 1.1.328
 - version of installed `pandas-stubs`: 2.0.3.230814

**Comment by Dr-Irv** [comment]
Actually, the pandas stubs are doing the right thing here, and the `numpy` stubs aren't catching the potential error.

The error report for `pyright` is:
```text
issue783.py:11:7 - error: Operator "+" not supported for types "str | float" and "str | float"
    Operator "+" not supported for types "str" and "float" when expected type is "object"
    Operator "+" not supported for types "float" and "str" when expected type is "object" (reportGeneralTypeIssues)
```

So the stubs have told you that you can't add a string and a float.

**Comment by bersbersbers** [comment]
@Dr-Irv I know I cannot add a string and a float. But I am not doing that :)

But I guess I see the problem. I have either a pure-float or a pure-string series, but extracting the two values separately, the type checkers lose the information that the two types are identical. Offloading the subtraction in a separate function might help.

`array[0]` is inferred as `Any`, so the `numpy` case is a false-negative.
