### ISSUE TITLE
Add a test for pyright development versions into the optional workflow

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas-stubs#786]
See discussion at https://github.com/microsoft/pyright/issues/6044#issuecomment-1741322364

Instructions for testing stubs against unreleased pyright:

1. Check out the latest "main" branch of https://github.com/Microsoft/pyright.
2. Make sure you're using node 16 (which is the version our build system assumes).
3. From the root directory, execute npm i to install all dependencies.
4. From the packages/pyright directory, execute npm run build.
5. To invoke the newly-built version of the pyright cli, execute node pyright/packages/pyright/index.js <command-line options>. Alternatively, you can install the newly-built version globally in your environment using npm install . -g, then invoke it using pyright.

@twoertwein do you want to see if this can be done?

**Comment by twoertwein** [comment]
I'm sure it can be done, but I don't think the added complexity and CI runtime are worth it: pyright has frequent releases and fixes all reported bugs pretty much immediately.

**Comment by Dr-Irv** [comment]
I wasn't sure either.
