### ISSUE TITLE
convert_floating argument is missing in convert_dtypes

### ISSUE THREAD

**Issue by twagner-fox** [pandas-dev/pandas-stubs#794]
**Describe the bug**

In both `NDFrame.convert_dtypes()` and `Series.convert_dtypes()`, the annotation for the `convert_floating` argument that was introduced in Pandas 1.2.0 is missing. This causes IDEs and type checkers to report an unexpected argument when using `convert_floating`.

**To Reproduce**

1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.
   ```python
   import pandas as pd

   df = pd.DataFrame()
   df = df.convert_dtypes(convert_floating=False)
   ```
2. Indicate which type checker you are using (`mypy` or  `pyright`).
   `mypy`
3. Show the error message received from that type checker while checking your example.
   ```
   temp.py:4: error: Unexpected keyword argument "convert_floating" for "convert_dtypes" of "NDFrame"; did you mean "convert_string"?  [call-arg]
   ```

**Please complete the following information:**
 - OS: Linux
 - OS Version: Ubuntu 20.04.6 LTS
 - python version: 3.10.13
 - version of type checker: 1.5.1
 - version of installed `pandas-stubs`: 1.5.3.230321

**Additional context**
I also tried using `pandas-stubs` 2.1.1.230928 intead and got the same error message with an additional hint:
```
temp.py:4: error: Unexpected keyword argument "convert_floating" for "convert_dtypes" of "NDFrame"; did you mean "convert_string"?  [call-arg]
/home/<user>/.cache/pypoetry/virtualenvs/<project>-py3.10/lib/python3.10/site-packages/pandas-stubs/core/generic.pyi:371: note: "convert_dtypes" of "NDFrame" defined here
```
We are using `pandas-stubs` versioned at `^1.5.2.0` because we have not made the switch to `pandas` 2.0 yet.

**Comment by Dr-Irv** [comment]
Thanks for the report.  Need to add the `convert_floating` argument here:
https://github.com/pandas-dev/pandas-stubs/blob/2bbc80c10d9106b84f0d23c48b9d58f0ab7cb6c1/pandas-stubs/core/generic.pyi#L373

and remove `convert_dtypes` from `core/series.pyi` and add tests

**Comment by Dr-Irv** [comment]
> We are using `pandas-stubs` versioned at `^1.5.2.0` because we have not made the switch to `pandas` 2.0 yet.

You can still use the latest `pandas-stubs`.  The advantage there is that if there are any features you are using in 1.5 that are deprecated/no longer supported in 2.x, then you'll get notified about that, which will help in the upgrading process.

The meaning of the pandas-stubs version "1.5.3.230321" is that the version on 3/21/2023 was tested against version 1.5.3 of pandas.  So the current version 2.1.1.230928 was tested with 2.1.1 and released on 9/28/2023, and we know that it is missing some 2.0 and 2.1 features.

**Comment by twagner-fox** [comment]
I will give making these fixes a shot.

> The meaning of the pandas-stubs version "1.5.3.230321" is that the version on 3/21/2023 was tested against version 1.5.3 of pandas. So the current version 2.1.1.230928 was tested with 2.1.1 and released on 9/28/2023, and we know that it is missing some 2.0 and 2.1 features.

That's how I understood it. I figured since we care most about correct typing for the pandas version we use in production, we should be using the pandas-stubs version that was tested on the pandas version we use in case newer versions of `pandas-stubs` may report errors that cannot be fixed without updating pandas. Or is there a guarantee that correctly typed code for pandas 2.* is also correctly typed for pandas 1.5.*?

**Comment by Dr-Irv** [comment]
> Or is there a guarantee that correctly typed code for pandas 2.* is also correctly typed for pandas 1.5.*?

There are nuances here.

There could be methods in 1.5, or arguments to methods in 1.5, that are changed in 2.*, and if/when we make all the correct changes to the stubs for 2.*, then that would get caught by using the 2.* stubs with 1.5.* code.

Conversely, there are things you would write for 2.* that won't work with 1.5.* (new functions, new arguments, etc.)

What I can say is that if you use the 2.* stubs with 1.5 code, then you are more future-proofing your code for future versions of pandas, but there is no guarantee that you are completely future-proof.
