### ISSUE TITLE
"Timestamp" has no attribute "as_unit" [attr-defined]

### ISSUE THREAD

**Issue by WillAyd** [pandas-dev/pandas-stubs#797]
I think we are missing the `.as_unit` method added to pd.Timestamp in 2.0

**Comment by Dr-Irv** [comment]
It's listed in the long list in #624 .  But I'll keep this open if someone wants to do a PR.  We need to add `as_unit()` to `Timestamp`, `Timedelta`, `DatetimeIndex`, `TimedeltaIndex`, and the `dt` accessors for `Series`
