### ISSUE TITLE
`read_json()` dtype should support `type[str]`

### ISSUE THREAD

**Issue by RobertCraigie** [pandas-dev/pandas-stubs#798]
**Describe the bug**

Currently the stub files for `read_json()` [only support](https://github.com/pandas-dev/pandas-stubs/blob/e7d8661c81bad6f41643cf868d4c2132cce65b7a/pandas-stubs/io/json/_json.pyi#L33) `bool | Mapping[HashableT, DtypeArg] | None` but at runtime, `dtype=str` works.

**To Reproduce**

```py
import pandas as pd

df = pd.read_json('data.jsonl', lines=True, dtype=str).fillna("")
```

Where `data.jsonl` contains

```json
{"prompt": "Translate the following English text to French: 'Hello, how are you?'", "completion": "Bonjour, comment ça va ?"}
{"prompt": "What is the capital of France?", "completion": "Paris"}
{"prompt": "Solve the following math problem: 2 + 2 = ?", "completion": "4"}
```

**Please complete the following information:**
 - OS: [e.g. Windows, Linux, MacOS] MacOS
 - OS Version [e.g. 22]
 - python version 3.9
 - version of type checker Pyright 1.1.326
 - version of installed `pandas-stubs` latest

**Additional context**

Apologies if this is incorrect, I personally have very limited `pandas` experience, I simply ran into this while porting someone elses code from an untyped codebase to a typed codebase.

**Comment by twoertwein** [comment]
Based on the [documentation](https://pandas.pydata.org/docs/reference/api/pandas.read_json.html), it has to be a bool or a dict of bools. I assume pandas interprets str as True'ish

**Comment by RobertCraigie** [comment]
Ah sorry I should've just read the docs, thanks!
