### ISSUE TITLE
Add types for `DataFrame.itertuples()` and `DataFrame.iterrows()`

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas-stubs#805]
Right now, `DataFrame.itertuples()` and `DataFrame.iterrows()` both don't have return types.

`itertuples()` can return `Iterable[tuple[Any, ...]]` in the stubs

`iterrows()` can return `Iterable[tuple[Hashable, Series]]:` in the stubs

**Comment by Dr-Irv** [comment]
> May I take this issue?

Yes, I now assigned it to you

**Comment by lebaudantoine** [comment]
Please let me know if the [PR](https://github.com/pandas-dev/pandas-stubs/pull/822) matches your requirements. 🤗
