### ISSUE TITLE
read_excel/index_col: string not accepted

### ISSUE THREAD

**Issue by clo-vis** [pandas-dev/pandas-stubs#809]
Either the documentation or the type hint for index_col in pandas.read_excel is wrong.

The documentation says a string may be used.

The type hint forbids that

Documentation:
index_col     int, **str**, list of int, default None

Type hints:
`index_col: int | Sequence[int] | None = ...,`

**Comment by Dr-Irv** [comment]
Looking internally at the pandas source, I think the docs may be wrong.  Inside of pandas, `index_col` is typed without allowing `str` as an arg type.

If you can produce an example where `read_excel()` accepts a string (and maybe a list of strings??) as an argument for `index_col`, then updates should be made to the internal pandas source and the type hints.

Conversely, if a string doesn't work as the argument, then an issue should be raised in the pandas repo.

Can you provide an appropriate test (either way)?

**Comment by clo-vis** [comment]
```python
from pandas import read_excel
print(read_excel("Book1.xlsx", usecols=["foo", "bar"]))
print(read_excel("Book1.xlsx", usecols=["foo", "bar"], index_col="bar"))
```

Output:
```
   foo  bar
0    1    2
1    3    4
     foo
bar     
2      1
4      3
```

[Book1.xlsx](https://github.com/pandas-dev/pandas-stubs/files/13264037/Book1.xlsx)
