### ISSUE TITLE
 Type "NaTType" is not hashable

### ISSUE THREAD

**Issue by randolf-scholz** [pandas-dev/pandas-stubs#827]
```python
import pandas as pd

s = {pd.NaT}
```

**Please complete the following information:**
pandas                        2.1.4
pandas-stubs                  2.1.1.230928

**Comment by twoertwein** [comment]
Need to add `def __hash__(self) -> int: ...` here https://github.com/pandas-dev/pandas-stubs/blob/a950dbd8c4fb06c1ce13bc8bbfc574c077e2c72a/pandas-stubs/_libs/tslibs/nattype.pyi#L23

and add a test
