### ISSUE TITLE
mypy complaining about is_categorical_dtype

### ISSUE THREAD

**Issue by Giatroo** [pandas-dev/pandas-stubs#833]
**Describe the bug**
I've updated `pandas-stubs` from version 2.1.1 to 2.1.4 and now `mypy` is saying that `pd.api.types.is_categorical_dtype` doesn't exist. I found out that it was being imported in version [2.1.1](https://github.com/pandas-dev/pandas-stubs/blob/v2.1.1.230928/pandas-stubs/api/types/__init__.pyi), but not anymore in version [2.1.4](https://github.com/pandas-dev/pandas-stubs/blob/v2.1.4.231218/pandas-stubs/api/types/__init__.pyi). 

**To Reproduce**
1. Run any code containing `is_categorical_dtype`
2. `mypy` will return the following error:
![image](https://github.com/pandas-dev/pandas-stubs/assets/13424358/248ff3e2-37b0-48cb-94ea-613759823248)

**Please complete the following information:**
 - OS: Linux
 - OS Version 20.04.6 LTS
 - python version 3.10.13
 - version of type checker: mypy 1.6.0 
 - version of installed `pandas-stubs`: 2.1.1

**Comment by twoertwein** [comment]
Using `is_categorical_dtype` should trigger warnings since pandas 2.1. https://pandas.pydata.org/docs/dev/whatsnew/v2.1.0.html `isinstance(obj.dtype, pd.CategoricalDtype)` is the recommended way of testing if the type is categorical.

**Comment by Giatroo** [comment]
Oh, I see. Thank you very much!
