### ISSUE TITLE
With the most recent pandas-stubs, mypy now complains about every call to itertuples()

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas-stubs#834]
With the most recent pandas-stubs, mypy now complains about every call to itertuples()
Is there a way that I'm supposed to tell the new release what my column names are?

Sample 
```python
import pandas as pd                                                                                 
                                                                                                    
df = pd.DataFrame({"a": [1, 2, 3, 4], "b": [5, 6, 7, 8]})                                           
                                                                                                    
for item in df.itertuples():                                                                        
    a = item.a                                                                                      
    b = item.b     
```

```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

foo.py:6: error: "tuple[Any, ...]" has no attribute "a"  [attr-defined]
foo.py:7: error: "tuple[Any, ...]" has no attribute "b"  [attr-defined]
Found 2 errors in 1 file (checked 1 source file)
```

_Originally posted by @j-carson in https://github.com/pandas-dev/pandas-stubs/discussions/832_

**Comment by Dr-Irv** [comment]
> With the new type mypy complains whenever it is passed to a function accepting NamedTuple :-(
> 
> ```
> error: Argument n to "foo" has incompatible type "_PandasNamedTuple"; expected "NamedTuple"  [arg-type]
> ```

@roj516 can you create a new issue and a more complete example?

**Comment by roj516** [comment]
> > With the new type mypy complains whenever it is passed to a function accepting NamedTuple :-(
> > ```
> > error: Argument n to "foo" has incompatible type "_PandasNamedTuple"; expected "NamedTuple"  [arg-type]
> > ```
> 
> @roj516 can you create a new issue and a more complete example?

[881](https://github.com/pandas-dev/pandas-stubs/issues/881)
