### ISSUE TITLE
Level parameter of DataFrame.groupby should allow Sequences

### ISSUE THREAD

**Issue by jens-diewald** [pandas-dev/pandas-stubs#836]
The level parameter of DataFrame.groupby does not except sequences, when it should. ([Corresponding Doc](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html))
This is the same as https://github.com/pandas-dev/pandas/issues/47548

**To Reproduce**
From the linked Issue above
```python
import pandas as pd
df = pd.DataFrame([[1, 2, 3, 4], [5, 6, 7, 8]], columns=['a', 'b', 'c', 'd']).set_index(['a', 'b', 'c'])

print(df.groupby(level=[0, 1]).sum())
```
**My System**
 - Windows 10
 - Python 3.11
 - MyPy 1.5.1
 - `pandas-stubs` 2.1.4.231218

**Potential Fix**
The issue linked above was fixed by changing the type of `level` from `Level | None` to `IndexLabel | None`. (https://github.com/pandas-dev/pandas/pull/47560)
I suppose, the same Fix should be applied to the groupby-Overloads in pandas-stubs/core/frame.pyi.
I am happy to create a pull request, if that helps.
But i would appreciate it, if someone more involved with this library could confirm that the proposed fix makes sense.

**Comment by Dr-Irv** [comment]
Yes, a PR is welcome, along with tests.  Would need to change the type of `level` in `groupby()` in `frame.pyi` and `series.pyi` for all the overloads.

A test like you have above should suffice, i.e., you don't need to check all the overloads, although it would be good to have a test for both `Series` and `DataFrame`.
