### ISSUE TITLE
"Expected type 'str', got 'Series | Series' instead" Warning When Accessing DataFrame Cell in Pandas

### ISSUE THREAD

**Issue by JasonMendoza2008** [pandas-dev/pandas-stubs#856]
I am working with a Pandas DataFrame in Python and encountering an issue when trying to access a specific cell value. My goal is to retrieve the city name associated with a particular row in the DataFrame.

Minimal Reproducible Example:
```
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'City': ['New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)

selected_cell: str = df.loc[1]['City']
```

When I run this code, I receive the following warning:
`Expected type 'str', got 'Series | Series' instead`

I don't think the type-hinting is wrong.

`selected_cell: str = df.loc[1, "City"]` does not work either.

I'm running on `Python 3.11.1` and `pandas 2.1.0` and `pandas-stubs 2.0.0.230412`. The type-checker is `PyCharm 2023.3.2 (Professional Edition)`.

**Comment by Dr-Irv** [comment]
Which type checker are you using?

What you want to use here is `selected_cell: str = df.loc[1, "City"]`.  That will return a scalar value

**Comment by JasonMendoza2008** [comment]
It's PyCharm checker.
`selected_cell: str = df.loc[1, "City"]` doesn't work either.

![image](https://github.com/pandas-dev/pandas-stubs/assets/56092290/9603d920-bb62-4bc5-8c1f-095855de6ad6)

**Comment by Dr-Irv** [comment]
I think that's a bug in the pycharm type checker.  I tried your code with both `pyright` and `mypy` and it works fine.

You might also considering upgrading your version of `pandas-stubs`  to see if that helps.   Last release is 2.1.4.231227

**Comment by JasonMendoza2008** [comment]
I updated `pandas-stubs` and still have the same problem. I think it's a PyCharm problem then and I should open up an issue on their end?

**Comment by Dr-Irv** [comment]
> I updated `pandas-stubs` and still have the same problem. I think it's a PyCharm problem then and I should open up an issue on their end?

Yes.  I'm going to close this as we are only supporting `pyright` and `mypy` and your example passes both type checkers.
