### ISSUE TITLE
Series apply frozenset raises error, frozenset not in enumerated Callable output types

### ISSUE THREAD

**Issue by ljmc-github** [pandas-dev/pandas-stubs#871]
**Describe the bug**
Series.apply has two overloads, the first one enumerates the possible return types of a Callable, this is missing frozenset (probably others as well).

https://github.com/pandas-dev/pandas-stubs/blob/23b35e48fb6b159d9ddab7f007ede26ae8a05564/pandas-stubs/core/series.pyi#L930-L937

**To Reproduce**

1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.

```python
import pandas as pd

s = pd.Series(["A", "B", "AB"])

s.apply(tuple)
s.apply(list)
s.apply(set)
s.apply(frozenset)
```

2. Indicate which type checker you are using (`mypy` or  `pyright`).

`mypy`

3. Show the error message received from that type checker while checking your example.

```none
series-apply.py:8: error: Argument 1 to "apply" of "Series" has incompatible type "type[frozenset[Any]]"; expected "Callable[..., str | bytes | date | datetime | timedelta | datetime64 | timedelta64 | bool | int | float | Timestamp | Timedelta | complex | Sequence[Any] | set[Any] | Mapping[Any, Any] | NAType | None]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

**Please complete the following information:**
 - OS: MacOS
 - OS Version 14.1.2 (23B92)
 - python version 3.11.4 (pyenv managed)
 - version of type checker `mypy==1.8.0`
 - version of installed `pandas-stubs==2.1.4.231227`

**Comment by ljmc-github** [comment]
PS. also happy to work on this, but I'll start with #203

**Comment by Dr-Irv** [comment]
> PS. also happy to work on this, but I'll start with #203

I think this one is easy - we just have to add `frozenset` to:
https://github.com/pandas-dev/pandas-stubs/blob/23b35e48fb6b159d9ddab7f007ede26ae8a05564/pandas-stubs/core/series.pyi#L933

And add a test.

**Comment by teshao** [comment]
Hi, I mentioned in the slack, but am I allowed to take this?

**Comment by teshao** [comment]
Hi, I mentioned in the slack, but am I allowed to take this?
