### ISSUE TITLE
Series disallows data value of NaT

### ISSUE THREAD

**Issue by mark-thm** [pandas-dev/pandas-stubs#872]
**Describe the bug**
pandas-stubs causes mypy to error on calls like `pd.Series(pd.NaT)` with an error like:
> No overload variant of "Series" matches argument types "NaTType"

**To Reproduce**
```
pd.Series(pd.NaT)
```

Using `mypy`:
> No overload variant of "Series" matches argument types "NaTType"

**Please complete the following information:**
 - OS: MacOS, Linux
 - OS Version: MacOS: 14.3.1, Linux: Ubuntu 22
 - python version: 3.11.7
 - version of type checker: mypy 1.8.0
 - version of installed `pandas-stubs`: 2.2.0.240218

**Additional context**
n/a

**Comment by Dr-Irv** [comment]
Need to add `NAType` and `NaTType` here:
https://github.com/pandas-dev/pandas-stubs/blob/82ed4f1e734082d0ae70cb4baed08c01e0383377/pandas-stubs/core/series.pyi#L321

with associated tests
