### ISSUE TITLE
DataFrame.fillna is missing argument method

### ISSUE THREAD

**Issue by mark-thm** [pandas-dev/pandas-stubs#873]
**Describe the bug**
DataFrame.fillna is missing argument method.

**To Reproduce**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.
    ```
    df = pd.DataFrame()
    df = df.fillna(method="ffill")
    ```
2. Indicate which type checker you are using (`mypy` or  `pyright`): `mypy`
3. Show the error message received from that type checker while checking your example:
    > No overload variant of "fillna" of "DataFrame" matches argument type "str"  [call-overload]

**Please complete the following information:**
 - OS: MacOS, Linux
 - OS Version: MacOS: 14.3.1, Linux: Ubuntu 22
 - python version: 3.11.7
 - version of type checker: 1.8.0
 - version of installed `pandas-stubs`: 2.2.0.240218

**Additional context**
n/a

**Comment by Dr-Irv** [comment]
The argument `method` for `DataFrame.fillna()` has been deprecated since version 2.1.  We remove deprecated methods from the stubs to encourage people to modify their code.  See  https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html
