### ISSUE TITLE
pd.concat doesn't let me mix Series and DataFrame

### ISSUE THREAD

**Issue by tvdboom** [pandas-dev/pandas-stubs#876]
**Describe the bug**
When trying to concat a Series to a DataFrame, mypy complains, but I see in the stubs that it should be possible (see image below). Am I doing something wrong?

![image](https://github.com/pandas-dev/pandas-stubs/assets/32366550/6378d57b-9df6-42dc-b2b5-67adf84a59be)

**To Reproduce**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.
 ```python
   def x() -> pd.DataFrame:
    df1 = pd.Series()
    df2 = pd.DataFrame()
    return pd.concat([df1, df2])
```
or
 ```python
   def x() -> pd.DataFrame:
    df1: pd.Series | pd.DataFrame = pd.Series()
    df2 = pd.DataFrame()
    return pd.concat([df1, df2])
```
2. Indicate which type checker you are using (`mypy` or  `pyright`).
mypy
3. Show the error message received from that type checker while checking your example.
` error: List item 0 has incompatible type "Series[Any]"; expected "DataFrame"  [list-item]`
or
`error: List item 0 has incompatible type "Series[Any] | DataFrame"; expected "DataFrame"  [list-item]`

**Please complete the following information:**
 - OS: Windows
 - OS Version: 10
 - python version: 3.11
 - version of type checker: 1.8.0
 - version of installed `pandas-stubs`:  2.2.0.240218

**Additional context**

**Comment by twoertwein** [comment]
This works on `main` https://github.com/pandas-dev/pandas-stubs/blob/02abbdb842fd51b19e2c16dd4618100e8e293486/pandas-stubs/core/reshape/concat.pyi#L73 and is also tested https://github.com/pandas-dev/pandas-stubs/blob/02abbdb842fd51b19e2c16dd4618100e8e293486/tests/test_pandas.py#L63 but is not yet released.

**Comment by tvdboom** [comment]
Not sure why `Iterable[Series | DataFRame]` doesn't work with a list of series and dataframes, but you are right, it works from `main`. Thanks. I'll wait for the release then.

**Comment by Dr-Irv** [comment]
I'm going to close this since it works on `main`
