### ISSUE TITLE
Issue with `concat` and passing a `Union` due to presence of checking for `Iterable[None]`

### ISSUE THREAD

**Issue by Dr-Irv** [pandas-dev/pandas-stubs#879]
You are right, the example doesn't work, my bad. This example does work though, and the same question still applies.

```python
data: pd.DataFrame | pd.Series = pd.Series()

pd.concat([pd.DataFrame(), data])
```

returns

```
error: List item 0 has incompatible type "DataFrame"; expected "None"  [list-item]
error: List item 1 has incompatible type "DataFrame | Series[Any]"; expected "None"  [list-item]
```

_Originally posted by @tvdboom in https://github.com/pandas-dev/pandas-stubs/discussions/878#discussioncomment-8594364_

**Comment by Dr-Irv** [comment]
The above code triggers issues with `pyright` and `mypy`.  Interestingly, if we remove the first overload for `pd.concat` that looks for `Iterable[None]`, then the above code type checks correctly.

Going to see what @twoertwein thinks - he put that in there.

**Comment by twoertwein** [comment]
I assumed you can only concat DataFrame and Series along axis=1. seems you can also do it for axis=0:

```py
>>> pd.concat([pd.DataFrame([[0, 1], [2, 3]]), pd.Series([4,5])])
   0    1
0  0  1.0
1  2  3.0
0  4  NaN
1  5  NaN
```
