### ISSUE TITLE
DatetimeIndex constructor should accept set

### ISSUE THREAD

**Issue by amgcc** [pandas-dev/pandas-stubs#882]
**Describe the bug**
Providing a `set` to the `DatetimeIndex` constructor is rejected.

**To Reproduce**
1. Provide a minimal runnable `pandas` example that is not properly checked by the stubs.

```
import pandas as pd


def main() -> None:
    s = {pd.Timestamp(2020, 1, 1), pd.Timestamp(2021, 1, 2)}
    l = [pd.Timestamp(2020, 1, 1), pd.Timestamp(2021, 1, 2)]
    idx = pd.DatetimeIndex(s)
    print(idx)

    idx2 = pd.DatetimeIndex(l)
    print(idx2)


if __name__ == '__main__':
    main()
```

2. Indicate which type checker you are using (`mypy` or  `pyright`).
**mypy**
3. Show the error message received from that type checker while checking your example.
```
dtidx_ctor.py:7: error: Argument 1 to "DatetimeIndex" has incompatible type "set[Timestamp]"; expected "ExtensionArray | ndarray[Any, Any] | Index[Any] | Series[Any] | ndarray[Any, Any] | list[Any] | tuple[Any, ...]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

**Please complete the following information:**
 - OS: [e.g. Windows, Linux, MacOS] **Linux**
 - OS Version [e.g. 22] **Fedora 7**
 - python version **3.11**
 - version of type checker **1.8**
 - version of installed `pandas-stubs` **2.1.4**

**Comment by Dr-Irv** [comment]
There's a related open issue on `pandas` about allowing sets as arguments for indexes:
https://github.com/pandas-dev/pandas/issues/55425

The problem here is that an `Index` is ordered, so providing a set doesn't allow the order to be determined.  Here's an example with `pd.Index()`.

```python
>>> pd.Index(set([1,2]))
Index([1, 2], dtype='int64')
>>> pd.Index(set([2,1]))
Index([1, 2], dtype='int64')
```

We decided for the stubs to disallow sets because the behavior for `pandas` is ambiguous.

**Comment by amgcc** [comment]
We often use `DatetimeIndex` in our application for union operations between calendars.  In this case, the ordering isn't important.  I think there is nothing "wrong" about using a set to initialize an index.  Please reconsider.

**Comment by Dr-Irv** [comment]
> We often use `DatetimeIndex` in our application for union operations between calendars. In this case, the ordering isn't important. I think there is nothing "wrong" about using a set to initialize an index. Please reconsider.

We discussed this in the pandas dev meeting and the intent is to (eventually) disallow sets with `Index` constructors.  The recommendation for your code is to listify the arguments to the constructor, e.g.,
```python
import pandas as pd


def main() -> None:
    s = {pd.Timestamp(2020, 1, 1), pd.Timestamp(2021, 1, 2)}
    l = [pd.Timestamp(2020, 1, 1), pd.Timestamp(2021, 1, 2)]
    idx = pd.DatetimeIndex(list(s))
    print(idx)

    idx2 = pd.DatetimeIndex(l)
    print(idx2)
```
