### ISSUE TITLE
In `DataFrame.select_dtypes` type values like `np.number` or `np.datetime64` should be allowed

### ISSUE THREAD

**Issue by benediktsatalia** [pandas-dev/pandas-stubs#887]
**Describe the bug**
The documentation of `DataFrame.select_dtypes` clearly states that it is allowed to use values like `np.number` or `np.datetime64` for the `include` and `exclude` parameters, but the current stubs don't allow it, they enforce `include: _str | list[_str] | None` and `exclude: _str | list[_str] | None`. This leads to typecheckers like `mypy` reporting false positives on such calls.

**To Reproduce**
If I run mypy on the following short snippet I get an error:

```python
import numpy as np
import pandas as pd

df = pd.DataFrame()
df.select_dtypes(np.number)
```

the error is:

```
min_example.py:5: error: Argument 1 to "select_dtypes" of "DataFrame" has incompatible type "type[number[Any]]"; expected "str | list[str] | None"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

**Please complete the following information:**
 - OS: Linux
 - OS Version: Arch Linux
 - python version: 3.11
 - version of type checker: mypy 1.8.0
 - version of installed `pandas-stubs`: 2.2.0.240218

**Comment by Dr-Irv** [comment]
Thanks for the report.  Definitely needs improvement on that particular stub.

Should use `AsTypeArg` from `pandas-stubs/_typing.pyi` instead of `str` PLUS add the other possible strings (e.g., `"number"`) and object types (e.g., `np.number`)  listed in the docs.

PR plus tests welcome.

**Comment by mutricyl** [comment]
I made an attempt for this issue. It is not that simple to cover all the restrictions stated in the documentation
