### ISSUE TITLE
BUG: Argument "index" to "Series" has incompatible type "Optional[Index]"; expected "Union[str, int, Series[Any], List[Any], Index]"

### ISSUE THREAD

**Issue by bashtage** [pandas-dev/pandas-stubs#90]
**Describe the bug**
`Series` index constructor can accept `None`

**To Reproduce**
```python
from __future__ import annotations

import pandas as pd

def f(idx: pd.Index | None) -> pd.Series:
    return pd.Series([1,2,3],index=idx)
```
error is

```
error: Argument "index" to "Series" has incompatible type "Optional[Index]"; expected "Union[str, int, Series[Any], List[Any], Index]"
```

**Please complete the following information:**
 - Windows
 - 11
 - 3.9
 - mypy 0.961
 - 1.4.3.220704

**Comment by Dr-Irv** [comment]
PR welcome to change 
https://github.com/pandas-dev/pandas-stubs/blob/64582ae4b9f377fe5be9b5002df04a6ce710445a/pandas-stubs/core/series.pyi#L165
to be `Optional`
