### ISSUE TITLE
concat still reports unreachable for Iterator[None|Any] corner case

### ISSUE THREAD

**Issue by lgonzalez-silen** [pandas-dev/pandas-stubs#902]
**Describe the bug**
A follow-up to #888. Some concat calls still report unreachables in VS Code/Pylance. See below.

**To Reproduce**

```python
import pandas as pd


# no param
def foo():
    return pd.DataFrame()


df_acc = None
df_new = foo()
pd.concat([df_acc, df_new])
print("reachable")


# the param makes the second concat call unreachable if return stored
def foo2(df):
    return pd.DataFrame()


pd.concat([df_acc, foo2()])  # direct use works
print("reachable")

# the param makes the second concat call unreachable
df_new = foo2()
pd.concat([df_acc, df_new])  # var use breaks
print("unreachable")
```

**Please complete the following information:**
 - OS: MacOS
 - OS Version 14.3.1
 - python version 3.11.7
 - Pylance v2024.4.1

**Comment by lgonzalez-silen** [comment]
The actual code is more complex, with the parameter actually being used. Let me see if I can come up with a more relevant example.

**Comment by lgonzalez-silen** [comment]
@Dr-Irv updated. no misuse of the sig any longer.

**Comment by lgonzalez-silen** [comment]
Oh sorry a different problem. Let me keep working on it.

**Comment by lgonzalez-silen** [comment]
Ok. I simplified the example. I think it might be the destructuring that's the issue. The code now runs fine, but Pylance marks it unreachable. Understood that if I type the return `list[pd.DataFrame | None]` for the function, then no issues, but none of the code in my project is typed. Also, the actual function in my code can never return None.

**Comment by Dr-Irv** [comment]
> Ok. I simplified the example. I think it might be the destructuring that's the issue. The code now runs fine, but Pylance marks it unreachable. Understood that if I type the return `list[pd.DataFrame | None]` for the function, then no issues, but none of the code in my project is typed. Also, the actual function in my code can never return None. cc @Dr-Irv

Not much we can do here.  pylance is doing an analysis based on the stubs and inference of types that you haven't declared.  It could be that their inference is incorrect.  You're better off introducing types into your code so that pylance doesn't mark the code as unreachable.

I also put in your new example, and I'm not seeing the unreachable conclusion.

**Comment by lgonzalez-silen** [comment]
Mirroring my code more closely (the accumulator var starts as None because it's a loop), I can definitely see an issue not related to anything pandas. Pylance thinks the code becomes unreachable within the loop, but then thinks things right outside the loop are fine... I'll open that issue over there.

![Screenshot 2024-04-03 at 11 11 45 AM](https://github.com/pandas-dev/pandas-stubs/assets/2609368/c82d65a1-f488-4b16-a4db-0814a1a07ef9)

**Comment by lgonzalez-silen** [comment]
One last relevant item for the record: the stub used by pylance:

![Screenshot 2024-04-03 at 11 20 32 AM](https://github.com/pandas-dev/pandas-stubs/assets/2609368/77fac935-45db-4854-aaef-7f96e52e66b0)

**Comment by Dr-Irv** [comment]
Can you put this line in VSC:  `from pandas._version import _commit_hash` then put your mouse over `_commit_hash`.  If it doesn't appear, then you need to update pylance.  I do think you're on an old version of the stubs.

**Comment by lgonzalez-silen** [comment]
![Screenshot 2024-04-03 at 11 56 19 AM](https://github.com/pandas-dev/pandas-stubs/assets/2609368/62dd583d-c5cd-4a37-9c84-7b23cdfc72dc)

**Comment by Dr-Irv** [comment]
So you're on the right version.

The type checking is inferring that `df_new` has an unknown type, and it seems that pylance is matching an unknown type to `None`.   Here's an example that doesn't involve pandas that illustrates the issue you point out above (and makes it a pylance issue):
```python
from typing import Literal
from typing_extensions import Never

def rlist():
    return [5, None]

def goo(x: Literal[None]) -> Never:
    raise Exception("not valid")

for _ in range(1):
    i, _ = rlist()
    goo(i)
    print("unreachable")
    
print("reachable")
```

![image](https://github.com/pandas-dev/pandas-stubs/assets/15113894/65c40b1f-1ce9-4ad3-b6db-9e7d649e53fa)

Note that the yellow squiggles indicate where pylance can't infer the types (I have that turned on in my environment).

**Comment by twoertwein** [comment]
I would be open to removing the `None->Never` overload if it causes false negatives: we clearly can't catch similar bugs (empty lists).
