### ISSUE TITLE
VSCode questions

### ISSUE THREAD

**Issue by tonyxiao** [pandas-dev/pandas-stubs#910]
<img width="1042" alt="image" src="https://github.com/pandas-dev/pandas-stubs/assets/696842/afe8ae24-e767-4cf7-985f-2d8ce47da7a9">

I'm getting warning from vscode even though I haven't installed pandas-stubs yet. Is this stub still needed? when I cmd+click in vscode after I install the stub, should I expect to be taken to the sub?

**Comment by tonyxiao** [comment]
<img width="736" alt="image" src="https://github.com/pandas-dev/pandas-stubs/assets/696842/6cfb8150-8ec9-40a3-ba84-dbf7dcc39e4e">
also why is it that tye type of `cccc` is `Unknown`? I would expect it to be `str | Series[str]`

**Comment by Dr-Irv** [comment]
> I'm getting warning from vscode even though I haven't installed pandas-stubs yet. Is this stub still needed? when I cmd+click in vscode after I install the stub, should I expect to be taken to the sub?

The stubs are shipped with VS Code.

**Comment by Dr-Irv** [comment]
> also why is it that tye type of `cccc` is `Unknown`? I would expect it to be `str | Series[str]` based on the `pyi` file

Please provide a complete code sample that can be copy-pasted.

I'm not seeing that problem.

**Comment by tonyxiao** [comment]
You mean stubs comes by default in vscode already even without me installing pandas-stub? Where would it be stored on disk by default if so?

**Comment by Dr-Irv** [comment]
> You mean stubs comes by default in vscode already even without me installing pandas-stub? Where would it be stored on disk by default if so?

`YOUR_HOME_DIRECTORY/.vscode-server/extensions/ms-python.vscode-pylance-2024.4.102/dist/bundled/stubs/pandas/`

**Comment by tonyxiao** [comment]
ah that makes sense. It's both cool and a bit unexpected that it's already there! Thank you!
