### ISSUE TITLE
Type of mean is not set correctly

### ISSUE THREAD

**Issue by rvanlaar** [pandas-dev/pandas-stubs#93]
**Describe the bug**
The return type of mean() is set as builtins.float where in practice it's numpy.float64.

**To Reproduce**
**typing.py**
```
from typing_extensions import reveal_type
import pandas as pd

val = pd.Series([True, False, True]).mean()
reveal_type(val)
```
`mypy typing.py`
`typing.py:5: note: Revealed type is "builtins.float"`

In the interactive terminal:
```
In [1]: import pandas as pd
In [2]: val = pd.Series([True, False, True]).mean()
In [3]: type(val)
Out[3]: numpy.float64
```

**Please complete the following information:**
 - OS: Debian
 - OS: 11
 - python version: 3.9.7
 - version of type checker: mypy
 - version of installed `pandas-stubs`: 1.4.3.220704

**Additional context**
This becomes a problem when using the round function on float, `pd.Series([True, False, True]).mean().round()`
For which mypy gives this message: `error: "float" has no attribute "round"`

**Comment by bashtage** [comment]
Feels more like a pandas bug than a typing bug to me.  I would think that scalar return values should be either `float` or `int`, as NumPy tries to do.

**Comment by Dr-Irv** [comment]
It's a reasonable example to allow `pd.Series([1.2, 3.4, 5.6]).mean().round()` .

So a PR that changes the result of `Series.mean()` from `float` to `np.float64` would be OK

**Comment by jreback** [comment]
this has been long standing to convert to python scalars

so -1 on changing

**Comment by Dr-Irv** [comment]
Based on comment from @jreback, I'm going to close this, as we don't document that `Series.mean()` returns `numpy.float64`

**Comment by rvanlaar** [comment]
The quick responses are much appreciated. 

The python code is valid and the return type of float is wrong in the stubs. 
Reading the comment that Series.mean() is not documented as returning numpy.float64 does seem to be a reason to broaden the bug and update the documentation, not closing the issue.

What am I missing here?
