### ISSUE TITLE
BUG: "Categorical" has no attribute "index"

### ISSUE THREAD

**Issue by bashtage** [pandas-dev/pandas-stubs#94]
**Describe the bug**
Categorical is missing index attribute

**To Reproduce**
```python

import pandas as pd
cat = pd.Categorical(["a","b","a"])
cat.index = pd.Index([-1,-2,-3])
```

**Please complete the following information:**
- Windows 11
- Python 3.9
```
mypy                              0.961
mypy-extensions                   0.4.3
pandas                            1.4.2                              
pandas-stubs                      1.4.3.220704
```

**Comment by Dr-Irv** [comment]
It's not clear to me that `index` is documented as part of the `pd.Categorical` class. 

I think your example is not part of the pandas API.  So while it works, that's because you can create any attribute on any class in python.

**Comment by bashtage** [comment]
Agree - sorry for the trouble.
