### ISSUE TITLE
`Series.astype` is partially unknown.

### ISSUE THREAD

**Issue by JanEricNitschke** [pandas-dev/pandas-stubs#948]
Same as the other ones.

Specifically these two overloads have the problem:

```
    @overload
    def astype(
        self,
        dtype: CategoryDtypeArg,
        copy: _bool = ...,
        errors: IgnoreRaise = ...,
    ) -> Series: ...
    @overload
    def astype(
        self,
        dtype: ObjectDtypeArg | VoidDtypeArg | ExtensionDtype | DtypeObj,
        copy: _bool = ...,
        errors: IgnoreRaise = ...,
    ) -> Series: ...
```

Is there anything more concrete that can be done here besides `Series[Any]`?

Possibly a type parameter with the respective bound and return a `Series[T]`?

**Comment by JanEricNitschke** [comment]
According to the [tests](https://github.com/pandas-dev/pandas-stubs/blob/main/tests/test_series.py#L2172) it should probably be `Series[object]` (thats what the runtime checks do) or `Series[Any]` thats what they [type checking tests](https://github.com/pandas-dev/pandas-stubs/blob/main/tests/test_series.py#L2593) do.

**Comment by Dr-Irv** [comment]
The results that are not `Any` have to be part of `S1`.  I think if you use `Series[CategoricalDtype]` in the first one, and `Series[Any]` in the second, it should be OK.
