### ISSUE TITLE
BUG:  "Series[Any]" should be accepted for things that accept "Sequence[Any]"

### ISSUE THREAD

**Issue by bashtage** [pandas-dev/pandas-stubs#95]
**Describe the bug**
Categorical accepts any `Sequqnce` but Series does not present itself as a `Sequqnce`

**To Reproduce**
```python
import pandas as pd
s = pd.Series(["a","b","a"])
c = pd.Categorical(s)
```
error is
```
Argument 1 to "Categorical" has incompatible type "Series[Any]"; expected "Sequence[Any]"
```

**Please complete the following information:**
- Windows 11
- Python 3.9
```
mypy                              0.961
mypy-extensions                   0.4.3
pandas                            1.4.2                              
pandas-stubs                      1.4.3.220704
```

**Comment by twoertwein** [comment]
I think there is one issue and one feature request here: 1) a typing issue in pandas-stubs and 2) a feature request (pandas) for `Series` to implement the `Sequence` protocol.

`Series` would need to implement these methods to be a `Sequence` (and it would also need to be typed that way):
https://github.com/python/typeshed/blob/c23cb7be7547947af1086167364f6b6922f8051a/stdlib/typing.pyi#L446

I don't know how far `Series` is away from also being a `Sequence` but I really like the idea! I think `np.ndarray`s have the same issue of not being `Sequence` compatible.

**Comment by Dr-Irv** [comment]
Could just change https://github.com/pandas-dev/pandas-stubs/blob/99f3b42d23f84b0da92025eeb52db15bac446f25/pandas-stubs/core/arrays/categorical.pyi#L36
to use `ListLike` from `_typing.pyi`

PR welcome
