### ISSUE TITLE
BUG: No overload variant of "__setitem__" of "_iLocIndexerSeries" matches argument types "ndarray[Any, dtype[signedinteger[_32Bit]]]", "float"

### ISSUE THREAD

**Issue by bashtage** [pandas-dev/pandas-stubs#96]
**Describe the bug**
`iloc` on a `Series` can't assign a float when the indices are a NumPy integer array

**To Reproduce**
```python
import numpy as np
import pandas as pd

s = pd.Series([1,2,3,4])
iloc = np.array([1,2,3], dtype=np.int32)
s.iloc[iloc] = -1.0
```

I suspect that iloc should accept all numpy integer types, both signed and unsigned

more generally

```python
import pandas as pd
import numpy as np

s = pd.Series([1,2,3])
a = np.array([0,1],dtype=np.int8)
s.iloc[a] = -1
b = np.array([0,1],dtype=np.int16)
s.iloc[b] = -1
c = np.array([0,1],dtype=np.int32)
s.iloc[c] = -1
d = np.array([0,1],dtype=np.int64)
s.iloc[d] = -1
e = np.array([0,1],dtype=np.uint8)
s.iloc[e] = -1
f = np.array([0,1],dtype=np.uint16)
s.iloc[f] = -1
g = np.array([0,1],dtype=np.uint32)
s.iloc[g] = -1
h = np.array([0,1],dtype=np.uint64)
s.iloc[h] = -1
```

works as expected but each assignment fails mypy

**Please complete the following information:**
- Windows 11
- Python 3.9
```
mypy                              0.961
mypy-extensions                   0.4.3
pandas                            1.4.2                              
pandas-stubs                      1.4.3.220704
```

**Comment by Dr-Irv** [comment]
Could just change https://github.com/pandas-dev/pandas-stubs/blob/99f3b42d23f84b0da92025eeb52db15bac446f25/pandas-stubs/core/series.pyi#L95
to accept ` npt.NDArray[np.int_]` and I think that would cover all the `numpy` cases of `int` arrays.

PR welcome
