### ISSUE TITLE
GroupBy[Series].count() should have return type Series[int]

### ISSUE THREAD

**Issue by chrisyeh96** [pandas-dev/pandas-stubs#965]
**Describe the bug**

**To Reproduce**

```python
s = pd.Series(["a", "b", "a"], index=[1, 2, 2])
s.groupby(level=0).count()
```

Type checker: pyright (in VS Code)

The expected type is `Series[int]`, but instead pyright shows it as `Series[str]`

**Please complete the following information:**
 - OS: Ubuntu
 - OS Version: 22.04.4 LTS
 - python version: 3.10.12
 - version of type checker: pyright 1.1.369
 - version of installed `pandas-stubs`: 2.2.2.240603

**Comment by Dr-Irv** [comment]
Thanks for the report.  Need to remove `def count()` from `core/groupby/groupby.pyi` and then restate it in `core/groupby/generic.pyi` in both the `DataFrameGroupBy` and `SeriesGroupBy` classes.

PR with tests welcome.
