### ISSUE TITLE
Pandas stubs forces numpy <2.0.0 for python < 3.12

### ISSUE THREAD

**Issue by jenshnielsen** [pandas-dev/pandas-stubs#970]
**Describe the bug**
Following the merge of #943 it is now not supported to typecheck with pandas stubs and numpy 2 for python <3.12
Reading the description of that pr it seem the intension was just to internal test against both numpy 1 and 2. Not to force users to install v1 for python <3.12

**To Reproduce**
pip install numpy==2.0.1 pandas-stubs==2.2.2.240805

**Please complete the following information:**
 - OS: Any 
 - OS Version Any
 - python version <3.12
 - version of type checker N/A
 - version of installed `pandas-stubs` 2.2.2.240805

**Comment by Dr-Irv** [comment]
Thanks for the report.  I have a PR #971 that fixes that issue, and once merged, will do a new release.  Will yank the new release.
