### ISSUE TITLE
`lower` and `upper` from `DataFrame.clip` don't accept array-like

### ISSUE THREAD

**Issue by ldouteau** [pandas-dev/pandas-stubs#980]
**Describe the bug**
Hi,

There is an inconsistency with Pandas's doc regarding `clip`. This was already fixed for Series in #443, but not for DataFrame

https://github.com/pandas-dev/pandas-stubs/blob/2acc94d60c63484d9b664b8e68aa213a4d39b937/pandas-stubs/core/frame.pyi#L1633-L1641

**To Reproduce**
1. From https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.clip.html
```python
import pandas as pd

data = {"col_0": [9, -3, 0, -1, 5], "col_1": [-2, -7, 6, 8, -5]}
df = pd.DataFrame(data)
t = pd.Series([2, -4, -1, 6, 3])
df.clip(t, t + 4, axis=0)
```
2. Pyright 1.1.373
3. 
```
Argument of type "Series[int]" cannot be assigned to parameter "upper" of type "float | None" in function "clip"
  Type "Series[int]" is incompatible with type "float | None"
    "Series[int]" is incompatible with "float"
    "Series[int]" is incompatible with "None"Pylance[reportArgumentType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportArgumentType)
```

**Please complete the following information:**
 - OS: Windows 11
 - OS Version 23H2
 - python version 3.12.2
 - version of type checker:  Pyright 1.1.373
 - version of installed `pandas-stubs`: 2.2.2.240807

**Comment by Dr-Irv** [comment]
Thanks for the report.  PR with tests welcome.

**Comment by geoffrey-eisenbarth** [comment]
In https://github.com/pandas-dev/pandas/pull/9647/changes/1528859f44608fc1c6d02bc5fa51272e9e3cf69a, support for clipping with respect to DataFrames was added (see this test: https://github.com/pandas-dev/pandas/blob/9297b0f74ba8f82656b3897131e34154c5c8e213/pandas/tests/frame/methods/test_clip.py#L113).

Shouldn't the overloads for `df.clip()` also reflect this, or am I misunderstanding something? If this should be it's own issue, let me know and I'll redirect. I can probably put together a PR if desired.

**Comment by Dr-Irv** [comment]
> If this should be it's own issue, let me know and I'll redirect. I can probably put together a PR if desired.

If you feel that the current `pandas-stubs` doesn't support this, then create a new issue with an example, and/or a PR to address it.
