### ISSUE TITLE
limit_area argument is currently missing for the frame.pyi

### ISSUE THREAD

**Issue by AY1uZwIcJzKhaGywovQP** [pandas-dev/pandas-stubs#987]
The new `limit_area` argument is missing for the `ffill` overloads for `frame.pyi`. 

This was seen in VSCode (pylance)
```python
df = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})
df2 = df.sort_values('a')  # This infers the type correctly
df3 = df.ffill(limit=10)  # This infers the type correctly
df4 = df.ffill(limit_area='inside')  # This cannot infer the type since the `.pyi` is missing `limit_area`
```
When running error checking for types with standard, the error message is:
`No overloads for "ffill" match the provided arguments
  Argument types: (Literal['inside'])`

 - OS: Windows 10
 - python version: 3.12
 - version of type checker
 - version of installed `pandas-stubs`: This is using the latest version of pylance but I'm not sure how to check the version of pandas-stubs used. However, I don't see the entry in the [current latest commit in master](https://github.com/pandas-dev/pandas-stubs/blob/d2798db3afa01619a2fa18d0e1b82ae63f2a5ccf/pandas-stubs/core/frame.pyi#L1697-L1713)

**Comment by Dr-Irv** [comment]
Should also cover `Series.ffill()` and `Series.bfill()`
